package br.com.pais.entities;

// Generated 06/06/2011 00:07:14 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DiscipulosbatismoId generated by hbm2java
 */
@Embeddable
public class DiscipulosbatismoId implements java.io.Serializable {

	private int batismo;
	private int discipulo;

	public DiscipulosbatismoId() {
	}

	public DiscipulosbatismoId(int batismo, int discipulo) {
		this.batismo = batismo;
		this.discipulo = discipulo;
	}

	@Column(name = "batismo", nullable = false)
	public int getBatismo() {
		return this.batismo;
	}

	public void setBatismo(int batismo) {
		this.batismo = batismo;
	}

	@Column(name = "discipulo", nullable = false)
	public int getDiscipulo() {
		return this.discipulo;
	}

	public void setDiscipulo(int discipulo) {
		this.discipulo = discipulo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DiscipulosbatismoId))
			return false;
		DiscipulosbatismoId castOther = (DiscipulosbatismoId) other;

		return (this.getBatismo() == castOther.getBatismo())
				&& (this.getDiscipulo() == castOther.getDiscipulo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getBatismo();
		result = 37 * result + this.getDiscipulo();
		return result;
	}

}
