package br.com.pais.entities;

// Generated 11/05/2011 14:16:49 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Escolaliderescronogramaaulas generated by hbm2java
 */
@Entity
@Table(name = "escolaliderescronogramaaulas", catalog = "wwwpais_sistema")
public class Escolaliderescronogramaaulas implements java.io.Serializable {

	private Integer cronoAulaCod;
	private Escolalideresmaterias escolalideresmateriasByAula2;
	private Escolalideresmaterias escolalideresmateriasByAula1;
	private Escolaliderescronograma escolaliderescronograma;
	private Date dataAula;
	private Character cancelada;
	private String motivo;
	private Date dataAulaTrasnferida;
	private Set<Escolalideresfrequencia> escolalideresfrequencias = new HashSet<Escolalideresfrequencia>(
			0);

	public Escolaliderescronogramaaulas() {
	}

	public Escolaliderescronogramaaulas(
			Escolalideresmaterias escolalideresmateriasByAula2,
			Escolalideresmaterias escolalideresmateriasByAula1,
			Escolaliderescronograma escolaliderescronograma) {
		this.escolalideresmateriasByAula2 = escolalideresmateriasByAula2;
		this.escolalideresmateriasByAula1 = escolalideresmateriasByAula1;
		this.escolaliderescronograma = escolaliderescronograma;
	}

	public Escolaliderescronogramaaulas(
			Escolalideresmaterias escolalideresmateriasByAula2,
			Escolalideresmaterias escolalideresmateriasByAula1,
			Escolaliderescronograma escolaliderescronograma, Date dataAula,
			Character cancelada, String motivo, Date dataAulaTrasnferida,
			Set<Escolalideresfrequencia> escolalideresfrequencias) {
		this.escolalideresmateriasByAula2 = escolalideresmateriasByAula2;
		this.escolalideresmateriasByAula1 = escolalideresmateriasByAula1;
		this.escolaliderescronograma = escolaliderescronograma;
		this.dataAula = dataAula;
		this.cancelada = cancelada;
		this.motivo = motivo;
		this.dataAulaTrasnferida = dataAulaTrasnferida;
		this.escolalideresfrequencias = escolalideresfrequencias;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "cronoAulaCod", unique = true, nullable = false)
	public Integer getCronoAulaCod() {
		return this.cronoAulaCod;
	}

	public void setCronoAulaCod(Integer cronoAulaCod) {
		this.cronoAulaCod = cronoAulaCod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "aula2", nullable = false)
	public Escolalideresmaterias getEscolalideresmateriasByAula2() {
		return this.escolalideresmateriasByAula2;
	}

	public void setEscolalideresmateriasByAula2(
			Escolalideresmaterias escolalideresmateriasByAula2) {
		this.escolalideresmateriasByAula2 = escolalideresmateriasByAula2;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "aula1", nullable = false)
	public Escolalideresmaterias getEscolalideresmateriasByAula1() {
		return this.escolalideresmateriasByAula1;
	}

	public void setEscolalideresmateriasByAula1(
			Escolalideresmaterias escolalideresmateriasByAula1) {
		this.escolalideresmateriasByAula1 = escolalideresmateriasByAula1;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cronoCod", nullable = false)
	public Escolaliderescronograma getEscolaliderescronograma() {
		return this.escolaliderescronograma;
	}

	public void setEscolaliderescronograma(
			Escolaliderescronograma escolaliderescronograma) {
		this.escolaliderescronograma = escolaliderescronograma;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dataAula", length = 10)
	public Date getDataAula() {
		return this.dataAula;
	}

	public void setDataAula(Date dataAula) {
		this.dataAula = dataAula;
	}

	@Column(name = "cancelada", length = 1)
	public Character getCancelada() {
		return this.cancelada;
	}

	public void setCancelada(Character cancelada) {
		this.cancelada = cancelada;
	}

	@Column(name = "motivo", length = 65535)
	public String getMotivo() {
		return this.motivo;
	}

	public void setMotivo(String motivo) {
		this.motivo = motivo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dataAulaTrasnferida", length = 10)
	public Date getDataAulaTrasnferida() {
		return this.dataAulaTrasnferida;
	}

	public void setDataAulaTrasnferida(Date dataAulaTrasnferida) {
		this.dataAulaTrasnferida = dataAulaTrasnferida;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "escolaliderescronogramaaulas")
	public Set<Escolalideresfrequencia> getEscolalideresfrequencias() {
		return this.escolalideresfrequencias;
	}

	public void setEscolalideresfrequencias(
			Set<Escolalideresfrequencia> escolalideresfrequencias) {
		this.escolalideresfrequencias = escolalideresfrequencias;
	}

}
