package br.com.pais.entities;

// Generated 11/05/2011 14:16:49 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Escolaliderestiposmovimento generated by hbm2java
 */
@Entity
@Table(name = "escolaliderestiposmovimento", catalog = "wwwpais_sistema")
public class Escolaliderestiposmovimento implements java.io.Serializable {

	private Integer elTipoMovCod;
	private Escolalideresindicador escolalideresindicador;
	private String elTipoMovNome;
	private Set<Escolalideresfinanceiro> escolalideresfinanceiros = new HashSet<Escolalideresfinanceiro>(
			0);

	public Escolaliderestiposmovimento() {
	}

	public Escolaliderestiposmovimento(
			Escolalideresindicador escolalideresindicador) {
		this.escolalideresindicador = escolalideresindicador;
	}

	public Escolaliderestiposmovimento(
			Escolalideresindicador escolalideresindicador,
			String elTipoMovNome,
			Set<Escolalideresfinanceiro> escolalideresfinanceiros) {
		this.escolalideresindicador = escolalideresindicador;
		this.elTipoMovNome = elTipoMovNome;
		this.escolalideresfinanceiros = escolalideresfinanceiros;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "elTipoMovCod", unique = true, nullable = false)
	public Integer getElTipoMovCod() {
		return this.elTipoMovCod;
	}

	public void setElTipoMovCod(Integer elTipoMovCod) {
		this.elTipoMovCod = elTipoMovCod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "elIndicCod", nullable = false)
	public Escolalideresindicador getEscolalideresindicador() {
		return this.escolalideresindicador;
	}

	public void setEscolalideresindicador(
			Escolalideresindicador escolalideresindicador) {
		this.escolalideresindicador = escolalideresindicador;
	}

	@Column(name = "elTipoMovNome", length = 80)
	public String getElTipoMovNome() {
		return this.elTipoMovNome;
	}

	public void setElTipoMovNome(String elTipoMovNome) {
		this.elTipoMovNome = elTipoMovNome;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "escolaliderestiposmovimento")
	public Set<Escolalideresfinanceiro> getEscolalideresfinanceiros() {
		return this.escolalideresfinanceiros;
	}

	public void setEscolalideresfinanceiros(
			Set<Escolalideresfinanceiro> escolalideresfinanceiros) {
		this.escolalideresfinanceiros = escolalideresfinanceiros;
	}

}
