package br.com.pais.entities;

// Generated 11/05/2011 14:16:49 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Escolalideresnotas generated by hbm2java
 */
@Entity
@Table(name = "escolalideresnotas", catalog = "wwwpais_sistema")
public class Escolalideresnotas implements java.io.Serializable {

	private Integer elNotaCod;
	private Escolalideresdiscipulos escolalideresdiscipulos;
	private Escolalideresmodulo escolalideresmodulo;
	private Double nota1;
	private Double nota2;
	private Double nota3;
	private Double media;

	public Escolalideresnotas() {
	}

	public Escolalideresnotas(Escolalideresdiscipulos escolalideresdiscipulos,
			Escolalideresmodulo escolalideresmodulo) {
		this.escolalideresdiscipulos = escolalideresdiscipulos;
		this.escolalideresmodulo = escolalideresmodulo;
	}

	public Escolalideresnotas(Escolalideresdiscipulos escolalideresdiscipulos,
			Escolalideresmodulo escolalideresmodulo, Double nota1,
			Double nota2, Double nota3, Double media) {
		this.escolalideresdiscipulos = escolalideresdiscipulos;
		this.escolalideresmodulo = escolalideresmodulo;
		this.nota1 = nota1;
		this.nota2 = nota2;
		this.nota3 = nota3;
		this.media = media;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "elNotaCod", unique = true, nullable = false)
	public Integer getElNotaCod() {
		return this.elNotaCod;
	}

	public void setElNotaCod(Integer elNotaCod) {
		this.elNotaCod = elNotaCod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "disipuloCod", nullable = false)
	public Escolalideresdiscipulos getEscolalideresdiscipulos() {
		return this.escolalideresdiscipulos;
	}

	public void setEscolalideresdiscipulos(
			Escolalideresdiscipulos escolalideresdiscipulos) {
		this.escolalideresdiscipulos = escolalideresdiscipulos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "moduloCod", nullable = false)
	public Escolalideresmodulo getEscolalideresmodulo() {
		return this.escolalideresmodulo;
	}

	public void setEscolalideresmodulo(Escolalideresmodulo escolalideresmodulo) {
		this.escolalideresmodulo = escolalideresmodulo;
	}

	@Column(name = "nota1", precision = 2)
	public Double getNota1() {
		return this.nota1;
	}

	public void setNota1(Double nota1) {
		this.nota1 = nota1;
	}

	@Column(name = "nota2", precision = 2)
	public Double getNota2() {
		return this.nota2;
	}

	public void setNota2(Double nota2) {
		this.nota2 = nota2;
	}

	@Column(name = "nota3", precision = 2)
	public Double getNota3() {
		return this.nota3;
	}

	public void setNota3(Double nota3) {
		this.nota3 = nota3;
	}

	@Column(name = "media", precision = 2)
	public Double getMedia() {
		return this.media;
	}

	public void setMedia(Double media) {
		this.media = media;
	}

}
