package br.com.pais.entities;

// Generated 11/05/2011 14:16:49 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Igrejas generated by hbm2java
 */
@Entity
@Table(name = "igrejas", catalog = "wwwpais_sistema")
public class Igrejas implements java.io.Serializable {

	private int igrcod;
	private Paises paises;
	private Discipulos discipulosByIgrresponsavelm;
	private Logradouro logradouro;
	private Discipulos discipulosByIgrresponsavelf;
	private String igrnome;
	private String igrlogo;
	private String igrcidade;
	private String igrestado;
	private int igrnum;
	private String igrcomplemento;
	private String igrtelfixo;
	private String igrtelcelular;
	private String igremail;
	private Byte igrdiavencimento;
	private Character igrstatus;
	private Set<Financeiroigrejas> financeiroigrejases = new HashSet<Financeiroigrejas>(
			0);
	private Set<Discipulos> discipuloses = new HashSet<Discipulos>(0);

	public Igrejas() {
	}

	public Igrejas(int igrcod, Paises paises,
			Discipulos discipulosByIgrresponsavelm, Logradouro logradouro,
			Discipulos discipulosByIgrresponsavelf, String igrnome) {
		this.igrcod = igrcod;
		this.paises = paises;
		this.discipulosByIgrresponsavelm = discipulosByIgrresponsavelm;
		this.logradouro = logradouro;
		this.discipulosByIgrresponsavelf = discipulosByIgrresponsavelf;
		this.igrnome = igrnome;
	}

	public Igrejas(int igrcod, Paises paises,
			Discipulos discipulosByIgrresponsavelm, Logradouro logradouro,
			Discipulos discipulosByIgrresponsavelf, String igrnome,
			String igrlogo, String igrcidade, String igrestado,
			String igrtelfixo, String igrtelcelular, String igremail,
			Byte igrdiavencimento, Character igrstatus,
			Set<Financeiroigrejas> financeiroigrejases,
			Set<Discipulos> discipuloses) {
		this.igrcod = igrcod;
		this.paises = paises;
		this.discipulosByIgrresponsavelm = discipulosByIgrresponsavelm;
		this.logradouro = logradouro;
		this.discipulosByIgrresponsavelf = discipulosByIgrresponsavelf;
		this.igrnome = igrnome;
		this.igrlogo = igrlogo;
		this.igrcidade = igrcidade;
		this.igrestado = igrestado;
		this.igrtelfixo = igrtelfixo;
		this.igrtelcelular = igrtelcelular;
		this.igremail = igremail;
		this.igrdiavencimento = igrdiavencimento;
		this.igrstatus = igrstatus;
		this.financeiroigrejases = financeiroigrejases;
		this.discipuloses = discipuloses;
	}

	@Id
	@Column(name = "igrcod", unique = true, nullable = false)
	public int getIgrcod() {
		return this.igrcod;
	}

	public void setIgrcod(int igrcod) {
		this.igrcod = igrcod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "igrpaises", nullable = false)
	public Paises getPaises() {
		return this.paises;
	}

	public void setPaises(Paises paises) {
		this.paises = paises;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "igrresponsavelm", nullable = false)
	public Discipulos getDiscipulosByIgrresponsavelm() {
		return this.discipulosByIgrresponsavelm;
	}

	public void setDiscipulosByIgrresponsavelm(
			Discipulos discipulosByIgrresponsavelm) {
		this.discipulosByIgrresponsavelm = discipulosByIgrresponsavelm;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "igrlogradouro", nullable = false)
	public Logradouro getLogradouro() {
		return this.logradouro;
	}

	public void setLogradouro(Logradouro logradouro) {
		this.logradouro = logradouro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "igrresponsavelf", nullable = false)
	public Discipulos getDiscipulosByIgrresponsavelf() {
		return this.discipulosByIgrresponsavelf;
	}

	public void setDiscipulosByIgrresponsavelf(
			Discipulos discipulosByIgrresponsavelf) {
		this.discipulosByIgrresponsavelf = discipulosByIgrresponsavelf;
	}

	@Column(name = "igrnome", nullable = false, length = 100)
	public String getIgrnome() {
		return this.igrnome;
	}

	public void setIgrnome(String igrnome) {
		this.igrnome = igrnome;
	}

	@Column(name = "igrlogo", length = 100)
	public String getIgrlogo() {
		return this.igrlogo;
	}

	public void setIgrlogo(String igrlogo) {
		this.igrlogo = igrlogo;
	}

	@Column(name = "igrcidade", length = 100)
	public String getIgrcidade() {
		return this.igrcidade;
	}

	public void setIgrcidade(String igrcidade) {
		this.igrcidade = igrcidade;
	}

	@Column(name = "igrestado", length = 100)
	public String getIgrestado() {
		return this.igrestado;
	}

	public void setIgrestado(String igrestado) {
		this.igrestado = igrestado;
	}

	@Column(name = "igrtelfixo", length = 14)
	public String getIgrtelfixo() {
		return this.igrtelfixo;
	}

	public void setIgrtelfixo(String igrtelfixo) {
		this.igrtelfixo = igrtelfixo;
	}

	@Column(name = "igrtelcelular", length = 14)
	public String getIgrtelcelular() {
		return this.igrtelcelular;
	}

	public void setIgrtelcelular(String igrtelcelular) {
		this.igrtelcelular = igrtelcelular;
	}

	@Column(name = "igremail", length = 100)
	public String getIgremail() {
		return this.igremail;
	}

	public void setIgremail(String igremail) {
		this.igremail = igremail;
	}

	@Column(name = "igrdiavencimento")
	public Byte getIgrdiavencimento() {
		return this.igrdiavencimento;
	}

	public void setIgrdiavencimento(Byte igrdiavencimento) {
		this.igrdiavencimento = igrdiavencimento;
	}

	@Column(name = "igrstatus", length = 1)
	public Character getIgrstatus() {
		return this.igrstatus;
	}

	public void setIgrstatus(Character igrstatus) {
		this.igrstatus = igrstatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "igrejas")
	public Set<Financeiroigrejas> getFinanceiroigrejases() {
		return this.financeiroigrejases;
	}

	public void setFinanceiroigrejases(
			Set<Financeiroigrejas> financeiroigrejases) {
		this.financeiroigrejases = financeiroigrejases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "igrejas")
	public Set<Discipulos> getDiscipuloses() {
		return this.discipuloses;
	}

	public void setDiscipuloses(Set<Discipulos> discipuloses) {
		this.discipuloses = discipuloses;
	}

	/**
	 * @return the igrnum
	 */
	@Column(name = "igrnum")
	public int getIgrnum() {
		return igrnum;
	}

	/**
	 * @param igrnum the igrnum to set
	 */
	public void setIgrnum(int igrnum) {
		this.igrnum = igrnum;
	}

	/**
	 * @return the igrcomplemento
	 */
	@Column(name = "igrnum", length = 80 )
	public String getIgrcomplemento() {
		return igrcomplemento;
	}

	/**
	 * @param igrcomplemento the igrcomplemento to set
	 */
	public void setIgrcomplemento(String igrcomplemento) {
		this.igrcomplemento = igrcomplemento;
	}

}
