package br.com.pais.domain;

// Generated 27/04/2010 23:53:17 by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * FormacaoEclesiasticas generated by hbm2java
 */
@Entity
@Table(name = "tbl_FormacaoEclesiasticas", catalog = "pais", uniqueConstraints = @UniqueConstraint(columnNames = "forDescricao"))
public class FormacaoEclesiasticas implements java.io.Serializable {

	private Integer forCod;
	private String forDescricao;
	private Set<Discipulos> tblDiscipuloses = new HashSet<Discipulos>(0);

	public FormacaoEclesiasticas() {
	}

	public FormacaoEclesiasticas(String forDescricao) {
		this.forDescricao = forDescricao;
	}

	public FormacaoEclesiasticas(String forDescricao,
			Set<Discipulos> tblDiscipuloses) {
		this.forDescricao = forDescricao;
		this.tblDiscipuloses = tblDiscipuloses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "forCod", unique = true, nullable = false)
	public Integer getForCod() {
		return this.forCod;
	}

	public void setForCod(Integer forCod) {
		this.forCod = forCod;
	}

	@Column(name = "forDescricao", unique = true, nullable = false, length = 60)
	public String getForDescricao() {
		return this.forDescricao;
	}

	public void setForDescricao(String forDescricao) {
		this.forDescricao = forDescricao;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "tblFormacaoEclesiasticases")
	public Set<Discipulos> getTblDiscipuloses() {
		return this.tblDiscipuloses;
	}

	public void setTblDiscipuloses(Set<Discipulos> tblDiscipuloses) {
		this.tblDiscipuloses = tblDiscipuloses;
	}

}
