package br.com.pais.domain;

// Generated 27/04/2010 23:53:17 by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Localidade generated by hbm2java
 */
@Entity
@Table(name = "tbl_localidade", catalog = "pais")
public class Localidade implements java.io.Serializable {

	private int locCod;
	private Estado estado;
	private String locNoSub;
	private String locNo;
	private String locCep;
	private String locUfeSg;
	private Integer locInSituacao;
	private String locInTipoLocalidade;
	private Integer locNuSequencialSub;
	private String locKeyDne;
	private Set<Bairro> bairros = new HashSet<Bairro>(0);

	public Localidade() {
	}

	public Localidade(int locCod, Estado estado,
			String locInTipoLocalidade) {
		this.locCod = locCod;
		this.estado = estado;
		this.locInTipoLocalidade = locInTipoLocalidade;
	}

	public Localidade(int locCod, Estado estado, String locNoSub,
			String locNo, String locCep, String locUfeSg,
			Integer locInSituacao, String locInTipoLocalidade,
			Integer locNuSequencialSub, String locKeyDne,
			Set<Bairro> bairros) {
		this.locCod = locCod;
		this.estado = estado;
		this.locNoSub = locNoSub;
		this.locNo = locNo;
		this.locCep = locCep;
		this.locUfeSg = locUfeSg;
		this.locInSituacao = locInSituacao;
		this.locInTipoLocalidade = locInTipoLocalidade;
		this.locNuSequencialSub = locNuSequencialSub;
		this.locKeyDne = locKeyDne;
		this.bairros = bairros;
	}

	@Id
	@Column(name = "locCod", unique = true, nullable = false)
	public int getLocCod() {
		return this.locCod;
	}

	public void setLocCod(int locCod) {
		this.locCod = locCod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tbl_estado_estCod", nullable = false)
	public Estado getTblEstado() {
		return this.estado;
	}

	public void setTblEstado(Estado estado) {
		this.estado = estado;
	}

	@Column(name = "locNoSub", length = 50)
	public String getLocNoSub() {
		return this.locNoSub;
	}

	public void setLocNoSub(String locNoSub) {
		this.locNoSub = locNoSub;
	}

	@Column(name = "locNo", length = 60)
	public String getLocNo() {
		return this.locNo;
	}

	public void setLocNo(String locNo) {
		this.locNo = locNo;
	}

	@Column(name = "locCep", length = 16)
	public String getLocCep() {
		return this.locCep;
	}

	public void setLocCep(String locCep) {
		this.locCep = locCep;
	}

	@Column(name = "locUfeSG", length = 2)
	public String getLocUfeSg() {
		return this.locUfeSg;
	}

	public void setLocUfeSg(String locUfeSg) {
		this.locUfeSg = locUfeSg;
	}

	@Column(name = "locInSituacao")
	public Integer getLocInSituacao() {
		return this.locInSituacao;
	}

	public void setLocInSituacao(Integer locInSituacao) {
		this.locInSituacao = locInSituacao;
	}

	@Column(name = "locInTipoLocalidade", nullable = false, length = 1)
	public String getLocInTipoLocalidade() {
		return this.locInTipoLocalidade;
	}

	public void setLocInTipoLocalidade(String locInTipoLocalidade) {
		this.locInTipoLocalidade = locInTipoLocalidade;
	}

	@Column(name = "locNuSequencialSub")
	public Integer getLocNuSequencialSub() {
		return this.locNuSequencialSub;
	}

	public void setLocNuSequencialSub(Integer locNuSequencialSub) {
		this.locNuSequencialSub = locNuSequencialSub;
	}

	@Column(name = "locKeyDne", length = 16)
	public String getLocKeyDne() {
		return this.locKeyDne;
	}

	public void setLocKeyDne(String locKeyDne) {
		this.locKeyDne = locKeyDne;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblLocalidade")
	public Set<Bairro> getTblBairros() {
		return this.bairros;
	}

	public void setTblBairros(Set<Bairro> bairros) {
		this.bairros = bairros;
	}

}
