package br.com.pais.domain;

// Generated 27/04/2010 23:53:17 by Hibernate Tools 3.3.0.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Movimento generated by hbm2java
 */
@Entity
@Table(name = "tbl_Movimento", catalog = "pais")
public class Movimento implements java.io.Serializable {

	private int movCod;
	private Celulas celulas;
	private Date movData;
	private String movTipo;
	private Byte movValor;
	private Set<Repasse> repasses = new HashSet<Repasse>(0);

	public Movimento() {
	}

	public Movimento(int movCod, Celulas celulas) {
		this.movCod = movCod;
		this.celulas = celulas;
	}

	public Movimento(int movCod, Celulas celulas, Date movData,
			String movTipo, Byte movValor, Set<Repasse> repasses) {
		this.movCod = movCod;
		this.celulas = celulas;
		this.movData = movData;
		this.movTipo = movTipo;
		this.movValor = movValor;
		this.repasses = repasses;
	}

	@Id
	@Column(name = "movCod", unique = true, nullable = false)
	public int getMovCod() {
		return this.movCod;
	}

	public void setMovCod(int movCod) {
		this.movCod = movCod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
			@JoinColumn(name = "celCod", referencedColumnName = "celCod", nullable = false),
			@JoinColumn(name = "funCod", referencedColumnName = "funCod", nullable = false),
			@JoinColumn(name = "disCod", referencedColumnName = "disCod", nullable = false) })
	public Celulas getTblCelulas() {
		return this.celulas;
	}

	public void setTblCelulas(Celulas celulas) {
		this.celulas = celulas;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "movData", length = 10)
	public Date getMovData() {
		return this.movData;
	}

	public void setMovData(Date movData) {
		this.movData = movData;
	}

	@Column(name = "movTipo", length = 60)
	public String getMovTipo() {
		return this.movTipo;
	}

	public void setMovTipo(String movTipo) {
		this.movTipo = movTipo;
	}

	@Column(name = "movValor", precision = 2, scale = 0)
	public Byte getMovValor() {
		return this.movValor;
	}

	public void setMovValor(Byte movValor) {
		this.movValor = movValor;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblMovimento")
	public Set<Repasse> getTblRepasses() {
		return this.repasses;
	}

	public void setTblRepasses(Set<Repasse> repasses) {
		this.repasses = repasses;
	}

}
