package br.com.pais.beans;

// Generated 26/04/2010 13:44:43 by Hibernate Tools 3.3.0.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Encontros generated by hbm2java
 */
@Entity
@Table(name = "tbl_encontros", catalog = "pais")
public class Encontros implements java.io.Serializable {

	private int encCod;
	private Logradouro tblLogradouro;
	private Date encDataRealizacao;
	private String encDescricao;
	private Set tblDiscipuloses = new HashSet(0);

	public Encontros() {
	}

	public Encontros(int encCod, Logradouro tblLogradouro) {
		this.encCod = encCod;
		this.tblLogradouro = tblLogradouro;
	}

	public Encontros(int encCod, Logradouro tblLogradouro,
			Date encDataRealizacao, String encDescricao, Set tblDiscipuloses) {
		this.encCod = encCod;
		this.tblLogradouro = tblLogradouro;
		this.encDataRealizacao = encDataRealizacao;
		this.encDescricao = encDescricao;
		this.tblDiscipuloses = tblDiscipuloses;
	}

	@Id
	@Column(name = "EncCod", unique = true, nullable = false)
	public int getEncCod() {
		return this.encCod;
	}

	public void setEncCod(int encCod) {
		this.encCod = encCod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EncLocal", nullable = false)
	public Logradouro getTblLogradouro() {
		return this.tblLogradouro;
	}

	public void setTblLogradouro(Logradouro tblLogradouro) {
		this.tblLogradouro = tblLogradouro;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EncDataRealizacao", length = 10)
	public Date getEncDataRealizacao() {
		return this.encDataRealizacao;
	}

	public void setEncDataRealizacao(Date encDataRealizacao) {
		this.encDataRealizacao = encDataRealizacao;
	}

	@Column(name = "EncDescricao")
	public String getEncDescricao() {
		return this.encDescricao;
	}

	public void setEncDescricao(String encDescricao) {
		this.encDescricao = encDescricao;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "tblEncontroses")
	public Set getTblDiscipuloses() {
		return this.tblDiscipuloses;
	}

	public void setTblDiscipuloses(Set tblDiscipuloses) {
		this.tblDiscipuloses = tblDiscipuloses;
	}

}
