package br.com.pais.beans;

// Generated 26/04/2010 13:44:43 by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estado generated by hbm2java
 */
@Entity
@Table(name = "tbl_estado", catalog = "pais")
public class Estado implements java.io.Serializable {

	private int estCod;
	private String estNo;
	private String estRad1Ini;
	private String estSuf1ini;
	private String estRad1fim;
	private String estSuf1fim;
	private String estRad2ini;
	private String estSuf2ini;
	private String estRad2fim;
	private String estSuf2fim;
	private Set tblLocalidades = new HashSet(0);

	public Estado() {
	}

	public Estado(int estCod, String estNo, String estRad1Ini,
			String estSuf1ini, String estRad1fim, String estSuf1fim) {
		this.estCod = estCod;
		this.estNo = estNo;
		this.estRad1Ini = estRad1Ini;
		this.estSuf1ini = estSuf1ini;
		this.estRad1fim = estRad1fim;
		this.estSuf1fim = estSuf1fim;
	}

	public Estado(int estCod, String estNo, String estRad1Ini,
			String estSuf1ini, String estRad1fim, String estSuf1fim,
			String estRad2ini, String estSuf2ini, String estRad2fim,
			String estSuf2fim, Set tblLocalidades) {
		this.estCod = estCod;
		this.estNo = estNo;
		this.estRad1Ini = estRad1Ini;
		this.estSuf1ini = estSuf1ini;
		this.estRad1fim = estRad1fim;
		this.estSuf1fim = estSuf1fim;
		this.estRad2ini = estRad2ini;
		this.estSuf2ini = estSuf2ini;
		this.estRad2fim = estRad2fim;
		this.estSuf2fim = estSuf2fim;
		this.tblLocalidades = tblLocalidades;
	}

	@Id
	@Column(name = "estCod", unique = true, nullable = false)
	public int getEstCod() {
		return this.estCod;
	}

	public void setEstCod(int estCod) {
		this.estCod = estCod;
	}

	@Column(name = "estNo", nullable = false, length = 72)
	public String getEstNo() {
		return this.estNo;
	}

	public void setEstNo(String estNo) {
		this.estNo = estNo;
	}

	@Column(name = "estRad1_ini", nullable = false, length = 5)
	public String getEstRad1Ini() {
		return this.estRad1Ini;
	}

	public void setEstRad1Ini(String estRad1Ini) {
		this.estRad1Ini = estRad1Ini;
	}

	@Column(name = "estSuf1Ini", nullable = false, length = 3)
	public String getEstSuf1ini() {
		return this.estSuf1ini;
	}

	public void setEstSuf1ini(String estSuf1ini) {
		this.estSuf1ini = estSuf1ini;
	}

	@Column(name = "estRad1Fim", nullable = false, length = 5)
	public String getEstRad1fim() {
		return this.estRad1fim;
	}

	public void setEstRad1fim(String estRad1fim) {
		this.estRad1fim = estRad1fim;
	}

	@Column(name = "estSuf1Fim", nullable = false, length = 3)
	public String getEstSuf1fim() {
		return this.estSuf1fim;
	}

	public void setEstSuf1fim(String estSuf1fim) {
		this.estSuf1fim = estSuf1fim;
	}

	@Column(name = "estRad2Ini", length = 5)
	public String getEstRad2ini() {
		return this.estRad2ini;
	}

	public void setEstRad2ini(String estRad2ini) {
		this.estRad2ini = estRad2ini;
	}

	@Column(name = "estSuf2Ini", length = 3)
	public String getEstSuf2ini() {
		return this.estSuf2ini;
	}

	public void setEstSuf2ini(String estSuf2ini) {
		this.estSuf2ini = estSuf2ini;
	}

	@Column(name = "estRad2Fim", length = 5)
	public String getEstRad2fim() {
		return this.estRad2fim;
	}

	public void setEstRad2fim(String estRad2fim) {
		this.estRad2fim = estRad2fim;
	}

	@Column(name = "estSuf2Fim", length = 3)
	public String getEstSuf2fim() {
		return this.estSuf2fim;
	}

	public void setEstSuf2fim(String estSuf2fim) {
		this.estSuf2fim = estSuf2fim;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblEstado")
	public Set getTblLocalidades() {
		return this.tblLocalidades;
	}

	public void setTblLocalidades(Set tblLocalidades) {
		this.tblLocalidades = tblLocalidades;
	}

}
