package br.com.pais.beans;

// Generated 26/04/2010 13:44:43 by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Estadocivil generated by hbm2java
 */
@Entity
@Table(name = "tbl_estadocivil", catalog = "pais", uniqueConstraints = @UniqueConstraint(columnNames = "Estdescricao"))
public class Estadocivil implements java.io.Serializable {

	private Integer estCod;
	private String estdescricao;
	private Set tblDiscipuloses = new HashSet(0);

	public Estadocivil() {
	}

	public Estadocivil(String estdescricao, Set tblDiscipuloses) {
		this.estdescricao = estdescricao;
		this.tblDiscipuloses = tblDiscipuloses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "EstCod", unique = true, nullable = false)
	public Integer getEstCod() {
		return this.estCod;
	}

	public void setEstCod(Integer estCod) {
		this.estCod = estCod;
	}

	@Column(name = "Estdescricao", unique = true, length = 60)
	public String getEstdescricao() {
		return this.estdescricao;
	}

	public void setEstdescricao(String estdescricao) {
		this.estdescricao = estdescricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblEstadocivil")
	public Set getTblDiscipuloses() {
		return this.tblDiscipuloses;
	}

	public void setTblDiscipuloses(Set tblDiscipuloses) {
		this.tblDiscipuloses = tblDiscipuloses;
	}

}
