package br.com.pais.beans;

// Generated 26/04/2010 13:44:43 by Hibernate Tools 3.3.0.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Movimento generated by hbm2java
 */
@Entity
@Table(name = "tbl_movimento", catalog = "pais")
public class Movimento implements java.io.Serializable {

	private int movCod;
	private Date movData;
	private String movTipo;
	private Byte movValor;
	private int celCod;
	private int funCod;
	private int disCod;
	private Set tblRepasses = new HashSet(0);

	public Movimento() {
	}

	public Movimento(int movCod, int celCod, int funCod, int disCod) {
		this.movCod = movCod;
		this.celCod = celCod;
		this.funCod = funCod;
		this.disCod = disCod;
	}

	public Movimento(int movCod, Date movData, String movTipo,
			Byte movValor, int celCod, int funCod, int disCod, Set tblRepasses) {
		this.movCod = movCod;
		this.movData = movData;
		this.movTipo = movTipo;
		this.movValor = movValor;
		this.celCod = celCod;
		this.funCod = funCod;
		this.disCod = disCod;
		this.tblRepasses = tblRepasses;
	}

	@Id
	@Column(name = "movCod", unique = true, nullable = false)
	public int getMovCod() {
		return this.movCod;
	}

	public void setMovCod(int movCod) {
		this.movCod = movCod;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "movData", length = 10)
	public Date getMovData() {
		return this.movData;
	}

	public void setMovData(Date movData) {
		this.movData = movData;
	}

	@Column(name = "movTipo", length = 60)
	public String getMovTipo() {
		return this.movTipo;
	}

	public void setMovTipo(String movTipo) {
		this.movTipo = movTipo;
	}

	@Column(name = "movValor", precision = 2, scale = 0)
	public Byte getMovValor() {
		return this.movValor;
	}

	public void setMovValor(Byte movValor) {
		this.movValor = movValor;
	}

	@Column(name = "celCod", nullable = false)
	public int getCelCod() {
		return this.celCod;
	}

	public void setCelCod(int celCod) {
		this.celCod = celCod;
	}

	@Column(name = "funCod", nullable = false)
	public int getFunCod() {
		return this.funCod;
	}

	public void setFunCod(int funCod) {
		this.funCod = funCod;
	}

	@Column(name = "disCod", nullable = false)
	public int getDisCod() {
		return this.disCod;
	}

	public void setDisCod(int disCod) {
		this.disCod = disCod;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblMovimento")
	public Set getTblRepasses() {
		return this.tblRepasses;
	}

	public void setTblRepasses(Set tblRepasses) {
		this.tblRepasses = tblRepasses;
	}

}
