package br.com.pais.beans;

// Generated 26/04/2010 13:44:43 by Hibernate Tools 3.3.0.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Discipulos generated by hbm2java
 */
@Entity
@Table(name = "tbl_discipulos", catalog = "pais")
public class Discipulos implements java.io.Serializable {

	private Integer disCod;
	private Estadocivil tblEstadocivil;
	private Discipulos tblDiscipulos;
	private Logradouro tblLogradouro;
	private Geracoes tblGeracoes;
	private String disfoto;
	private String disemail;
	private String disnome;
	private String dispai;
	private String disconjuge;
	private String dismae;
	private Date disdatanascimento;
	private char dism12;
	private Set tblRepasses = new HashSet(0);
	private Set tblEncontroses = new HashSet(0);
	private Set tblDiscipuloses = new HashSet(0);
	private Set tblFormacaoacademicas = new HashSet(0);
	private Set tblFormacaoeclesiasticases = new HashSet(0);
	private Set tblFuncaoeclesiasticases = new HashSet(0);
	private Set tblDocumentoses = new HashSet(0);

	public Discipulos() {
	}

	public Discipulos(Estadocivil tblEstadocivil,
			Discipulos tblDiscipulos, Logradouro tblLogradouro,
			Geracoes tblGeracoes, String disnome, String disconjuge,
			String dismae, Date disdatanascimento, char dism12) {
		this.tblEstadocivil = tblEstadocivil;
		this.tblDiscipulos = tblDiscipulos;
		this.tblLogradouro = tblLogradouro;
		this.tblGeracoes = tblGeracoes;
		this.disnome = disnome;
		this.disconjuge = disconjuge;
		this.dismae = dismae;
		this.disdatanascimento = disdatanascimento;
		this.dism12 = dism12;
	}

	public Discipulos(Estadocivil tblEstadocivil,
			Discipulos tblDiscipulos, Logradouro tblLogradouro,
			Geracoes tblGeracoes, String disfoto, String disemail,
			String disnome, String dispai, String disconjuge, String dismae,
			Date disdatanascimento, char dism12, Set tblRepasses,
			Set tblEncontroses, Set tblDiscipuloses, Set tblFormacaoacademicas,
			Set tblFormacaoeclesiasticases, Set tblFuncaoeclesiasticases,
			Set tblDocumentoses) {
		this.tblEstadocivil = tblEstadocivil;
		this.tblDiscipulos = tblDiscipulos;
		this.tblLogradouro = tblLogradouro;
		this.tblGeracoes = tblGeracoes;
		this.disfoto = disfoto;
		this.disemail = disemail;
		this.disnome = disnome;
		this.dispai = dispai;
		this.disconjuge = disconjuge;
		this.dismae = dismae;
		this.disdatanascimento = disdatanascimento;
		this.dism12 = dism12;
		this.tblRepasses = tblRepasses;
		this.tblEncontroses = tblEncontroses;
		this.tblDiscipuloses = tblDiscipuloses;
		this.tblFormacaoacademicas = tblFormacaoacademicas;
		this.tblFormacaoeclesiasticases = tblFormacaoeclesiasticases;
		this.tblFuncaoeclesiasticases = tblFuncaoeclesiasticases;
		this.tblDocumentoses = tblDocumentoses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "disCod", unique = true, nullable = false)
	public Integer getDisCod() {
		return this.disCod;
	}

	public void setDisCod(Integer disCod) {
		this.disCod = disCod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "disEstCivil", nullable = false)
	public Estadocivil getTblEstadocivil() {
		return this.tblEstadocivil;
	}

	public void setTblEstadocivil(Estadocivil tblEstadocivil) {
		this.tblEstadocivil = tblEstadocivil;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "disdiscipulador", nullable = false)
	public Discipulos getTblDiscipulos() {
		return this.tblDiscipulos;
	}

	public void setTblDiscipulos(Discipulos tblDiscipulos) {
		this.tblDiscipulos = tblDiscipulos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "disEndere�o", nullable = false)
	public Logradouro getTblLogradouro() {
		return this.tblLogradouro;
	}

	public void setTblLogradouro(Logradouro tblLogradouro) {
		this.tblLogradouro = tblLogradouro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "disGeracao", nullable = false)
	public Geracoes getTblGeracoes() {
		return this.tblGeracoes;
	}

	public void setTblGeracoes(Geracoes tblGeracoes) {
		this.tblGeracoes = tblGeracoes;
	}

	@Column(name = "disfoto", length = 60)
	public String getDisfoto() {
		return this.disfoto;
	}

	public void setDisfoto(String disfoto) {
		this.disfoto = disfoto;
	}

	@Column(name = "disemail", length = 60)
	public String getDisemail() {
		return this.disemail;
	}

	public void setDisemail(String disemail) {
		this.disemail = disemail;
	}

	@Column(name = "disnome", nullable = false, length = 60)
	public String getDisnome() {
		return this.disnome;
	}

	public void setDisnome(String disnome) {
		this.disnome = disnome;
	}

	@Column(name = "dispai", length = 60)
	public String getDispai() {
		return this.dispai;
	}

	public void setDispai(String dispai) {
		this.dispai = dispai;
	}

	@Column(name = "disconjuge", nullable = false, length = 60)
	public String getDisconjuge() {
		return this.disconjuge;
	}

	public void setDisconjuge(String disconjuge) {
		this.disconjuge = disconjuge;
	}

	@Column(name = "dismae", nullable = false, length = 60)
	public String getDismae() {
		return this.dismae;
	}

	public void setDismae(String dismae) {
		this.dismae = dismae;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "disdatanascimento", nullable = false, length = 10)
	public Date getDisdatanascimento() {
		return this.disdatanascimento;
	}

	public void setDisdatanascimento(Date disdatanascimento) {
		this.disdatanascimento = disdatanascimento;
	}

	@Column(name = "dism12", nullable = false, length = 1)
	public char getDism12() {
		return this.dism12;
	}

	public void setDism12(char dism12) {
		this.dism12 = dism12;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblDiscipulos")
	public Set getTblRepasses() {
		return this.tblRepasses;
	}

	public void setTblRepasses(Set tblRepasses) {
		this.tblRepasses = tblRepasses;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "tbl_participa", catalog = "pais", joinColumns = { @JoinColumn(name = "disCod", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "EncCod", nullable = false, updatable = false) })
	public Set getTblEncontroses() {
		return this.tblEncontroses;
	}

	public void setTblEncontroses(Set tblEncontroses) {
		this.tblEncontroses = tblEncontroses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblDiscipulos")
	public Set getTblDiscipuloses() {
		return this.tblDiscipuloses;
	}

	public void setTblDiscipuloses(Set tblDiscipuloses) {
		this.tblDiscipuloses = tblDiscipuloses;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "tbl_foracademicadiscipulos", catalog = "pais", joinColumns = { @JoinColumn(name = "disCod", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "ForCod", nullable = false, updatable = false) })
	public Set getTblFormacaoacademicas() {
		return this.tblFormacaoacademicas;
	}

	public void setTblFormacaoacademicas(Set tblFormacaoacademicas) {
		this.tblFormacaoacademicas = tblFormacaoacademicas;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "tbl_foreclesiasticasdiscipulos", catalog = "pais", joinColumns = { @JoinColumn(name = "disCod", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "forCod", nullable = false, updatable = false) })
	public Set getTblFormacaoeclesiasticases() {
		return this.tblFormacaoeclesiasticases;
	}

	public void setTblFormacaoeclesiasticases(Set tblFormacaoeclesiasticases) {
		this.tblFormacaoeclesiasticases = tblFormacaoeclesiasticases;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "tblDiscipuloses")
	public Set getTblFuncaoeclesiasticases() {
		return this.tblFuncaoeclesiasticases;
	}

	public void setTblFuncaoeclesiasticases(Set tblFuncaoeclesiasticases) {
		this.tblFuncaoeclesiasticases = tblFuncaoeclesiasticases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblDiscipulos")
	public Set getTblDocumentoses() {
		return this.tblDocumentoses;
	}

	public void setTblDocumentoses(Set tblDocumentoses) {
		this.tblDocumentoses = tblDocumentoses;
	}

}
