package br.com.pais.beans;

// Generated 26/04/2010 13:44:43 by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Documentos generated by hbm2java
 */
@Entity
@Table(name = "tbl_documentos", catalog = "pais", uniqueConstraints = {
		@UniqueConstraint(columnNames = "docTituloEleitor"),
		@UniqueConstraint(columnNames = "docCPF"),
		@UniqueConstraint(columnNames = "docRG") })
public class Documentos implements java.io.Serializable {

	private Integer docCod;
	private Discipulos tblDiscipulos;
	private String docRg;
	private String docRgemissor;
	private String docTituloEleitor;
	private Integer docSecao;
	private Integer docZona;
	private String docCpf;

	public Documentos() {
	}

	public Documentos(Discipulos tblDiscipulos) {
		this.tblDiscipulos = tblDiscipulos;
	}

	public Documentos(Discipulos tblDiscipulos, String docRg,
			String docRgemissor, String docTituloEleitor, Integer docSecao,
			Integer docZona, String docCpf) {
		this.tblDiscipulos = tblDiscipulos;
		this.docRg = docRg;
		this.docRgemissor = docRgemissor;
		this.docTituloEleitor = docTituloEleitor;
		this.docSecao = docSecao;
		this.docZona = docZona;
		this.docCpf = docCpf;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "docCod", unique = true, nullable = false)
	public Integer getDocCod() {
		return this.docCod;
	}

	public void setDocCod(Integer docCod) {
		this.docCod = docCod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tbl_Discipulos_disCod", nullable = false)
	public Discipulos getTblDiscipulos() {
		return this.tblDiscipulos;
	}

	public void setTblDiscipulos(Discipulos tblDiscipulos) {
		this.tblDiscipulos = tblDiscipulos;
	}

	@Column(name = "docRG", unique = true, length = 10)
	public String getDocRg() {
		return this.docRg;
	}

	public void setDocRg(String docRg) {
		this.docRg = docRg;
	}

	@Column(name = "docRGEmissor", length = 5)
	public String getDocRgemissor() {
		return this.docRgemissor;
	}

	public void setDocRgemissor(String docRgemissor) {
		this.docRgemissor = docRgemissor;
	}

	@Column(name = "docTituloEleitor", unique = true, length = 10)
	public String getDocTituloEleitor() {
		return this.docTituloEleitor;
	}

	public void setDocTituloEleitor(String docTituloEleitor) {
		this.docTituloEleitor = docTituloEleitor;
	}

	@Column(name = "docSecao")
	public Integer getDocSecao() {
		return this.docSecao;
	}

	public void setDocSecao(Integer docSecao) {
		this.docSecao = docSecao;
	}

	@Column(name = "docZona")
	public Integer getDocZona() {
		return this.docZona;
	}

	public void setDocZona(Integer docZona) {
		this.docZona = docZona;
	}

	@Column(name = "docCPF", unique = true, length = 11)
	public String getDocCpf() {
		return this.docCpf;
	}

	public void setDocCpf(String docCpf) {
		this.docCpf = docCpf;
	}

}
