package br.com.pais.beans;

// Generated 26/04/2010 13:44:43 by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Formacaoacademica generated by hbm2java
 */
@Entity
@Table(name = "tbl_formacaoacademica", catalog = "pais", uniqueConstraints = @UniqueConstraint(columnNames = "ForDescricao"))
public class Formacaoacademica implements java.io.Serializable {

	private Integer forCod;
	private String forDescricao;
	private Set tblDiscipuloses = new HashSet(0);

	public Formacaoacademica() {
	}

	public Formacaoacademica(String forDescricao) {
		this.forDescricao = forDescricao;
	}

	public Formacaoacademica(String forDescricao, Set tblDiscipuloses) {
		this.forDescricao = forDescricao;
		this.tblDiscipuloses = tblDiscipuloses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ForCod", unique = true, nullable = false)
	public Integer getForCod() {
		return this.forCod;
	}

	public void setForCod(Integer forCod) {
		this.forCod = forCod;
	}

	@Column(name = "ForDescricao", unique = true, nullable = false, length = 60)
	public String getForDescricao() {
		return this.forDescricao;
	}

	public void setForDescricao(String forDescricao) {
		this.forDescricao = forDescricao;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "tblFormacaoacademicas")
	public Set getTblDiscipuloses() {
		return this.tblDiscipuloses;
	}

	public void setTblDiscipuloses(Set tblDiscipuloses) {
		this.tblDiscipuloses = tblDiscipuloses;
	}

}
