package br.com.pais.beans;

// Generated 26/04/2010 13:44:43 by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Funcaoeclesiasticas generated by hbm2java
 */
@Entity
@Table(name = "tbl_funcaoeclesiasticas", catalog = "pais", uniqueConstraints = @UniqueConstraint(columnNames = "funDescricao"))
public class Funcaoeclesiasticas implements java.io.Serializable {

	private int funCod;
	private String funDescricao;
	private Set tblDiscipuloses = new HashSet(0);

	public Funcaoeclesiasticas() {
	}

	public Funcaoeclesiasticas(int funCod) {
		this.funCod = funCod;
	}

	public Funcaoeclesiasticas(int funCod, String funDescricao,
			Set tblDiscipuloses) {
		this.funCod = funCod;
		this.funDescricao = funDescricao;
		this.tblDiscipuloses = tblDiscipuloses;
	}

	@Id
	@Column(name = "funCod", unique = true, nullable = false)
	public int getFunCod() {
		return this.funCod;
	}

	public void setFunCod(int funCod) {
		this.funCod = funCod;
	}

	@Column(name = "funDescricao", unique = true, length = 60)
	public String getFunDescricao() {
		return this.funDescricao;
	}

	public void setFunDescricao(String funDescricao) {
		this.funDescricao = funDescricao;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "tbl_funeclesiasticasdiscipulos", catalog = "pais", joinColumns = { @JoinColumn(name = "funCod", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "disCod", nullable = false, updatable = false) })
	public Set getTblDiscipuloses() {
		return this.tblDiscipuloses;
	}

	public void setTblDiscipuloses(Set tblDiscipuloses) {
		this.tblDiscipuloses = tblDiscipuloses;
	}

}
