package br.com.pais.beans;

// Generated 26/04/2010 13:44:43 by Hibernate Tools 3.3.0.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Telcelulas generated by hbm2java
 */
@Entity
@Table(name = "tbl_telcelulas", catalog = "pais")
public class Telcelulas implements java.io.Serializable {

	private TelcelulasId id;
	private String telTipo;

	public Telcelulas() {
	}

	public Telcelulas(TelcelulasId id, String telTipo) {
		this.id = id;
		this.telTipo = telTipo;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "celCod", column = @Column(name = "celCod", nullable = false)),
			@AttributeOverride(name = "telNumero", column = @Column(name = "telNumero", nullable = false)) })
	public TelcelulasId getId() {
		return this.id;
	}

	public void setId(TelcelulasId id) {
		this.id = id;
	}

	@Column(name = "telTipo", nullable = false, length = 30)
	public String getTelTipo() {
		return this.telTipo;
	}

	public void setTelTipo(String telTipo) {
		this.telTipo = telTipo;
	}

}
