package br.com.pais.entities;

// Generated 06/06/2011 00:07:14 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Discipulosbatismo generated by hbm2java
 */
@Entity
@Table(name = "discipulosbatismo", catalog = "wwwpais_sistema")
public class Discipulosbatismo implements java.io.Serializable {

	private DiscipulosbatismoId id;
	private Batismo batismo;
	private Discipulos discipulos;
	private char batizando;

	public Discipulosbatismo() {
	}

	public Discipulosbatismo(DiscipulosbatismoId id, Batismo batismo,
			Discipulos discipulos, char batizando) {
		this.id = id;
		this.batismo = batismo;
		this.discipulos = discipulos;
		this.batizando = batizando;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "batismo", column = @Column(name = "batismo", nullable = false)),
			@AttributeOverride(name = "discipulo", column = @Column(name = "discipulo", nullable = false)) })
	public DiscipulosbatismoId getId() {
		return this.id;
	}

	public void setId(DiscipulosbatismoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "batismo", nullable = false, insertable = false, updatable = false)
	public Batismo getBatismo() {
		return this.batismo;
	}

	public void setBatismo(Batismo batismo) {
		this.batismo = batismo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "discipulo", nullable = false, insertable = false, updatable = false)
	public Discipulos getDiscipulos() {
		return this.discipulos;
	}

	public void setDiscipulos(Discipulos discipulos) {
		this.discipulos = discipulos;
	}

	@Column(name = "batizando", nullable = false, length = 1)
	public char getBatizando() {
		return this.batizando;
	}

	public void setBatizando(char batizando) {
		this.batizando = batizando;
	}

}
