package br.com.pais.entities;

// Generated 26/05/2011 16:14:20 by Hibernate Tools 3.4.0.Beta1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Encontrofinanceiro generated by hbm2java
 */
@Entity
@Table(name = "encontrofinanceiro", catalog = "wwwpais_sistema")
public class Encontrofinanceiro implements java.io.Serializable {

	private Integer encFinanCod;
	private Dadosencontros dadosencontros;
	private Encontrostipomovimento encontrostipomovimento;
	private BigDecimal valorMovimento;

	public Encontrofinanceiro() {
	}

	public Encontrofinanceiro(Dadosencontros dadosencontros,
			Encontrostipomovimento encontrostipomovimento,
			BigDecimal valorMovimento) {
		this.dadosencontros = dadosencontros;
		this.encontrostipomovimento = encontrostipomovimento;
		this.valorMovimento = valorMovimento;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "EncFinanCod", unique = true, nullable = false)
	public Integer getEncFinanCod() {
		return this.encFinanCod;
	}

	public void setEncFinanCod(Integer encFinanCod) {
		this.encFinanCod = encFinanCod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dadosencontrosCod", nullable = false)
	public Dadosencontros getDadosencontros() {
		return this.dadosencontros;
	}

	public void setDadosencontros(Dadosencontros dadosencontros) {
		this.dadosencontros = dadosencontros;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tipomovimentoCod", nullable = false)
	public Encontrostipomovimento getEncontrostipomovimento() {
		return this.encontrostipomovimento;
	}

	public void setEncontrostipomovimento(
			Encontrostipomovimento encontrostipomovimento) {
		this.encontrostipomovimento = encontrostipomovimento;
	}

	@Column(name = "valorMovimento", nullable = false, precision = 10)
	public BigDecimal getValorMovimento() {
		return this.valorMovimento;
	}

	public void setValorMovimento(BigDecimal valorMovimento) {
		this.valorMovimento = valorMovimento;
	}

}
