package br.com.pais.entities;

// Generated 11/05/2011 14:16:49 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Escolalideresindicador generated by hbm2java
 */
@Entity
@Table(name = "escolalideresindicador", catalog = "wwwpais_sistema")
public class Escolalideresindicador implements java.io.Serializable {

	private Integer elIndicCod;
	private String elIndicNome;
	private Set<Escolaliderestiposmovimento> escolaliderestiposmovimentos = new HashSet<Escolaliderestiposmovimento>(
			0);

	public Escolalideresindicador() {
	}

	public Escolalideresindicador(String elIndicNome,
			Set<Escolaliderestiposmovimento> escolaliderestiposmovimentos) {
		this.elIndicNome = elIndicNome;
		this.escolaliderestiposmovimentos = escolaliderestiposmovimentos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "elIndicCod", unique = true, nullable = false)
	public Integer getElIndicCod() {
		return this.elIndicCod;
	}

	public void setElIndicCod(Integer elIndicCod) {
		this.elIndicCod = elIndicCod;
	}

	@Column(name = "elIndicNome", length = 80)
	public String getElIndicNome() {
		return this.elIndicNome;
	}

	public void setElIndicNome(String elIndicNome) {
		this.elIndicNome = elIndicNome;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "escolalideresindicador")
	public Set<Escolaliderestiposmovimento> getEscolaliderestiposmovimentos() {
		return this.escolaliderestiposmovimentos;
	}

	public void setEscolaliderestiposmovimentos(
			Set<Escolaliderestiposmovimento> escolaliderestiposmovimentos) {
		this.escolaliderestiposmovimentos = escolaliderestiposmovimentos;
	}

}
