package br.com.pais.entities;

// Generated 11/05/2011 14:16:49 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Escolalideresfinanceiro generated by hbm2java
 */
@Entity
@Table(name = "escolalideresfinanceiro", catalog = "wwwpais_sistema")
public class Escolalideresfinanceiro implements java.io.Serializable {

	private Integer elFinanCod;
	private Escolaliderestiposmovimento escolaliderestiposmovimento;
	private Escolalideres escolalideres;
	private BigDecimal elFinanValor;
	private Date elFinanData;
	private Set<Escolalideresfinanceiroalunos> escolalideresfinanceiroalunoses = new HashSet<Escolalideresfinanceiroalunos>(
			0);

	public Escolalideresfinanceiro() {
	}

	public Escolalideresfinanceiro(
			Escolaliderestiposmovimento escolaliderestiposmovimento,
			Escolalideres escolalideres) {
		this.escolaliderestiposmovimento = escolaliderestiposmovimento;
		this.escolalideres = escolalideres;
	}

	public Escolalideresfinanceiro(
			Escolaliderestiposmovimento escolaliderestiposmovimento,
			Escolalideres escolalideres, BigDecimal elFinanValor,
			Date elFinanData,
			Set<Escolalideresfinanceiroalunos> escolalideresfinanceiroalunoses) {
		this.escolaliderestiposmovimento = escolaliderestiposmovimento;
		this.escolalideres = escolalideres;
		this.elFinanValor = elFinanValor;
		this.elFinanData = elFinanData;
		this.escolalideresfinanceiroalunoses = escolalideresfinanceiroalunoses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "elFinanCod", unique = true, nullable = false)
	public Integer getElFinanCod() {
		return this.elFinanCod;
	}

	public void setElFinanCod(Integer elFinanCod) {
		this.elFinanCod = elFinanCod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "elTipoMovCod", nullable = false)
	public Escolaliderestiposmovimento getEscolaliderestiposmovimento() {
		return this.escolaliderestiposmovimento;
	}

	public void setEscolaliderestiposmovimento(
			Escolaliderestiposmovimento escolaliderestiposmovimento) {
		this.escolaliderestiposmovimento = escolaliderestiposmovimento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "elCod", nullable = false)
	public Escolalideres getEscolalideres() {
		return this.escolalideres;
	}

	public void setEscolalideres(Escolalideres escolalideres) {
		this.escolalideres = escolalideres;
	}

	@Column(name = "elFinanValor", precision = 10)
	public BigDecimal getElFinanValor() {
		return this.elFinanValor;
	}

	public void setElFinanValor(BigDecimal elFinanValor) {
		this.elFinanValor = elFinanValor;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "elFinanData", length = 10)
	public Date getElFinanData() {
		return this.elFinanData;
	}

	public void setElFinanData(Date elFinanData) {
		this.elFinanData = elFinanData;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "escolalideresfinanceiro")
	public Set<Escolalideresfinanceiroalunos> getEscolalideresfinanceiroalunoses() {
		return this.escolalideresfinanceiroalunoses;
	}

	public void setEscolalideresfinanceiroalunoses(
			Set<Escolalideresfinanceiroalunos> escolalideresfinanceiroalunoses) {
		this.escolalideresfinanceiroalunoses = escolalideresfinanceiroalunoses;
	}

}
