package br.com.pais.entities;

// Generated 11/05/2011 14:16:49 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Escolalideresfrequencia generated by hbm2java
 */
@Entity
@Table(name = "escolalideresfrequencia", catalog = "wwwpais_sistema")
public class Escolalideresfrequencia implements java.io.Serializable {

	private Integer elFreqCod;
	private Escolaliderescronogramaaulas escolaliderescronogramaaulas;
	private Escolalideresdiscipulos escolalideresdiscipulos;
	private char presenca;

	public Escolalideresfrequencia() {
	}

	public Escolalideresfrequencia(
			Escolaliderescronogramaaulas escolaliderescronogramaaulas,
			Escolalideresdiscipulos escolalideresdiscipulos, char presenca) {
		this.escolaliderescronogramaaulas = escolaliderescronogramaaulas;
		this.escolalideresdiscipulos = escolalideresdiscipulos;
		this.presenca = presenca;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "elFreqCod", unique = true, nullable = false)
	public Integer getElFreqCod() {
		return this.elFreqCod;
	}

	public void setElFreqCod(Integer elFreqCod) {
		this.elFreqCod = elFreqCod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cronoAulaCod", nullable = false)
	public Escolaliderescronogramaaulas getEscolaliderescronogramaaulas() {
		return this.escolaliderescronogramaaulas;
	}

	public void setEscolaliderescronogramaaulas(
			Escolaliderescronogramaaulas escolaliderescronogramaaulas) {
		this.escolaliderescronogramaaulas = escolaliderescronogramaaulas;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "discipuloCod", nullable = false)
	public Escolalideresdiscipulos getEscolalideresdiscipulos() {
		return this.escolalideresdiscipulos;
	}

	public void setEscolalideresdiscipulos(
			Escolalideresdiscipulos escolalideresdiscipulos) {
		this.escolalideresdiscipulos = escolalideresdiscipulos;
	}

	@Column(name = "presenca", nullable = false, length = 1)
	public char getPresenca() {
		return this.presenca;
	}

	public void setPresenca(char presenca) {
		this.presenca = presenca;
	}

}
