package br.com.pais.entities;

// Generated 11/05/2011 14:16:49 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Escolalideresfechamentomodulo generated by hbm2java
 */
@Entity
@Table(name = "escolalideresfechamentomodulo", catalog = "wwwpais_sistema")
public class Escolalideresfechamentomodulo implements java.io.Serializable {

	private Integer fechaModCod;
	private Escolalideres escolalideres;
	private Escolalideresmodulo escolalideresmodulo;
	private Integer aulasPrevistas;
	private Integer aulasDadas;
	private Date dataEncerradas;

	public Escolalideresfechamentomodulo() {
	}

	public Escolalideresfechamentomodulo(Escolalideres escolalideres,
			Escolalideresmodulo escolalideresmodulo) {
		this.escolalideres = escolalideres;
		this.escolalideresmodulo = escolalideresmodulo;
	}

	public Escolalideresfechamentomodulo(Escolalideres escolalideres,
			Escolalideresmodulo escolalideresmodulo, Integer aulasPrevistas,
			Integer aulasDadas, Date dataEncerradas) {
		this.escolalideres = escolalideres;
		this.escolalideresmodulo = escolalideresmodulo;
		this.aulasPrevistas = aulasPrevistas;
		this.aulasDadas = aulasDadas;
		this.dataEncerradas = dataEncerradas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "fechaModCod", unique = true, nullable = false)
	public Integer getFechaModCod() {
		return this.fechaModCod;
	}

	public void setFechaModCod(Integer fechaModCod) {
		this.fechaModCod = fechaModCod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "elCod", nullable = false)
	public Escolalideres getEscolalideres() {
		return this.escolalideres;
	}

	public void setEscolalideres(Escolalideres escolalideres) {
		this.escolalideres = escolalideres;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "modCod", nullable = false)
	public Escolalideresmodulo getEscolalideresmodulo() {
		return this.escolalideresmodulo;
	}

	public void setEscolalideresmodulo(Escolalideresmodulo escolalideresmodulo) {
		this.escolalideresmodulo = escolalideresmodulo;
	}

	@Column(name = "aulasPrevistas")
	public Integer getAulasPrevistas() {
		return this.aulasPrevistas;
	}

	public void setAulasPrevistas(Integer aulasPrevistas) {
		this.aulasPrevistas = aulasPrevistas;
	}

	@Column(name = "aulasDadas")
	public Integer getAulasDadas() {
		return this.aulasDadas;
	}

	public void setAulasDadas(Integer aulasDadas) {
		this.aulasDadas = aulasDadas;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dataEncerradas", length = 10)
	public Date getDataEncerradas() {
		return this.dataEncerradas;
	}

	public void setDataEncerradas(Date dataEncerradas) {
		this.dataEncerradas = dataEncerradas;
	}

}
