package br.com.pais.entities;

// Generated 06/05/2011 15:49:37 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Financeiroigrejas generated by hbm2java
 */
@Entity
@Table(name = "financeiroigrejas")
public class Financeiroigrejas implements java.io.Serializable {

	private FinanceiroigrejasId id;
	private Pacotes pacotes;
	private Date datapagto;
	private Integer tipopagto;
	private BigDecimal valorpago;

	public Financeiroigrejas() {
	}

	public Financeiroigrejas(FinanceiroigrejasId id, Pacotes pacotes) {
		this.id = id;
		this.pacotes = pacotes;
	}

	public Financeiroigrejas(FinanceiroigrejasId id, Pacotes pacotes,
			Date datapagto, Integer tipopagto, BigDecimal valorpago) {
		this.id = id;
		this.pacotes = pacotes;
		this.datapagto = datapagto;
		this.tipopagto = tipopagto;
		this.valorpago = valorpago;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "igrejasIgrcod", column = @Column(name = "igrejas_igrcod", nullable = false)),
			@AttributeOverride(name = "pacotesIdpacotes", column = @Column(name = "pacotes_idpacotes", nullable = false)) })
	public FinanceiroigrejasId getId() {
		return this.id;
	}

	public void setId(FinanceiroigrejasId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pacotes_idpacotes", nullable = false, insertable = false, updatable = false)
	public Pacotes getPacotes() {
		return this.pacotes;
	}

	public void setPacotes(Pacotes pacotes) {
		this.pacotes = pacotes;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datapagto", length = 19)
	public Date getDatapagto() {
		return this.datapagto;
	}

	public void setDatapagto(Date datapagto) {
		this.datapagto = datapagto;
	}

	@Column(name = "tipopagto")
	public Integer getTipopagto() {
		return this.tipopagto;
	}

	public void setTipopagto(Integer tipopagto) {
		this.tipopagto = tipopagto;
	}

	@Column(name = "valorpago", precision = 10)
	public BigDecimal getValorpago() {
		return this.valorpago;
	}

	public void setValorpago(BigDecimal valorpago) {
		this.valorpago = valorpago;
	}

}
