package br.com.pais.entities;

// Generated 25/01/2011 16:14:58 by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Logradouro generated by hbm2java
 */
@Entity
@Table(name = "logradouro")
public class Logradouro implements java.io.Serializable {

	private int logNumSequencial;
	private Bairro bairro;
	private String ufeSg;
	private int locNuSequencial;
	private String logNo;
	private String logNome;
	private String logComplemento;
	private String logTipoLogradouro;
	private String cep;
	private Set<Celulas> celulases = new HashSet<Celulas>(0);
	private Set<Bases> baseses = new HashSet<Bases>(0);
	private Set<Discipulos> discipuloses = new HashSet<Discipulos>(0);

	public Logradouro() {
	}

	public Logradouro(int logNumSequencial, Bairro bairro, String ufeSg,
			int locNuSequencial, String logNo, String logNome,
			String logTipoLogradouro, String cep) {
		this.logNumSequencial = logNumSequencial;
		this.bairro = bairro;
		this.ufeSg = ufeSg;
		this.locNuSequencial = locNuSequencial;
		this.logNo = logNo;
		this.logNome = logNome;
		this.logTipoLogradouro = logTipoLogradouro;
		this.cep = cep;
	}

	public Logradouro(int logNumSequencial, Bairro bairro, String ufeSg,
			int locNuSequencial, String logNo, String logNome,
			String logComplemento, String logTipoLogradouro, String cep,
			Set<Celulas> celulases, Set<Bases> baseses,
			Set<Discipulos> discipuloses) {
		this.logNumSequencial = logNumSequencial;
		this.bairro = bairro;
		this.ufeSg = ufeSg;
		this.locNuSequencial = locNuSequencial;
		this.logNo = logNo;
		this.logNome = logNome;
		this.logComplemento = logComplemento;
		this.logTipoLogradouro = logTipoLogradouro;
		this.cep = cep;
		this.celulases = celulases;
		this.baseses = baseses;
		this.discipuloses = discipuloses;
	}

	@Id
	@Column(name = "LOG_NUM_SEQUENCIAL", unique = true, nullable = false)
	public int getLogNumSequencial() {
		return this.logNumSequencial;
	}

	public void setLogNumSequencial(int logNumSequencial) {
		this.logNumSequencial = logNumSequencial;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BAI_NU_SEQUENCIAL_INI", nullable = false)
	public Bairro getBairro() {
		return this.bairro;
	}

	public void setBairro(Bairro bairro) {
		this.bairro = bairro;
	}

	@Column(name = "UFE_SG", nullable = false, length = 2)
	public String getUfeSg() {
		return this.ufeSg;
	}

	public void setUfeSg(String ufeSg) {
		this.ufeSg = ufeSg;
	}

	@Column(name = "LOC_NU_SEQUENCIAL", nullable = false)
	public int getLocNuSequencial() {
		return this.locNuSequencial;
	}

	public void setLocNuSequencial(int locNuSequencial) {
		this.locNuSequencial = locNuSequencial;
	}

	@Column(name = "LOG_No", nullable = false, length = 70)
	public String getLogNo() {
		return this.logNo;
	}

	public void setLogNo(String logNo) {
		this.logNo = logNo;
	}

	@Column(name = "LOG_Nome", nullable = false, length = 125)
	public String getLogNome() {
		return this.logNome;
	}

	public void setLogNome(String logNome) {
		this.logNome = logNome;
	}

	@Column(name = "LOG_Complemento", length = 100)
	public String getLogComplemento() {
		return this.logComplemento;
	}

	public void setLogComplemento(String logComplemento) {
		this.logComplemento = logComplemento;
	}

	@Column(name = "LOG_Tipo_Logradouro", nullable = false, length = 72)
	public String getLogTipoLogradouro() {
		return this.logTipoLogradouro;
	}

	public void setLogTipoLogradouro(String logTipoLogradouro) {
		this.logTipoLogradouro = logTipoLogradouro;
	}

	@Column(name = "CEP", nullable = false, length = 8)
	public String getCep() {
		return this.cep;
	}

	public void setCep(String cep) {
		this.cep = cep;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "logradouro")
	public Set<Celulas> getCelulases() {
		return this.celulases;
	}

	public void setCelulases(Set<Celulas> celulases) {
		this.celulases = celulases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "logradouro")
	public Set<Bases> getBaseses() {
		return this.baseses;
	}

	public void setBaseses(Set<Bases> baseses) {
		this.baseses = baseses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "logradouro")
	public Set<Discipulos> getDiscipuloses() {
		return this.discipuloses;
	}

	public void setDiscipuloses(Set<Discipulos> discipuloses) {
		this.discipuloses = discipuloses;
	}

}
