package br.com.pais.entities;

// Generated 25/01/2011 16:14:58 by Hibernate Tools 3.4.0.Beta1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Movimento generated by hbm2java
 */
@Entity
@Table(name = "movimento", catalog = "wwwpais_sistema")
public class Movimento implements java.io.Serializable {

	private Integer movCod;
	private Celulas celulas;
	private Bases bases;
	private Date movData;
	private Date movDataCadastro;
	private Date movHoraCadastro;
	private Date movDataBaixa;
	private Date movHoraBaixa;
	private String movTipo;
	private String movEspecie;
	private Double movValor;
	private String movRecebido;
	private String movVisualizado;
	private String movProtocolo;
	private String movProtocoloPai;
	private List<Repasse> repasses = new ArrayList<Repasse>();
	private List<Movimentocheque> movimentocheques = new ArrayList<Movimentocheque>();

	public Movimento() {
	}

	public Movimento(Celulas celulas, Bases bases, Date movData, 
			Date movDataCadastro, Date movHoraCadastro,
			Date movDataBaixa, Date movHoraBaixa,
			String movTipo, String movEspecie, Double movValor,
			String movRecebido, String movVisualizado, String movProtocolo, String movProtocoloPai,
			List<Repasse> repasses, List<Movimentocheque> movimentocheques) {
		this.celulas = celulas;
		this.bases = bases;
		this.movData = movData;
		this.movDataCadastro = movDataCadastro;
		this.movHoraCadastro = movHoraCadastro;
		this.movDataBaixa = movData;
		this.movHoraBaixa = movHoraCadastro;
		this.movTipo = movTipo;
		this.movEspecie = movEspecie;
		this.movValor = movValor;
		this.movRecebido = movRecebido;
		this.movVisualizado = movVisualizado;
		this.movProtocolo = movProtocolo;
		this.movProtocoloPai = movProtocoloPai;
		this.repasses = repasses;
		this.movimentocheques = movimentocheques;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "movCod", unique = true, nullable = false)
	public Integer getMovCod() {
		return this.movCod;
	}

	public void setMovCod(Integer movCod) {
		this.movCod = movCod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "celCod")
	public Celulas getCelulas() {
		return this.celulas;
	}

	public void setCelulas(Celulas celulas) {
		this.celulas = celulas;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "basCod")
	public Bases getBases() {
		return this.bases;
	}

	public void setBases(Bases bases) {
		this.bases = bases;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "movData", length = 10)
	public Date getMovData() {
		return this.movData;
	}

	public void setMovData(Date movData) {
		this.movData = movData;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "movDataCadastro", length = 10)
	public Date getMovDataCadastro() {
		return movDataCadastro;
	}

	public void setMovDataCadastro(Date movDataCadastro) {
		this.movDataCadastro = movDataCadastro;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "movHoraCadastro", length = 8)
	public Date getMovHoraCadastro() {
		return movHoraCadastro;
	}

	public void setMovHoraCadastro(Date movHoraCadastro) {
		this.movHoraCadastro = movHoraCadastro;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name = "movDataBaixa", length = 10)
	public Date getMovDataBaixa() {
		return movDataBaixa;
	}

	public void setMovDataBaixa(Date movDataBaixa) {
		this.movDataBaixa = movDataBaixa;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "movHoraBaixa", length = 8)
	public Date getMovHoraBaixa() {
		return movHoraBaixa;
	}

	public void setMovHoraBaixa(Date movHoraBaixa) {
		this.movHoraBaixa = movHoraBaixa;
	}

	@Column(name = "movTipo", length = 60)
	public String getMovTipo() {
		return this.movTipo;
	}

	public void setMovTipo(String movTipo) {
		this.movTipo = movTipo;
	}

	@Column(name = "movEspecie", length = 60)
	public String getMovEspecie() {
		return this.movEspecie;
	}

	public void setMovEspecie(String movEspecie) {
		this.movEspecie = movEspecie;
	}

	@Column(name = "movValor", precision = 22, scale = 0)
	public Double getMovValor() {
		return this.movValor;
	}

	public void setMovValor(Double movValor) {
		this.movValor = movValor;
	}

	@Column(name = "movRecebido", length = 1)
	public String getMovRecebido() {
		return this.movRecebido;
	}

	public void setMovRecebido(String movRecebido) {
		this.movRecebido = movRecebido;
	}
	
	@Column(name = "movVisualizado", length = 1)
	public String getMovVisualizado() {
		return this.movVisualizado;
	}

	public void setMovVisualizado(String movVisualizado) {
		this.movVisualizado = movVisualizado;
	}

	@Column(name = "movProtocolo")
	public String getMovProtocolo() {
		return this.movProtocolo;
	}

	public void setMovProtocolo(String movProtocolo) {
		this.movProtocolo = movProtocolo;
	}

	@Column(name = "movProtocoloPai")
	public String getMovProtocoloPai() {
		return this.movProtocoloPai;
	}

	public void setMovProtocoloPai(String movProtocoloPai) {
		this.movProtocoloPai = movProtocoloPai;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "movimento")
	public List<Repasse> getRepasses() {
		return this.repasses;
	}

	public void setRepasses(List<Repasse> repasses) {
		this.repasses = repasses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "movimento")
	public List<Movimentocheque> getMovimentocheques() {
		return this.movimentocheques;
	}

	public void setMovimentocheques(List<Movimentocheque> movimentocheques) {
		this.movimentocheques = movimentocheques;
	}
}
