package br.com.pais.entities;

// Generated 10/02/2011 15:30:39 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Movimentocheque generated by hbm2java
 */
@Entity
@Table(name = "movimentocheque")
public class Movimentocheque implements java.io.Serializable {

	private MovimentochequeId id;
	private Movimento movimento;
	private Bancos bancos;

	public Movimentocheque() {
	}

	public Movimentocheque(MovimentochequeId id, Movimento movimento,
			Bancos bancos) {
		this.id = id;
		this.movimento = movimento;
		this.bancos = bancos;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codMovimento", column = @Column(name = "CodMovimento", nullable = false)),
			@AttributeOverride(name = "codBanco", column = @Column(name = "CodBanco", nullable = false)),
			@AttributeOverride(name = "preDatado", column = @Column(name = "PreDatado", length = 1)),
			@AttributeOverride(name = "comp", column = @Column(name = "Comp", length = 10)),
			@AttributeOverride(name = "banco", column = @Column(name = "Banco", length = 10)),
			@AttributeOverride(name = "agencia", column = @Column(name = "Agencia", length = 10)),
			@AttributeOverride(name = "campoC1", column = @Column(name = "campoC1", length = 1)),
			@AttributeOverride(name = "conta", column = @Column(name = "Conta", length = 20)),
			@AttributeOverride(name = "campoC2", column = @Column(name = "campoC2", length = 1)),
			@AttributeOverride(name = "numCheque", column = @Column(name = "NumCheque", length = 20)),
			@AttributeOverride(name = "campoC3", column = @Column(name = "campoC3", length = 1)),
			@AttributeOverride(name = "valNum", column = @Column(name = "ValNum", precision = 10)),
			@AttributeOverride(name = "valExtenso", column = @Column(name = "ValExtenso", length = 150)),
			@AttributeOverride(name = "pagoPara", column = @Column(name = "PagoPara", length = 100)),
			@AttributeOverride(name = "dataCheque", column = @Column(name = "DataCheque", length = 10)),
			@AttributeOverride(name = "dataCidade", column = @Column(name = "DataCidade", length = 100)),
			@AttributeOverride(name = "dataDia", column = @Column(name = "DataDia", length = 10)),
			@AttributeOverride(name = "dataMes", column = @Column(name = "DataMes", length = 60)),
			@AttributeOverride(name = "dataAno", column = @Column(name = "DataAno", length = 4)),
			@AttributeOverride(name = "nomPagante", column = @Column(name = "NomPagante", length = 100)),
			@AttributeOverride(name = "cpfPagante", column = @Column(name = "CpfPagante", length = 14)),
			@AttributeOverride(name = "clienteDesdeMes", column = @Column(name = "ClienteDesdeMes", length = 2)),
			@AttributeOverride(name = "clienteDesdeAno", column = @Column(name = "ClienteDesdeAno", length = 4)),
			@AttributeOverride(name = "numAutenticacao", column = @Column(name = "numAutenticacao", length = 150))})
	public MovimentochequeId getId() {
		return this.id;
	}

	public void setId(MovimentochequeId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodMovimento", nullable = false, insertable = false, updatable = false)
	public Movimento getMovimento() {
		return this.movimento;
	}

	public void setMovimento(Movimento movimento) {
		this.movimento = movimento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodBanco", nullable = false, insertable = false, updatable = false)
	public Bancos getBancos() {
		return this.bancos;
	}

	public void setBancos(Bancos bancos) {
		this.bancos = bancos;
	}

}
