package br.com.pais.entities;

// Generated 06/05/2011 15:49:37 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Paises generated by hbm2java
 */
@Entity
@Table(name = "paises")
public class Paises implements java.io.Serializable {

	private int paiscod;
	private String paisdescricao;

	public Paises() {
	}

	public Paises(int paiscod) {
		this.paiscod = paiscod;
	}

	public Paises(int paiscod, String paisdescricao) {
		this.paiscod = paiscod;
		this.paisdescricao = paisdescricao;
	}

	@Id
	@Column(name = "paiscod", unique = true, nullable = false)
	public int getPaiscod() {
		return this.paiscod;
	}

	public void setPaiscod(int paiscod) {
		this.paiscod = paiscod;
	}

	@Column(name = "paisdescricao", length = 100)
	public String getPaisdescricao() {
		return this.paisdescricao;
	}

	public void setPaisdescricao(String paisdescricao) {
		this.paisdescricao = paisdescricao;
	}

}
