package br.com.pais.entities;

// Generated 25/01/2011 16:14:58 by Hibernate Tools 3.4.0.Beta1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Repasse generated by hbm2java
 */
@Entity
@Table(name = "repasse", catalog = "wwwpais_sistema")
public class Repasse implements java.io.Serializable {

	private RepasseId id;
	private Movimento movimento;
	private Discipulos discipulos;
	private Double resValor;
	private Date resData;
	private String resLocal;

	public Repasse() {
	}

	public Repasse(RepasseId id, Movimento movimento, Discipulos discipulos,
			Double resValor, Date resData) {
		this.id = id;
		this.movimento = movimento;
		this.discipulos = discipulos;
		this.resValor = resValor;
		this.resData = resData;
	}

	public Repasse(RepasseId id, Movimento movimento, Discipulos discipulos,
			Double resValor, Date resData, String resLocal) {
		this.id = id;
		this.movimento = movimento;
		this.discipulos = discipulos;
		this.resValor = resValor;
		this.resData = resData;
		this.resLocal = resLocal;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "movCod", column = @Column(name = "movCod", nullable = false)),
			@AttributeOverride(name = "disCod", column = @Column(name = "disCod", nullable = false)) })
	public RepasseId getId() {
		return this.id;
	}

	public void setId(RepasseId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "movCod", nullable = false, insertable = false, updatable = false)
	public Movimento getMovimento() {
		return this.movimento;
	}

	public void setMovimento(Movimento movimento) {
		this.movimento = movimento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "disCod", nullable = false, insertable = false, updatable = false)
	public Discipulos getDiscipulos() {
		return this.discipulos;
	}

	public void setDiscipulos(Discipulos discipulos) {
		this.discipulos = discipulos;
	}

	@Column(name = "resValor", nullable = false, precision = 10)
	public Double getResValor() {
		return this.resValor;
	}

	public void setResValor(Double resValor) {
		this.resValor = resValor;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "resData", nullable = false, length = 10)
	public Date getResData() {
		return this.resData;
	}

	public void setResData(Date resData) {
		this.resData = resData;
	}

	@Column(name = "resLocal", length = 60)
	public String getResLocal() {
		return this.resLocal;
	}

	public void setResLocal(String resLocal) {
		this.resLocal = resLocal;
	}

}
