package br.com.pais.entities;

// Generated 13/06/2011 13:26:57 by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipousuarios generated by hbm2java
 */
@Entity
@Table(name = "tipousuarios", catalog = "wwwpais_sistema")
public class Tipousuarios implements java.io.Serializable {

	private Integer tipUsuCod;
	private String tipUsuDescricao;
	private Set<Usuarios> usuarioses = new HashSet<Usuarios>(0);

	public Tipousuarios() {
	}

	public Tipousuarios(String tipUsuDescricao) {
		this.tipUsuDescricao = tipUsuDescricao;
	}

	public Tipousuarios(String tipUsuDescricao, Set<Usuarios> usuarioses) {
		this.tipUsuDescricao = tipUsuDescricao;
		this.usuarioses = usuarioses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "tipUsuCod", unique = true, nullable = false)
	public Integer getTipUsuCod() {
		return this.tipUsuCod;
	}

	public void setTipUsuCod(Integer tipUsuCod) {
		this.tipUsuCod = tipUsuCod;
	}

	@Column(name = "tipUsuDescricao", nullable = false, length = 60)
	public String getTipUsuDescricao() {
		return this.tipUsuDescricao;
	}

	public void setTipUsuDescricao(String tipUsuDescricao) {
		this.tipUsuDescricao = tipUsuDescricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipousuarios")
	public Set<Usuarios> getUsuarioses() {
		return this.usuarioses;
	}

	public void setUsuarioses(Set<Usuarios> usuarioses) {
		this.usuarioses = usuarioses;
	}

}
