package br.com.pais.entities;

// Generated 13/06/2011 13:26:57 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name = "usuarios", catalog = "wwwpais_sistema")
public class Usuarios implements java.io.Serializable {

	private Integer idusuarios;
	private Tipousuarios tipousuarios;
	private String nome;
	private String login;
	private String email;
	private String senha;
	private String foto;

	public Usuarios() {
	}

	public Usuarios(Tipousuarios tipousuarios, String nome, String login,
			String email, String senha) {
		this.tipousuarios = tipousuarios;
		this.nome = nome;
		this.login = login;
		this.email = email;
		this.senha = senha;
	}

	public Usuarios(Tipousuarios tipousuarios, String nome, String login,
			String email, String senha, String foto) {
		this.tipousuarios = tipousuarios;
		this.nome = nome;
		this.login = login;
		this.email = email;
		this.senha = senha;
		this.foto = foto;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idusuarios", unique = true, nullable = false)
	public Integer getIdusuarios() {
		return this.idusuarios;
	}

	public void setIdusuarios(Integer idusuarios) {
		this.idusuarios = idusuarios;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tipousuarios", nullable = false)
	public Tipousuarios getTipousuarios() {
		return this.tipousuarios;
	}

	public void setTipousuarios(Tipousuarios tipousuarios) {
		this.tipousuarios = tipousuarios;
	}

	@Column(name = "nome", nullable = false, length = 100)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "login", nullable = false, length = 14)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "email", nullable = false, length = 80)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "senha", nullable = false, length = 32)
	public String getSenha() {
		return this.senha;
	}

	public void setSenha(String senha) {
		this.senha = senha;
	}

	@Column(name = "foto", length = 100)
	public String getFoto() {
		return this.foto;
	}

	public void setFoto(String foto) {
		this.foto = foto;
	}

}
