package br.com.pais.entities;

// Generated 06/05/2011 15:49:37 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Zona generated by hbm2java
 */
@Entity
@Table(name = "zona")
public class Zona implements java.io.Serializable {

	private Integer idzona;
	private String descricao;
	private Set<Celulas> celulases = new HashSet<Celulas>(0);
	private Set<Bases> baseses = new HashSet<Bases>(0);

	public Zona() {
	}

	public Zona(String descricao, Set<Celulas> celulases, Set<Bases> baseses) {
		this.descricao = descricao;
		this.celulases = celulases;
		this.baseses = baseses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idzona", unique = true, nullable = false)
	public Integer getIdzona() {
		return this.idzona;
	}

	public void setIdzona(Integer idzona) {
		this.idzona = idzona;
	}

	@Column(name = "descricao", length = 45)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "zona")
	public Set<Celulas> getCelulases() {
		return this.celulases;
	}

	public void setCelulases(Set<Celulas> celulases) {
		this.celulases = celulases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "zona")
	public Set<Bases> getBaseses() {
		return this.baseses;
	}

	public void setBaseses(Set<Bases> baseses) {
		this.baseses = baseses;
	}

}
