package br.com.pais.entities;

// Generated 06/06/2011 00:07:14 by Hibernate Tools 3.4.0.Beta1

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Batismo generated by hbm2java
 */
@Entity
@Table(name = "batismo", catalog = "wwwpais_sistema")
public class Batismo implements java.io.Serializable {

	private Integer batcod;
	private Discipulos discipulos;
	private Encontrostatus encontrostatus;
	private String batlocal;
	private Date batdatarealizacao;
	private Date bathorario;
	private List<Discipulosbatismo> discipulosbatismos = new ArrayList<Discipulosbatismo>(0);

	public Batismo() {
	}

	public Batismo(Discipulos discipulos, Encontrostatus encontrostatus,
			String batlocal, Date batdatarealizacao, Date bathorario) {
		this.discipulos = discipulos;
		this.encontrostatus = encontrostatus;
		this.batlocal = batlocal;
		this.batdatarealizacao = batdatarealizacao;
		this.bathorario = bathorario;
	}

	public Batismo(Discipulos discipulos, Encontrostatus encontrostatus,
			String batlocal, Date batdatarealizacao, Date bathorario,
			List<Discipulosbatismo> discipulosbatismos) {
		this.discipulos = discipulos;
		this.encontrostatus = encontrostatus;
		this.batlocal = batlocal;
		this.batdatarealizacao = batdatarealizacao;
		this.bathorario = bathorario;
		this.discipulosbatismos = discipulosbatismos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "batcod", unique = true, nullable = false)
	public Integer getBatcod() {
		return this.batcod;
	}

	public void setBatcod(Integer batcod) {
		this.batcod = batcod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "responsavel", nullable = false)
	public Discipulos getDiscipulos() {
		return this.discipulos;
	}

	public void setDiscipulos(Discipulos discipulos) {
		this.discipulos = discipulos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "status", nullable = false)
	public Encontrostatus getEncontrostatus() {
		return this.encontrostatus;
	}

	public void setEncontrostatus(Encontrostatus encontrostatus) {
		this.encontrostatus = encontrostatus;
	}

	@Column(name = "batlocal", nullable = false, length = 100)
	public String getBatlocal() {
		return this.batlocal;
	}

	public void setBatlocal(String batlocal) {
		this.batlocal = batlocal;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "batdatarealizacao", nullable = false, length = 10)
	public Date getBatdatarealizacao() {
		return this.batdatarealizacao;
	}

	public void setBatdatarealizacao(Date batdatarealizacao) {
		this.batdatarealizacao = batdatarealizacao;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "bathorario", nullable = false, length = 8)
	public Date getBathorario() {
		return this.bathorario;
	}

	public void setBathorario(Date bathorario) {
		this.bathorario = bathorario;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "batismo")
	public List<Discipulosbatismo> getDiscipulosbatismos() {
		return this.discipulosbatismos;
	}

	public void setDiscipulosbatismos(List<Discipulosbatismo> discipulosbatismos) {
		this.discipulosbatismos = discipulosbatismos;
	}

}
