package br.com.pais.entities;

// Generated 26/05/2011 10:55:55 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Encontrospapelaria generated by hbm2java
 */
@Entity
@Table(name = "encontrospapelaria", catalog = "wwwpais_sistema")
public class Encontrospapelaria implements java.io.Serializable {

	private Integer encpapelariaCod;
	private String encpapelariadescricao;
	private String relatorio;
	private char ativo;

	public Encontrospapelaria() {
	}

	public Encontrospapelaria(String encpapelariadescricao, char ativo) {
		this.encpapelariadescricao = encpapelariadescricao;
		this.ativo = ativo;
	}

	public Encontrospapelaria(String encpapelariadescricao, String relatorio,
			char ativo) {
		this.encpapelariadescricao = encpapelariadescricao;
		this.relatorio = relatorio;
		this.ativo = ativo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "encpapelariaCod", unique = true, nullable = false)
	public Integer getEncpapelariaCod() {
		return this.encpapelariaCod;
	}

	public void setEncpapelariaCod(Integer encpapelariaCod) {
		this.encpapelariaCod = encpapelariaCod;
	}

	@Column(name = "encpapelariadescricao", nullable = false, length = 100)
	public String getEncpapelariadescricao() {
		return this.encpapelariadescricao;
	}

	public void setEncpapelariadescricao(String encpapelariadescricao) {
		this.encpapelariadescricao = encpapelariadescricao;
	}

	@Column(name = "relatorio", length = 100)
	public String getRelatorio() {
		return this.relatorio;
	}

	public void setRelatorio(String relatorio) {
		this.relatorio = relatorio;
	}

	@Column(name = "ativo", nullable = false, length = 1)
	public char getAtivo() {
		return this.ativo;
	}

	public void setAtivo(char ativo) {
		this.ativo = ativo;
	}

}
