package br.com.pais.entities;

// Generated 24/05/2011 10:42:25 by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import br.com.pais.entities.Dadosencontros;

/**
 * Encontrostatus generated by hbm2java
 */
@Entity
@Table(name = "encontrostatus", catalog = "wwwpais_sistema")
public class Encontrostatus implements java.io.Serializable {

	private Integer encstacod;
	private String encstadescricao;
	private Set<Dadosencontros> dadosencontrosesForDadencstatus = new HashSet<Dadosencontros>(0);
	private Set<Dadosencontros> dadosencontrosesForSolicitaescolalideres = new HashSet<Dadosencontros>(0);

	public Encontrostatus() {
	}

	public Encontrostatus(String encstadescricao,
			Set<Dadosencontros> dadosencontrosesForDadencstatus,
			Set<Dadosencontros> dadosencontrosesForSolicitaescolalideres) {
		this.encstadescricao = encstadescricao;
		this.dadosencontrosesForDadencstatus = dadosencontrosesForDadencstatus;
		this.dadosencontrosesForSolicitaescolalideres = dadosencontrosesForSolicitaescolalideres;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "encstacod", unique = true, nullable = false)
	public Integer getEncstacod() {
		return this.encstacod;
	}

	public void setEncstacod(Integer encstacod) {
		this.encstacod = encstacod;
	}

	@Column(name = "encstadescricao", length = 45)
	public String getEncstadescricao() {
		return this.encstadescricao;
	}

	public void setEncstadescricao(String encstadescricao) {
		this.encstadescricao = encstadescricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "encontrostatusByDadencstatus")
	public Set<Dadosencontros> getDadosencontrosesForDadencstatus() {
		return this.dadosencontrosesForDadencstatus;
	}

	public void setDadosencontrosesForDadencstatus(
			Set<Dadosencontros> dadosencontrosesForDadencstatus) {
		this.dadosencontrosesForDadencstatus = dadosencontrosesForDadencstatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "encontrostatusBySolicitaescolalideres")
	public Set<Dadosencontros> getDadosencontrosesForSolicitaescolalideres() {
		return this.dadosencontrosesForSolicitaescolalideres;
	}

	public void setDadosencontrosesForSolicitaescolalideres(
			Set<Dadosencontros> dadosencontrosesForSolicitaescolalideres) {
		this.dadosencontrosesForSolicitaescolalideres = dadosencontrosesForSolicitaescolalideres;
	}

}