package br.com.pais.entities;

// Generated 06/05/2011 15:49:37 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Escolarequerimentos generated by hbm2java
 */
@Entity
@Table(name = "escolarequerimentos")
public class Escolarequerimentos implements java.io.Serializable {

	private Integer reqCod;
	private String reqNom;
	private BigDecimal reqValor;

	public Escolarequerimentos() {
	}

	public Escolarequerimentos(String reqNom, BigDecimal reqValor) {
		this.reqNom = reqNom;
		this.reqValor = reqValor;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "reqCod", unique = true, nullable = false)
	public Integer getReqCod() {
		return this.reqCod;
	}

	public void setReqCod(Integer reqCod) {
		this.reqCod = reqCod;
	}

	@Column(name = "reqNom", length = 60)
	public String getReqNom() {
		return this.reqNom;
	}

	public void setReqNom(String reqNom) {
		this.reqNom = reqNom;
	}

	@Column(name = "reqValor", precision = 10)
	public BigDecimal getReqValor() {
		return this.reqValor;
	}

	public void setReqValor(BigDecimal reqValor) {
		this.reqValor = reqValor;
	}

}
