package br.com.pais.entities;

// Generated 11/05/2011 14:16:49 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Escolalideresmaterias generated by hbm2java
 */
@Entity
@Table(name = "escolalideresmaterias", catalog = "wwwpais_sistema")
public class Escolalideresmaterias implements java.io.Serializable {

	private Integer matCod;
	private Escolalidereslivro escolalidereslivro;
	private Escolalideresmodulo escolalideresmodulo;
	private String matNome;
	private Set<Escolaliderescronogramaaulas> escolaliderescronogramaaulasesForAula2 = new HashSet<Escolaliderescronogramaaulas>(
			0);
	private Set<Escolaliderescronogramaaulas> escolaliderescronogramaaulasesForAula1 = new HashSet<Escolaliderescronogramaaulas>(
			0);

	public Escolalideresmaterias() {
	}

	public Escolalideresmaterias(Escolalidereslivro escolalidereslivro,
			Escolalideresmodulo escolalideresmodulo) {
		this.escolalidereslivro = escolalidereslivro;
		this.escolalideresmodulo = escolalideresmodulo;
	}

	public Escolalideresmaterias(
			Escolalidereslivro escolalidereslivro,
			Escolalideresmodulo escolalideresmodulo,
			String matNome,
			Set<Escolaliderescronogramaaulas> escolaliderescronogramaaulasesForAula2,
			Set<Escolaliderescronogramaaulas> escolaliderescronogramaaulasesForAula1) {
		this.escolalidereslivro = escolalidereslivro;
		this.escolalideresmodulo = escolalideresmodulo;
		this.matNome = matNome;
		this.escolaliderescronogramaaulasesForAula2 = escolaliderescronogramaaulasesForAula2;
		this.escolaliderescronogramaaulasesForAula1 = escolaliderescronogramaaulasesForAula1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "matCod", unique = true, nullable = false)
	public Integer getMatCod() {
		return this.matCod;
	}

	public void setMatCod(Integer matCod) {
		this.matCod = matCod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "livroCod", nullable = false)
	public Escolalidereslivro getEscolalidereslivro() {
		return this.escolalidereslivro;
	}

	public void setEscolalidereslivro(Escolalidereslivro escolalidereslivro) {
		this.escolalidereslivro = escolalidereslivro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "moduloCod", nullable = false)
	public Escolalideresmodulo getEscolalideresmodulo() {
		return this.escolalideresmodulo;
	}

	public void setEscolalideresmodulo(Escolalideresmodulo escolalideresmodulo) {
		this.escolalideresmodulo = escolalideresmodulo;
	}

	@Column(name = "matNome", length = 45)
	public String getMatNome() {
		return this.matNome;
	}

	public void setMatNome(String matNome) {
		this.matNome = matNome;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "escolalideresmateriasByAula2")
	public Set<Escolaliderescronogramaaulas> getEscolaliderescronogramaaulasesForAula2() {
		return this.escolaliderescronogramaaulasesForAula2;
	}

	public void setEscolaliderescronogramaaulasesForAula2(
			Set<Escolaliderescronogramaaulas> escolaliderescronogramaaulasesForAula2) {
		this.escolaliderescronogramaaulasesForAula2 = escolaliderescronogramaaulasesForAula2;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "escolalideresmateriasByAula1")
	public Set<Escolaliderescronogramaaulas> getEscolaliderescronogramaaulasesForAula1() {
		return this.escolaliderescronogramaaulasesForAula1;
	}

	public void setEscolaliderescronogramaaulasesForAula1(
			Set<Escolaliderescronogramaaulas> escolaliderescronogramaaulasesForAula1) {
		this.escolaliderescronogramaaulasesForAula1 = escolaliderescronogramaaulasesForAula1;
	}

}
