package br.com.pais.entities;

// Generated 06/05/2011 15:49:37 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Escolalideresdiscipulos generated by hbm2java
 */
@Entity
@Table(name = "escolalideresdiscipulos")
public class Escolalideresdiscipulos implements java.io.Serializable {

	private Integer elDisCod;
	private Discipulos discipulos;
	private Escolalideres escolalideres;
	private Set<Escolalideresfrequencia> escolalideresfrequencias = new HashSet<Escolalideresfrequencia>(
			0);

	public Escolalideresdiscipulos() {
	}

	public Escolalideresdiscipulos(Discipulos discipulos,
			Escolalideres escolalideres) {
		this.discipulos = discipulos;
		this.escolalideres = escolalideres;
	}

	public Escolalideresdiscipulos(Discipulos discipulos,
			Escolalideres escolalideres,
			Set<Escolalideresfrequencia> escolalideresfrequencias) {
		this.discipulos = discipulos;
		this.escolalideres = escolalideres;
		this.escolalideresfrequencias = escolalideresfrequencias;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "elDisCod", unique = true, nullable = false)
	public Integer getElDisCod() {
		return this.elDisCod;
	}

	public void setElDisCod(Integer elDisCod) {
		this.elDisCod = elDisCod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "discipuloCod", nullable = false)
	public Discipulos getDiscipulos() {
		return this.discipulos;
	}

	public void setDiscipulos(Discipulos discipulos) {
		this.discipulos = discipulos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "escolaCod", nullable = false)
	public Escolalideres getEscolalideres() {
		return this.escolalideres;
	}

	public void setEscolalideres(Escolalideres escolalideres) {
		this.escolalideres = escolalideres;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "escolalideresdiscipulos")
	public Set<Escolalideresfrequencia> getEscolalideresfrequencias() {
		return this.escolalideresfrequencias;
	}

	public void setEscolalideresfrequencias(
			Set<Escolalideresfrequencia> escolalideresfrequencias) {
		this.escolalideresfrequencias = escolalideresfrequencias;
	}

}
