package br.com.pais.entities;

// Generated 11/05/2011 14:16:49 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Escolalideresfinanceiroalunos generated by hbm2java
 */
@Entity
@Table(name = "escolalideresfinanceiroalunos", catalog = "wwwpais_sistema")
public class Escolalideresfinanceiroalunos implements java.io.Serializable {

	private EscolalideresfinanceiroalunosId id;
	private Escolalideresfinanceiro escolalideresfinanceiro;
	private Discipulos discipulos;
	private Escolarequerimentos escolarequerimentos;

	public Escolalideresfinanceiroalunos() {
	}

	public Escolalideresfinanceiroalunos(EscolalideresfinanceiroalunosId id,
			Escolalideresfinanceiro escolalideresfinanceiro,
			Discipulos discipulos) {
		this.id = id;
		this.escolalideresfinanceiro = escolalideresfinanceiro;
		this.discipulos = discipulos;
	}

	public Escolalideresfinanceiroalunos(EscolalideresfinanceiroalunosId id,
			Escolalideresfinanceiro escolalideresfinanceiro,
			Discipulos discipulos, Escolarequerimentos escolarequerimentos) {
		this.id = id;
		this.escolalideresfinanceiro = escolalideresfinanceiro;
		this.discipulos = discipulos;
		this.escolarequerimentos = escolarequerimentos;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "elFinanCod", column = @Column(name = "elFinanCod", nullable = false)),
			@AttributeOverride(name = "reqCod", column = @Column(name = "reqCod")),
			@AttributeOverride(name = "disCod", column = @Column(name = "disCod", nullable = false)) })
	public EscolalideresfinanceiroalunosId getId() {
		return this.id;
	}

	public void setId(EscolalideresfinanceiroalunosId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "elFinanCod", nullable = false, insertable = false, updatable = false)
	public Escolalideresfinanceiro getEscolalideresfinanceiro() {
		return this.escolalideresfinanceiro;
	}

	public void setEscolalideresfinanceiro(
			Escolalideresfinanceiro escolalideresfinanceiro) {
		this.escolalideresfinanceiro = escolalideresfinanceiro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "disCod", nullable = false, insertable = false, updatable = false)
	public Discipulos getDiscipulos() {
		return this.discipulos;
	}

	public void setDiscipulos(Discipulos discipulos) {
		this.discipulos = discipulos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "reqCod", insertable = false, updatable = false)
	public Escolarequerimentos getEscolarequerimentos() {
		return this.escolarequerimentos;
	}

	public void setEscolarequerimentos(Escolarequerimentos escolarequerimentos) {
		this.escolarequerimentos = escolarequerimentos;
	}

}
