package br.com.pais.entities;

// Generated 11/05/2011 14:16:49 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Escolalideres generated by hbm2java
 */
@Entity
@Table(name = "escolalideres", catalog = "wwwpais_sistema")
public class Escolalideres implements java.io.Serializable {

	private Integer elCod;
	private Discipulos discipulosByElMestre;
	private Discipulos discipulosByElPastor;
	private Discipulos discipulosByElCoordenadorPastor;
	private Discipulos discipulosByElMestrePastor;
	private Discipulos discipulosByElCoordenador;
	private Discipulos discipulosByElDiscipulador;
	private Discipulos discipulosByElPastorRequerimento;
	private Logradouro logradouro;
	private Date elDataRequerimento;
	private String elTipoLocal;
	private String elNomeCedeu;
	private String elFoneResidencial;
	private String elFoneCelular;
	private String elPontoReferencia;
	private String elRede;
	private String elRedeDia;
	private Date elRedeHorarioInicio;
	private Date elRedeHorarioFim;
	private String elMestreRede;
	private String elCoordenadorRede;
	private Character ativa;
	private Set<Escolalideresdiscipulos> escolalideresdiscipuloses = new HashSet<Escolalideresdiscipulos>(
			0);
	private Set<Escolalideresfechamentomodulo> escolalideresfechamentomodulos = new HashSet<Escolalideresfechamentomodulo>(
			0);
	private Set<Escolalideresfinanceiro> escolalideresfinanceiros = new HashSet<Escolalideresfinanceiro>(
			0);
	private Set<Escolaliderescronograma> escolaliderescronogramas = new HashSet<Escolaliderescronograma>(
			0);

	public Escolalideres() {
	}

	public Escolalideres(Discipulos discipulosByElMestre,
			Discipulos discipulosByElCoordenadorPastor,
			Discipulos discipulosByElMestrePastor,
			Discipulos discipulosByElCoordenador,
			Discipulos discipulosByElPastorRequerimento, Logradouro logradouro) {
		this.discipulosByElMestre = discipulosByElMestre;
		this.discipulosByElCoordenadorPastor = discipulosByElCoordenadorPastor;
		this.discipulosByElMestrePastor = discipulosByElMestrePastor;
		this.discipulosByElCoordenador = discipulosByElCoordenador;
		this.discipulosByElPastorRequerimento = discipulosByElPastorRequerimento;
		this.logradouro = logradouro;
	}

	public Escolalideres(Discipulos discipulosByElMestre,
			Discipulos discipulosByElPastor,
			Discipulos discipulosByElCoordenadorPastor,
			Discipulos discipulosByElMestrePastor,
			Discipulos discipulosByElCoordenador,
			Discipulos discipulosByElDiscipulador,
			Discipulos discipulosByElPastorRequerimento, Logradouro logradouro,
			Date elDataRequerimento, String elTipoLocal, String elNomeCedeu,
			String elFoneResidencial, String elFoneCelular,
			String elPontoReferencia, String elRede, String elRedeDia,
			Date elRedeHorarioInicio, Date elRedeHorarioFim,
			String elMestreRede, String elCoordenadorRede, Character ativa,
			Set<Escolalideresdiscipulos> escolalideresdiscipuloses,
			Set<Escolalideresfechamentomodulo> escolalideresfechamentomodulos,
			Set<Escolalideresfinanceiro> escolalideresfinanceiros,
			Set<Escolaliderescronograma> escolaliderescronogramas) {
		this.discipulosByElMestre = discipulosByElMestre;
		this.discipulosByElPastor = discipulosByElPastor;
		this.discipulosByElCoordenadorPastor = discipulosByElCoordenadorPastor;
		this.discipulosByElMestrePastor = discipulosByElMestrePastor;
		this.discipulosByElCoordenador = discipulosByElCoordenador;
		this.discipulosByElDiscipulador = discipulosByElDiscipulador;
		this.discipulosByElPastorRequerimento = discipulosByElPastorRequerimento;
		this.logradouro = logradouro;
		this.elDataRequerimento = elDataRequerimento;
		this.elTipoLocal = elTipoLocal;
		this.elNomeCedeu = elNomeCedeu;
		this.elFoneResidencial = elFoneResidencial;
		this.elFoneCelular = elFoneCelular;
		this.elPontoReferencia = elPontoReferencia;
		this.elRede = elRede;
		this.elRedeDia = elRedeDia;
		this.elRedeHorarioInicio = elRedeHorarioInicio;
		this.elRedeHorarioFim = elRedeHorarioFim;
		this.elMestreRede = elMestreRede;
		this.elCoordenadorRede = elCoordenadorRede;
		this.ativa = ativa;
		this.escolalideresdiscipuloses = escolalideresdiscipuloses;
		this.escolalideresfechamentomodulos = escolalideresfechamentomodulos;
		this.escolalideresfinanceiros = escolalideresfinanceiros;
		this.escolaliderescronogramas = escolaliderescronogramas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "elCod", unique = true, nullable = false)
	public Integer getElCod() {
		return this.elCod;
	}

	public void setElCod(Integer elCod) {
		this.elCod = elCod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "elMestre", nullable = false)
	public Discipulos getDiscipulosByElMestre() {
		return this.discipulosByElMestre;
	}

	public void setDiscipulosByElMestre(Discipulos discipulosByElMestre) {
		this.discipulosByElMestre = discipulosByElMestre;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "elPastor")
	public Discipulos getDiscipulosByElPastor() {
		return this.discipulosByElPastor;
	}

	public void setDiscipulosByElPastor(Discipulos discipulosByElPastor) {
		this.discipulosByElPastor = discipulosByElPastor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "elCoordenadorPastor", nullable = false)
	public Discipulos getDiscipulosByElCoordenadorPastor() {
		return this.discipulosByElCoordenadorPastor;
	}

	public void setDiscipulosByElCoordenadorPastor(
			Discipulos discipulosByElCoordenadorPastor) {
		this.discipulosByElCoordenadorPastor = discipulosByElCoordenadorPastor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "elMestrePastor", nullable = false)
	public Discipulos getDiscipulosByElMestrePastor() {
		return this.discipulosByElMestrePastor;
	}

	public void setDiscipulosByElMestrePastor(
			Discipulos discipulosByElMestrePastor) {
		this.discipulosByElMestrePastor = discipulosByElMestrePastor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "elCoordenador", nullable = false)
	public Discipulos getDiscipulosByElCoordenador() {
		return this.discipulosByElCoordenador;
	}

	public void setDiscipulosByElCoordenador(
			Discipulos discipulosByElCoordenador) {
		this.discipulosByElCoordenador = discipulosByElCoordenador;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "elDiscipulador")
	public Discipulos getDiscipulosByElDiscipulador() {
		return this.discipulosByElDiscipulador;
	}

	public void setDiscipulosByElDiscipulador(
			Discipulos discipulosByElDiscipulador) {
		this.discipulosByElDiscipulador = discipulosByElDiscipulador;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "elPastorRequerimento", nullable = false)
	public Discipulos getDiscipulosByElPastorRequerimento() {
		return this.discipulosByElPastorRequerimento;
	}

	public void setDiscipulosByElPastorRequerimento(
			Discipulos discipulosByElPastorRequerimento) {
		this.discipulosByElPastorRequerimento = discipulosByElPastorRequerimento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "elEndereco", nullable = false)
	public Logradouro getLogradouro() {
		return this.logradouro;
	}

	public void setLogradouro(Logradouro logradouro) {
		this.logradouro = logradouro;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "elDataRequerimento", length = 10)
	public Date getElDataRequerimento() {
		return this.elDataRequerimento;
	}

	public void setElDataRequerimento(Date elDataRequerimento) {
		this.elDataRequerimento = elDataRequerimento;
	}

	@Column(name = "elTipoLocal", length = 120)
	public String getElTipoLocal() {
		return this.elTipoLocal;
	}

	public void setElTipoLocal(String elTipoLocal) {
		this.elTipoLocal = elTipoLocal;
	}

	@Column(name = "elNomeCedeu", length = 120)
	public String getElNomeCedeu() {
		return this.elNomeCedeu;
	}

	public void setElNomeCedeu(String elNomeCedeu) {
		this.elNomeCedeu = elNomeCedeu;
	}

	@Column(name = "elFoneResidencial", length = 14)
	public String getElFoneResidencial() {
		return this.elFoneResidencial;
	}

	public void setElFoneResidencial(String elFoneResidencial) {
		this.elFoneResidencial = elFoneResidencial;
	}

	@Column(name = "elFoneCelular", length = 14)
	public String getElFoneCelular() {
		return this.elFoneCelular;
	}

	public void setElFoneCelular(String elFoneCelular) {
		this.elFoneCelular = elFoneCelular;
	}

	@Column(name = "elPontoReferencia", length = 150)
	public String getElPontoReferencia() {
		return this.elPontoReferencia;
	}

	public void setElPontoReferencia(String elPontoReferencia) {
		this.elPontoReferencia = elPontoReferencia;
	}

	@Column(name = "elRede", length = 120)
	public String getElRede() {
		return this.elRede;
	}

	public void setElRede(String elRede) {
		this.elRede = elRede;
	}

	@Column(name = "elRedeDia", length = 45)
	public String getElRedeDia() {
		return this.elRedeDia;
	}

	public void setElRedeDia(String elRedeDia) {
		this.elRedeDia = elRedeDia;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "elRedeHorarioInicio", length = 8)
	public Date getElRedeHorarioInicio() {
		return this.elRedeHorarioInicio;
	}

	public void setElRedeHorarioInicio(Date elRedeHorarioInicio) {
		this.elRedeHorarioInicio = elRedeHorarioInicio;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "elRedeHorarioFim", length = 8)
	public Date getElRedeHorarioFim() {
		return this.elRedeHorarioFim;
	}

	public void setElRedeHorarioFim(Date elRedeHorarioFim) {
		this.elRedeHorarioFim = elRedeHorarioFim;
	}

	@Column(name = "elMestreRede", length = 120)
	public String getElMestreRede() {
		return this.elMestreRede;
	}

	public void setElMestreRede(String elMestreRede) {
		this.elMestreRede = elMestreRede;
	}

	@Column(name = "elCoordenadorRede", length = 120)
	public String getElCoordenadorRede() {
		return this.elCoordenadorRede;
	}

	public void setElCoordenadorRede(String elCoordenadorRede) {
		this.elCoordenadorRede = elCoordenadorRede;
	}

	@Column(name = "ativa", length = 1)
	public Character getAtiva() {
		return this.ativa;
	}

	public void setAtiva(Character ativa) {
		this.ativa = ativa;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "escolalideres")
	public Set<Escolalideresdiscipulos> getEscolalideresdiscipuloses() {
		return this.escolalideresdiscipuloses;
	}

	public void setEscolalideresdiscipuloses(
			Set<Escolalideresdiscipulos> escolalideresdiscipuloses) {
		this.escolalideresdiscipuloses = escolalideresdiscipuloses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "escolalideres")
	public Set<Escolalideresfechamentomodulo> getEscolalideresfechamentomodulos() {
		return this.escolalideresfechamentomodulos;
	}

	public void setEscolalideresfechamentomodulos(
			Set<Escolalideresfechamentomodulo> escolalideresfechamentomodulos) {
		this.escolalideresfechamentomodulos = escolalideresfechamentomodulos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "escolalideres")
	public Set<Escolalideresfinanceiro> getEscolalideresfinanceiros() {
		return this.escolalideresfinanceiros;
	}

	public void setEscolalideresfinanceiros(
			Set<Escolalideresfinanceiro> escolalideresfinanceiros) {
		this.escolalideresfinanceiros = escolalideresfinanceiros;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "escolalideres")
	public Set<Escolaliderescronograma> getEscolaliderescronogramas() {
		return this.escolaliderescronogramas;
	}

	public void setEscolaliderescronogramas(
			Set<Escolaliderescronograma> escolaliderescronogramas) {
		this.escolaliderescronogramas = escolaliderescronogramas;
	}

}
