package br.com.pais.entities;

// Generated 11/05/2011 14:16:49 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Escolalidereslivro generated by hbm2java
 */
@Entity
@Table(name = "escolalidereslivro", catalog = "wwwpais_sistema")
public class Escolalidereslivro implements java.io.Serializable {

	private Integer livroCod;
	private String livroNome;
	private Set<Escolalideresmaterias> escolalideresmateriases = new HashSet<Escolalideresmaterias>(
			0);

	public Escolalidereslivro() {
	}

	public Escolalidereslivro(String livroNome,
			Set<Escolalideresmaterias> escolalideresmateriases) {
		this.livroNome = livroNome;
		this.escolalideresmateriases = escolalideresmateriases;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "livroCod", unique = true, nullable = false)
	public Integer getLivroCod() {
		return this.livroCod;
	}

	public void setLivroCod(Integer livroCod) {
		this.livroCod = livroCod;
	}

	@Column(name = "livroNome", length = 80)
	public String getLivroNome() {
		return this.livroNome;
	}

	public void setLivroNome(String livroNome) {
		this.livroNome = livroNome;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "escolalidereslivro")
	public Set<Escolalideresmaterias> getEscolalideresmateriases() {
		return this.escolalideresmateriases;
	}

	public void setEscolalideresmateriases(
			Set<Escolalideresmaterias> escolalideresmateriases) {
		this.escolalideresmateriases = escolalideresmateriases;
	}

}
