package br.com.pais.entities;

// Generated 06/05/2011 15:49:37 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Escolalideresmodulo generated by hbm2java
 */
@Entity
@Table(name = "escolalideresmodulo")
public class Escolalideresmodulo implements java.io.Serializable {

	private Integer modCod;
	private String modNome;
	private Set<Escolalideresmaterias> escolalideresmateriases = new HashSet<Escolalideresmaterias>(
			0);

	public Escolalideresmodulo() {
	}

	public Escolalideresmodulo(String modNome) {
		this.modNome = modNome;
	}

	public Escolalideresmodulo(String modNome,
			Set<Escolalideresmaterias> escolalideresmateriases) {
		this.modNome = modNome;
		this.escolalideresmateriases = escolalideresmateriases;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "modCod", unique = true, nullable = false)
	public Integer getModCod() {
		return this.modCod;
	}

	public void setModCod(Integer modCod) {
		this.modCod = modCod;
	}

	@Column(name = "modNome", nullable = false, length = 80)
	public String getModNome() {
		return this.modNome;
	}

	public void setModNome(String modNome) {
		this.modNome = modNome;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "escolalideresmodulo")
	public Set<Escolalideresmaterias> getEscolalideresmateriases() {
		return this.escolalideresmateriases;
	}

	public void setEscolalideresmateriases(
			Set<Escolalideresmaterias> escolalideresmateriases) {
		this.escolalideresmateriases = escolalideresmateriases;
	}

}
