package br.com.pais.entities;

// Generated 06/05/2011 15:49:37 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FinanceiroigrejasId generated by hbm2java
 */
@Embeddable
public class FinanceiroigrejasId implements java.io.Serializable {

	private int igrejasIgrcod;
	private int pacotesIdpacotes;

	public FinanceiroigrejasId() {
	}

	public FinanceiroigrejasId(int igrejasIgrcod, int pacotesIdpacotes) {
		this.igrejasIgrcod = igrejasIgrcod;
		this.pacotesIdpacotes = pacotesIdpacotes;
	}

	@Column(name = "igrejas_igrcod", nullable = false)
	public int getIgrejasIgrcod() {
		return this.igrejasIgrcod;
	}

	public void setIgrejasIgrcod(int igrejasIgrcod) {
		this.igrejasIgrcod = igrejasIgrcod;
	}

	@Column(name = "pacotes_idpacotes", nullable = false)
	public int getPacotesIdpacotes() {
		return this.pacotesIdpacotes;
	}

	public void setPacotesIdpacotes(int pacotesIdpacotes) {
		this.pacotesIdpacotes = pacotesIdpacotes;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FinanceiroigrejasId))
			return false;
		FinanceiroigrejasId castOther = (FinanceiroigrejasId) other;

		return (this.getIgrejasIgrcod() == castOther.getIgrejasIgrcod())
				&& (this.getPacotesIdpacotes() == castOther
						.getPacotesIdpacotes());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIgrejasIgrcod();
		result = 37 * result + this.getPacotesIdpacotes();
		return result;
	}

}
