package br.com.pais.entities;

// Generated 06/05/2011 15:49:37 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Fotosbases generated by hbm2java
 */
@Entity
@Table(name = "fotosbases")
public class Fotosbases implements java.io.Serializable {

	private Integer codFoto;
	private Bases bases;
	private String foto;
	private String legenda;
	private byte[] imagem;
	
	public Fotosbases() {
	}

	public Fotosbases(Bases bases, String foto) {
		this.bases = bases;
		this.foto = foto;
	}

	public Fotosbases(Bases bases, String foto, String legenda) {
		this.bases = bases;
		this.foto = foto;
		this.legenda = legenda;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "codFoto", unique = true, nullable = false)
	public Integer getCodFoto() {
		return this.codFoto;
	}

	public void setCodFoto(Integer codFoto) {
		this.codFoto = codFoto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "basCod", nullable = false)
	public Bases getBases() {
		return this.bases;
	}

	public void setBases(Bases bases) {
		this.bases = bases;
	}

	@Column(name = "foto", nullable = false, length = 100)
	public String getFoto() {
		return this.foto;
	}

	public void setFoto(String foto) {
		this.foto = foto;
	}

	@Column(name = "legenda", length = 100)
	public String getLegenda() {
		return this.legenda;
	}

	public void setLegenda(String legenda) {
		this.legenda = legenda;
	}
	/**
	 * @return the imagem
	 */
	@Transient
	public byte[] getImagem() {
		return imagem;
	}

	/**
	 * @param imagem the imagem to set
	 */
	public void setImagem(byte[] imagem) {
		this.imagem = imagem;
	}

}
