package br.com.pais.entities;

// Generated 06/05/2011 15:49:37 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FrequenciaId generated by hbm2java
 */
@Embeddable
public class FrequenciaId implements java.io.Serializable {

	private int discipulosDisCod;
	private int palestrasHasEncontrosPalestrasPalCod;
	private int palestrasHasEncontrosEncontrosEncCod;

	public FrequenciaId() {
	}

	public FrequenciaId(int discipulosDisCod,
			int palestrasHasEncontrosPalestrasPalCod,
			int palestrasHasEncontrosEncontrosEncCod) {
		this.discipulosDisCod = discipulosDisCod;
		this.palestrasHasEncontrosPalestrasPalCod = palestrasHasEncontrosPalestrasPalCod;
		this.palestrasHasEncontrosEncontrosEncCod = palestrasHasEncontrosEncontrosEncCod;
	}

	@Column(name = "discipulos_disCod", nullable = false)
	public int getDiscipulosDisCod() {
		return this.discipulosDisCod;
	}

	public void setDiscipulosDisCod(int discipulosDisCod) {
		this.discipulosDisCod = discipulosDisCod;
	}

	@Column(name = "Palestras_has_encontros_Palestras_PalCod", nullable = false)
	public int getPalestrasHasEncontrosPalestrasPalCod() {
		return this.palestrasHasEncontrosPalestrasPalCod;
	}

	public void setPalestrasHasEncontrosPalestrasPalCod(
			int palestrasHasEncontrosPalestrasPalCod) {
		this.palestrasHasEncontrosPalestrasPalCod = palestrasHasEncontrosPalestrasPalCod;
	}

	@Column(name = "Palestras_has_encontros_encontros_EncCod", nullable = false)
	public int getPalestrasHasEncontrosEncontrosEncCod() {
		return this.palestrasHasEncontrosEncontrosEncCod;
	}

	public void setPalestrasHasEncontrosEncontrosEncCod(
			int palestrasHasEncontrosEncontrosEncCod) {
		this.palestrasHasEncontrosEncontrosEncCod = palestrasHasEncontrosEncontrosEncCod;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FrequenciaId))
			return false;
		FrequenciaId castOther = (FrequenciaId) other;

		return (this.getDiscipulosDisCod() == castOther.getDiscipulosDisCod())
				&& (this.getPalestrasHasEncontrosPalestrasPalCod() == castOther
						.getPalestrasHasEncontrosPalestrasPalCod())
				&& (this.getPalestrasHasEncontrosEncontrosEncCod() == castOther
						.getPalestrasHasEncontrosEncontrosEncCod());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getDiscipulosDisCod();
		result = 37 * result + this.getPalestrasHasEncontrosPalestrasPalCod();
		result = 37 * result + this.getPalestrasHasEncontrosEncontrosEncCod();
		return result;
	}

}
