package br.com.pais.entities;

// Generated 24/05/2011 10:42:25 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FrequenciaId generated by hbm2java
 */
@Embeddable
public class FrequenciaId implements java.io.Serializable {

	private int discipulos;
	private int encontrospalestras;

	public FrequenciaId() {
	}

	public FrequenciaId(int discipulos, int encontrospalestras) {
		this.discipulos = discipulos;
		this.encontrospalestras = encontrospalestras;
	}

	@Column(name = "discipulos", nullable = false)
	public int getDiscipulos() {
		return this.discipulos;
	}

	public void setDiscipulos(int discipulos) {
		this.discipulos = discipulos;
	}

	@Column(name = "encontrospalestras", nullable = false)
	public int getEncontrospalestras() {
		return this.encontrospalestras;
	}

	public void setEncontrospalestras(int encontrospalestras) {
		this.encontrospalestras = encontrospalestras;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FrequenciaId))
			return false;
		FrequenciaId castOther = (FrequenciaId) other;

		return (this.getDiscipulos() == castOther.getDiscipulos())
				&& (this.getEncontrospalestras() == castOther
						.getEncontrospalestras());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getDiscipulos();
		result = 37 * result + this.getEncontrospalestras();
		return result;
	}

}
