package br.com.pais.entities;

// Generated 06/05/2011 15:49:37 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Lideres generated by hbm2java
 */
@Entity
@Table(name = "lideres")
public class Lideres implements java.io.Serializable {

	private LideresId id;
	private Discipulos discipulos;
	private String tipo;

	public Lideres() {
	}

	public Lideres(LideresId id, Discipulos discipulos, String tipo) {
		this.id = id;
		this.discipulos = discipulos;
		this.tipo = tipo;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "discipulosDisCod", column = @Column(name = "discipulos_disCod", nullable = false)),
			@AttributeOverride(name = "dadosencontrosDadenccod", column = @Column(name = "dadosencontros_dadenccod", nullable = false)) })
	public LideresId getId() {
		return this.id;
	}

	public void setId(LideresId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "discipulos_disCod", nullable = false, insertable = false, updatable = false)
	public Discipulos getDiscipulos() {
		return this.discipulos;
	}

	public void setDiscipulos(Discipulos discipulos) {
		this.discipulos = discipulos;
	}

	@Column(name = "tipo", nullable = false, length = 100)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

}
