package br.com.pais.entities;

// Generated 06/05/2011 15:49:37 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ministra generated by hbm2java
 */
@Entity
@Table(name = "ministra")
public class Ministra implements java.io.Serializable {

	private MinistraId id;
	private Discipulos discipulos;
	private Dadosencontros dadosencontros;

	public Ministra() {
	}

	public Ministra(MinistraId id, Dadosencontros dadosencontros, Discipulos discipulos) {
		this.id = id;
		this.discipulos = discipulos;
		this.dadosencontros = dadosencontros;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "discipulosDisCod", column = @Column(name = "discipulos_disCod", nullable = false)),
			@AttributeOverride(name = "dadosencontrosDadenccod", column = @Column(name = "dadosencontros_dadenccod", nullable = false)) })
	public MinistraId getId() {
		return this.id;
	}

	public void setId(MinistraId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dadosencontros_dadenccod", nullable = false, insertable = false, updatable = false)
	public Dadosencontros getDadosencontros() {
		return this.dadosencontros;
	}

	public void setDadosencontros(Dadosencontros dadosencontros) {
		this.dadosencontros = dadosencontros;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "discipulos_disCod", nullable = false, insertable = false, updatable = false)
	public Discipulos getDiscipulos() {
		return this.discipulos;
	}

	public void setDiscipulos(Discipulos discipulos) {
		this.discipulos = discipulos;
	}

}
