package br.com.pais.entities;

// Generated 14/02/2011 15:49:33 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MovimentochequeId generated by hbm2java
 */
@Embeddable
public class MovimentochequeId implements java.io.Serializable {

	private int codMovimento;
	private int codBanco;
	private String preDatado;
	private String comp;
	private String banco;
	private String agencia;
	private String campoC1;
	private String conta;
	private String campoC2;
	private String numCheque;
	private String campoC3;
	private Double valNum;
	private String valExtenso;
	private String pagoPara;
	private Date dataCheque;
	private String dataCidade;
	private String dataDia;
	private String dataMes;
	private String dataAno;
	private String nomPagante;
	private String cpfPagante;
	private String clienteDesdeMes;
	private String clienteDesdeAno;
	private String numAutenticacao;

	public MovimentochequeId() {
	}

	public MovimentochequeId(int codMovimento, int codBanco) {
		this.codMovimento = codMovimento;
		this.codBanco = codBanco;
	}

	public MovimentochequeId(int codMovimento, int codBanco, String preDatado,
			String comp, String banco, String agencia, String campoC1,
			String conta, String campoC2, String numCheque, String campoC3,
			Double valNum, String valExtenso, String pagoPara,
			Date dataCheque, String dataCidade, String dataDia, String dataMes,
			String dataAno, String nomPagante, String cpfPagante,
			String clienteDesdeMes, String clienteDesdeAno,
			String numAutenticacao) {
		this.codMovimento = codMovimento;
		this.codBanco = codBanco;
		this.preDatado = preDatado;
		this.comp = comp;
		this.banco = banco;
		this.agencia = agencia;
		this.campoC1 = campoC1;
		this.conta = conta;
		this.campoC2 = campoC2;
		this.numCheque = numCheque;
		this.campoC3 = campoC3;
		this.valNum = valNum;
		this.valExtenso = valExtenso;
		this.pagoPara = pagoPara;
		this.dataCheque = dataCheque;
		this.dataCidade = dataCidade;
		this.dataDia = dataDia;
		this.dataMes = dataMes;
		this.dataAno = dataAno;
		this.nomPagante = nomPagante;
		this.cpfPagante = cpfPagante;
		this.clienteDesdeMes = clienteDesdeMes;
		this.clienteDesdeAno = clienteDesdeAno;
		this.numAutenticacao = numAutenticacao;
	}

	@Column(name = "CodMovimento", nullable = false)
	public int getCodMovimento() {
		return this.codMovimento;
	}

	public void setCodMovimento(int codMovimento) {
		this.codMovimento = codMovimento;
	}

	@Column(name = "CodBanco", nullable = false)
	public int getCodBanco() {
		return this.codBanco;
	}

	public void setCodBanco(int codBanco) {
		this.codBanco = codBanco;
	}

	@Column(name = "PreDatado", length = 1)
	public String getPreDatado() {
		return this.preDatado;
	}

	public void setPreDatado(String preDatado) {
		this.preDatado = preDatado;
	}

	@Column(name = "Comp", length = 10)
	public String getComp() {
		return this.comp;
	}

	public void setComp(String comp) {
		this.comp = comp;
	}

	@Column(name = "Banco", length = 10)
	public String getBanco() {
		return this.banco;
	}

	public void setBanco(String banco) {
		this.banco = banco;
	}

	@Column(name = "Agencia", length = 10)
	public String getAgencia() {
		return this.agencia;
	}

	public void setAgencia(String agencia) {
		this.agencia = agencia;
	}

	@Column(name = "campoC1", length = 1)
	public String getCampoC1() {
		return this.campoC1;
	}

	public void setCampoC1(String campoC1) {
		this.campoC1 = campoC1;
	}

	@Column(name = "Conta", length = 20)
	public String getConta() {
		return this.conta;
	}

	public void setConta(String conta) {
		this.conta = conta;
	}

	@Column(name = "campoC2", length = 1)
	public String getCampoC2() {
		return this.campoC2;
	}

	public void setCampoC2(String campoC2) {
		this.campoC2 = campoC2;
	}

	@Column(name = "NumCheque", length = 20)
	public String getNumCheque() {
		return this.numCheque;
	}

	public void setNumCheque(String numCheque) {
		this.numCheque = numCheque;
	}

	@Column(name = "campoC3", length = 1)
	public String getCampoC3() {
		return this.campoC3;
	}

	public void setCampoC3(String campoC3) {
		this.campoC3 = campoC3;
	}

	@Column(name = "ValNum", precision = 10)
	public Double getValNum() {
		return this.valNum;
	}

	public void setValNum(Double valNum) {
		this.valNum = valNum;
	}

	@Column(name = "ValExtenso", length = 150)
	public String getValExtenso() {
		return this.valExtenso;
	}

	public void setValExtenso(String valExtenso) {
		this.valExtenso = valExtenso;
	}

	@Column(name = "PagoPara", length = 100)
	public String getPagoPara() {
		return this.pagoPara;
	}

	public void setPagoPara(String pagoPara) {
		this.pagoPara = pagoPara;
	}

	@Column(name = "DataCheque", length = 10)
	public Date getDataCheque() {
		return this.dataCheque;
	}

	public void setDataCheque(Date dataCheque) {
		this.dataCheque = dataCheque;
	}

	@Column(name = "DataCidade", length = 100)
	public String getDataCidade() {
		return this.dataCidade;
	}

	public void setDataCidade(String dataCidade) {
		this.dataCidade = dataCidade;
	}

	@Column(name = "DataDia", length = 10)
	public String getDataDia() {
		return this.dataDia;
	}

	public void setDataDia(String dataDia) {
		this.dataDia = dataDia;
	}

	@Column(name = "DataMes", length = 60)
	public String getDataMes() {
		return this.dataMes;
	}

	public void setDataMes(String dataMes) {
		this.dataMes = dataMes;
	}

	@Column(name = "DataAno", length = 4)
	public String getDataAno() {
		return this.dataAno;
	}

	public void setDataAno(String dataAno) {
		this.dataAno = dataAno;
	}

	@Column(name = "NomPagante", length = 100)
	public String getNomPagante() {
		return this.nomPagante;
	}

	public void setNomPagante(String nomPagante) {
		this.nomPagante = nomPagante;
	}

	@Column(name = "CpfPagante", length = 14)
	public String getCpfPagante() {
		return this.cpfPagante;
	}

	public void setCpfPagante(String cpfPagante) {
		this.cpfPagante = cpfPagante;
	}

	@Column(name = "ClienteDesdeMes", length = 2)
	public String getClienteDesdeMes() {
		return this.clienteDesdeMes;
	}

	public void setClienteDesdeMes(String clienteDesdeMes) {
		this.clienteDesdeMes = clienteDesdeMes;
	}

	@Column(name = "ClienteDesdeAno", length = 4)
	public String getClienteDesdeAno() {
		return this.clienteDesdeAno;
	}

	public void setClienteDesdeAno(String clienteDesdeAno) {
		this.clienteDesdeAno = clienteDesdeAno;
	}

	@Column(name = "NumAutenticacao", length = 150)
	public String getNumAutenticacao() {
		return this.numAutenticacao;
	}

	public void setNumAutenticacao(String numAutenticacao) {
		this.numAutenticacao = numAutenticacao;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MovimentochequeId))
			return false;
		MovimentochequeId castOther = (MovimentochequeId) other;

		return (this.getCodMovimento() == castOther.getCodMovimento())
				&& (this.getCodBanco() == castOther.getCodBanco())
				&& ((this.getPreDatado() == castOther.getPreDatado()) || (this
						.getPreDatado() != null
						&& castOther.getPreDatado() != null && this
						.getPreDatado().equals(castOther.getPreDatado())))
				&& ((this.getComp() == castOther.getComp()) || (this.getComp() != null
						&& castOther.getComp() != null && this.getComp()
						.equals(castOther.getComp())))
				&& ((this.getBanco() == castOther.getBanco()) || (this
						.getBanco() != null && castOther.getBanco() != null && this
						.getBanco().equals(castOther.getBanco())))
				&& ((this.getAgencia() == castOther.getAgencia()) || (this
						.getAgencia() != null && castOther.getAgencia() != null && this
						.getAgencia().equals(castOther.getAgencia())))
				&& ((this.getCampoC1() == castOther.getCampoC1()) || (this
						.getCampoC1() != null && castOther.getCampoC1() != null && this
						.getCampoC1().equals(castOther.getCampoC1())))
				&& ((this.getConta() == castOther.getConta()) || (this
						.getConta() != null && castOther.getConta() != null && this
						.getConta().equals(castOther.getConta())))
				&& ((this.getCampoC2() == castOther.getCampoC2()) || (this
						.getCampoC2() != null && castOther.getCampoC2() != null && this
						.getCampoC2().equals(castOther.getCampoC2())))
				&& ((this.getNumCheque() == castOther.getNumCheque()) || (this
						.getNumCheque() != null
						&& castOther.getNumCheque() != null && this
						.getNumCheque().equals(castOther.getNumCheque())))
				&& ((this.getCampoC3() == castOther.getCampoC3()) || (this
						.getCampoC3() != null && castOther.getCampoC3() != null && this
						.getCampoC3().equals(castOther.getCampoC3())))
				&& ((this.getValNum() == castOther.getValNum()) || (this
						.getValNum() != null && castOther.getValNum() != null && this
						.getValNum().equals(castOther.getValNum())))
				&& ((this.getValExtenso() == castOther.getValExtenso()) || (this
						.getValExtenso() != null
						&& castOther.getValExtenso() != null && this
						.getValExtenso().equals(castOther.getValExtenso())))
				&& ((this.getPagoPara() == castOther.getPagoPara()) || (this
						.getPagoPara() != null
						&& castOther.getPagoPara() != null && this
						.getPagoPara().equals(castOther.getPagoPara())))
				&& ((this.getDataCheque() == castOther.getDataCheque()) || (this
						.getDataCheque() != null
						&& castOther.getDataCheque() != null && this
						.getDataCheque().equals(castOther.getDataCheque())))
				&& ((this.getDataCidade() == castOther.getDataCidade()) || (this
						.getDataCidade() != null
						&& castOther.getDataCidade() != null && this
						.getDataCidade().equals(castOther.getDataCidade())))
				&& ((this.getDataDia() == castOther.getDataDia()) || (this
						.getDataDia() != null && castOther.getDataDia() != null && this
						.getDataDia().equals(castOther.getDataDia())))
				&& ((this.getDataMes() == castOther.getDataMes()) || (this
						.getDataMes() != null && castOther.getDataMes() != null && this
						.getDataMes().equals(castOther.getDataMes())))
				&& ((this.getDataAno() == castOther.getDataAno()) || (this
						.getDataAno() != null && castOther.getDataAno() != null && this
						.getDataAno().equals(castOther.getDataAno())))
				&& ((this.getNomPagante() == castOther.getNomPagante()) || (this
						.getNomPagante() != null
						&& castOther.getNomPagante() != null && this
						.getNomPagante().equals(castOther.getNomPagante())))
				&& ((this.getCpfPagante() == castOther.getCpfPagante()) || (this
						.getCpfPagante() != null
						&& castOther.getCpfPagante() != null && this
						.getCpfPagante().equals(castOther.getCpfPagante())))
				&& ((this.getClienteDesdeMes() == castOther
						.getClienteDesdeMes()) || (this.getClienteDesdeMes() != null
						&& castOther.getClienteDesdeMes() != null && this
						.getClienteDesdeMes().equals(
								castOther.getClienteDesdeMes())))
				&& ((this.getClienteDesdeAno() == castOther
						.getClienteDesdeAno()) || (this.getClienteDesdeAno() != null
						&& castOther.getClienteDesdeAno() != null && this
						.getClienteDesdeAno().equals(
								castOther.getClienteDesdeAno())))
				&& ((this.getNumAutenticacao() == castOther
						.getNumAutenticacao()) || (this.getNumAutenticacao() != null
						&& castOther.getNumAutenticacao() != null && this
						.getNumAutenticacao().equals(
								castOther.getNumAutenticacao())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodMovimento();
		result = 37 * result + this.getCodBanco();
		result = 37 * result
				+ (getPreDatado() == null ? 0 : this.getPreDatado().hashCode());
		result = 37 * result
				+ (getComp() == null ? 0 : this.getComp().hashCode());
		result = 37 * result
				+ (getBanco() == null ? 0 : this.getBanco().hashCode());
		result = 37 * result
				+ (getAgencia() == null ? 0 : this.getAgencia().hashCode());
		result = 37 * result
				+ (getCampoC1() == null ? 0 : this.getCampoC1().hashCode());
		result = 37 * result
				+ (getConta() == null ? 0 : this.getConta().hashCode());
		result = 37 * result
				+ (getCampoC2() == null ? 0 : this.getCampoC2().hashCode());
		result = 37 * result
				+ (getNumCheque() == null ? 0 : this.getNumCheque().hashCode());
		result = 37 * result
				+ (getCampoC3() == null ? 0 : this.getCampoC3().hashCode());
		result = 37 * result
				+ (getValNum() == null ? 0 : this.getValNum().hashCode());
		result = 37
				* result
				+ (getValExtenso() == null ? 0 : this.getValExtenso()
						.hashCode());
		result = 37 * result
				+ (getPagoPara() == null ? 0 : this.getPagoPara().hashCode());
		result = 37
				* result
				+ (getDataCheque() == null ? 0 : this.getDataCheque()
						.hashCode());
		result = 37
				* result
				+ (getDataCidade() == null ? 0 : this.getDataCidade()
						.hashCode());
		result = 37 * result
				+ (getDataDia() == null ? 0 : this.getDataDia().hashCode());
		result = 37 * result
				+ (getDataMes() == null ? 0 : this.getDataMes().hashCode());
		result = 37 * result
				+ (getDataAno() == null ? 0 : this.getDataAno().hashCode());
		result = 37
				* result
				+ (getNomPagante() == null ? 0 : this.getNomPagante()
						.hashCode());
		result = 37
				* result
				+ (getCpfPagante() == null ? 0 : this.getCpfPagante()
						.hashCode());
		result = 37
				* result
				+ (getClienteDesdeMes() == null ? 0 : this.getClienteDesdeMes()
						.hashCode());
		result = 37
				* result
				+ (getClienteDesdeAno() == null ? 0 : this.getClienteDesdeAno()
						.hashCode());
		result = 37
				* result
				+ (getNumAutenticacao() == null ? 0 : this.getNumAutenticacao()
						.hashCode());
		return result;
	}

}
