package br.com.pais.entities;

// Generated 06/05/2011 15:49:37 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Participa generated by hbm2java
 */
@Entity
@Table(name = "participa")
public class Participa implements java.io.Serializable {

	private ParticipaId id;
	private Discipulos discipulos;

	public Participa() {
	}

	public Participa(ParticipaId id, Discipulos discipulos) {
		this.id = id;
		this.discipulos = discipulos;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "disCod", column = @Column(name = "disCod", nullable = false)),
			@AttributeOverride(name = "dadosencontrosDadenccod", column = @Column(name = "dadosencontros_dadenccod", nullable = false)) })
	public ParticipaId getId() {
		return this.id;
	}

	public void setId(ParticipaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "disCod", nullable = false, insertable = false, updatable = false)
	public Discipulos getDiscipulos() {
		return this.discipulos;
	}

	public void setDiscipulos(Discipulos discipulos) {
		this.discipulos = discipulos;
	}

}
