package br.com.pais.entities;

// Generated 12/09/2010 22:48:01 by Hibernate Tools 3.3.0.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Bases generated by hbm2java
 */
@Entity
@Table(name = "bases", catalog = "wwwpais_sistema", uniqueConstraints = @UniqueConstraint(columnNames = "basNuEndereco"))
public class Bases implements java.io.Serializable {

	private Integer basCod;
	private Discipulos discipulosByLiderGovJusto;
	private Logradouro logradouro;
	private Statusbase statusbase;
	private Funeclesiasticasdiscipulos funeclesiasticasdiscipulos;
	private Discipulos discipulosByLiderAcaoSocial;
	private Condicaobase condicaobase;
	private Tipobases tipobases;
	private Date basHorReuniao;
	private Date basDtReuniao;
	private Date basDtAbertura;
	private String basFlag;
	private String basNuEndereco;
	private String basEndComplemento;
	private Set<Telbases> telbaseses = new HashSet<Telbases>(0);
	private Set<Celulas> celulases = new HashSet<Celulas>(0);
	private Set<Movimento> movimentos = new HashSet<Movimento>(0);

	public Bases() {
	}

	public Bases(Funeclesiasticasdiscipulos funeclesiasticasdiscipulos,
			Tipobases tipobases) {
		this.funeclesiasticasdiscipulos = funeclesiasticasdiscipulos;
		this.tipobases = tipobases;
	}

	public Bases(Discipulos discipulosByLiderGovJusto, Logradouro logradouro,
			Statusbase statusbase,
			Funeclesiasticasdiscipulos funeclesiasticasdiscipulos,
			Discipulos discipulosByLiderAcaoSocial, Condicaobase condicaobase,
			Tipobases tipobases, Date basHorReuniao, Date basDtReuniao,
			Date basDtAbertura, String basFlag, String basNuEndereco,
			String basEndComplemento, Set<Telbases> telbaseses,
			Set<Celulas> celulases, Set<Movimento> movimentos) {
		this.discipulosByLiderGovJusto = discipulosByLiderGovJusto;
		this.logradouro = logradouro;
		this.statusbase = statusbase;
		this.funeclesiasticasdiscipulos = funeclesiasticasdiscipulos;
		this.discipulosByLiderAcaoSocial = discipulosByLiderAcaoSocial;
		this.condicaobase = condicaobase;
		this.tipobases = tipobases;
		this.basHorReuniao = basHorReuniao;
		this.basDtReuniao = basDtReuniao;
		this.basDtAbertura = basDtAbertura;
		this.basFlag = basFlag;
		this.basNuEndereco = basNuEndereco;
		this.basEndComplemento = basEndComplemento;
		this.telbaseses = telbaseses;
		this.celulases = celulases;
		this.movimentos = movimentos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "basCod", unique = true, nullable = false)
	public Integer getBasCod() {
		return this.basCod;
	}

	public void setBasCod(Integer basCod) {
		this.basCod = basCod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "liderGovJusto")
	public Discipulos getDiscipulosByLiderGovJusto() {
		return this.discipulosByLiderGovJusto;
	}

	public void setDiscipulosByLiderGovJusto(
			Discipulos discipulosByLiderGovJusto) {
		this.discipulosByLiderGovJusto = discipulosByLiderGovJusto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "basEndereco")
	public Logradouro getLogradouro() {
		return this.logradouro;
	}

	public void setLogradouro(Logradouro logradouro) {
		this.logradouro = logradouro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "basStatus")
	public Statusbase getStatusbase() {
		return this.statusbase;
	}

	public void setStatusbase(Statusbase statusbase) {
		this.statusbase = statusbase;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "funCod", referencedColumnName = "funCod", nullable = false),
			@JoinColumn(name = "disCod", referencedColumnName = "disCod", nullable = false) })
	public Funeclesiasticasdiscipulos getFuneclesiasticasdiscipulos() {
		return this.funeclesiasticasdiscipulos;
	}

	public void setFuneclesiasticasdiscipulos(
			Funeclesiasticasdiscipulos funeclesiasticasdiscipulos) {
		this.funeclesiasticasdiscipulos = funeclesiasticasdiscipulos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "liderAcaoSocial")
	public Discipulos getDiscipulosByLiderAcaoSocial() {
		return this.discipulosByLiderAcaoSocial;
	}

	public void setDiscipulosByLiderAcaoSocial(
			Discipulos discipulosByLiderAcaoSocial) {
		this.discipulosByLiderAcaoSocial = discipulosByLiderAcaoSocial;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "basCondicao")
	public Condicaobase getCondicaobase() {
		return this.condicaobase;
	}

	public void setCondicaobase(Condicaobase condicaobase) {
		this.condicaobase = condicaobase;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tpbCod", nullable = false)
	public Tipobases getTipobases() {
		return this.tipobases;
	}

	public void setTipobases(Tipobases tipobases) {
		this.tipobases = tipobases;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "basHorReuniao", length = 19)
	public Date getBasHorReuniao() {
		return this.basHorReuniao;
	}

	public void setBasHorReuniao(Date basHorReuniao) {
		this.basHorReuniao = basHorReuniao;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "basDtReuniao", length = 10)
	public Date getBasDtReuniao() {
		return this.basDtReuniao;
	}

	public void setBasDtReuniao(Date basDtReuniao) {
		this.basDtReuniao = basDtReuniao;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "basDtAbertura", length = 10)
	public Date getBasDtAbertura() {
		return this.basDtAbertura;
	}

	public void setBasDtAbertura(Date basDtAbertura) {
		this.basDtAbertura = basDtAbertura;
	}

	@Column(name = "basFlag", length = 3)
	public String getBasFlag() {
		return this.basFlag;
	}

	public void setBasFlag(String basFlag) {
		this.basFlag = basFlag;
	}

	@Column(name = "basNuEndereco", unique = true, length = 5)
	public String getBasNuEndereco() {
		return this.basNuEndereco;
	}

	public void setBasNuEndereco(String basNuEndereco) {
		this.basNuEndereco = basNuEndereco;
	}

	@Column(name = "basEndComplemento", length = 45)
	public String getBasEndComplemento() {
		return this.basEndComplemento;
	}

	public void setBasEndComplemento(String basEndComplemento) {
		this.basEndComplemento = basEndComplemento;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bases")
	public Set<Telbases> getTelbaseses() {
		return this.telbaseses;
	}

	public void setTelbaseses(Set<Telbases> telbaseses) {
		this.telbaseses = telbaseses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bases")
	public Set<Celulas> getCelulases() {
		return this.celulases;
	}

	public void setCelulases(Set<Celulas> celulases) {
		this.celulases = celulases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bases")
	public Set<Movimento> getMovimentos() {
		return this.movimentos;
	}

	public void setMovimentos(Set<Movimento> movimentos) {
		this.movimentos = movimentos;
	}

}
