package br.com.pais.entities;

// Generated 17/01/2011 11:25:41 by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Encontros generated by hbm2java
 */
@Entity
@Table(name = "encontros", catalog = "wwwpais_sistema")
public class Encontros implements java.io.Serializable {

	private Integer encCod;
	private String encDescricao;
	private Set<Discipulos> discipuloses = new HashSet<Discipulos>(0);

	public Encontros() {
	}

	public Encontros(String encDescricao) {
		this.encDescricao = encDescricao;
	}

	public Encontros(String encDescricao, Set<Discipulos> discipuloses) {
		this.encDescricao = encDescricao;
		this.discipuloses = discipuloses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "EncCod", unique = true, nullable = false)
	public Integer getEncCod() {
		return this.encCod;
	}

	public void setEncCod(Integer encCod) {
		this.encCod = encCod;
	}

	@Column(name = "EncDescricao", nullable = false)
	public String getEncDescricao() {
		return this.encDescricao;
	}

	public void setEncDescricao(String encDescricao) {
		this.encDescricao = encDescricao;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "encontroses")
	public Set<Discipulos> getDiscipuloses() {
		return this.discipuloses;
	}

	public void setDiscipuloses(Set<Discipulos> discipuloses) {
		this.discipuloses = discipuloses;
	}

}
