package br.com.pais.entities;

// Generated 13/09/2010 13:58:41 by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estado generated by hbm2java
 */
@Entity
@Table(name = "estado", catalog = "wwwpais_sistema")
public class Estado implements java.io.Serializable {

	private String ufeSg;
	private String ufeNo;
	private Set<Localidade> localidades = new HashSet<Localidade>(0);

	public Estado() {
	}

	public Estado(String ufeSg, String ufeNo) {
		this.ufeSg = ufeSg;
		this.ufeNo = ufeNo;
	}

	public Estado(String ufeSg, String ufeNo, Set<Localidade> localidades) {
		this.ufeSg = ufeSg;
		this.ufeNo = ufeNo;
		this.localidades = localidades;
	}

	@Id
	@Column(name = "UFE_SG", unique = true, nullable = false, length = 2)
	public String getUfeSg() {
		return this.ufeSg;
	}

	public void setUfeSg(String ufeSg) {
		this.ufeSg = ufeSg;
	}

	@Column(name = "UFE_NO", nullable = false, length = 72)
	public String getUfeNo() {
		return this.ufeNo;
	}

	public void setUfeNo(String ufeNo) {
		this.ufeNo = ufeNo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estado")
	public Set<Localidade> getLocalidades() {
		return this.localidades;
	}

	public void setLocalidades(Set<Localidade> localidades) {
		this.localidades = localidades;
	}

}
