package br.com.pais.entities;

// Generated 14/05/2010 14:52:28 by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estado generated by hbm2java
 */
@Entity
@Table(name = "estado")
public class Estado implements java.io.Serializable {

	@Id
	@Column(name = "UFE_SG", unique = true, nullable = false, length = 2)
	private String ufeSg;
	
	@Column(name = "UFE_NO", nullable = false, length = 72)	
	private String ufeNo;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estado")
	private Set<Localidade> localidades = new HashSet<Localidade>(0);

	/**
	 * @return the ufeSg
	 */
	public String getUfeSg() {
		return ufeSg;
	}

	/**
	 * @param ufeSg the ufeSg to set
	 */
	public void setUfeSg(String ufeSg) {
		this.ufeSg = ufeSg;
	}

	/**
	 * @return the ufeNo
	 */
	public String getUfeNo() {
		return ufeNo;
	}

	/**
	 * @param ufeNo the ufeNo to set
	 */
	public void setUfeNo(String ufeNo) {
		this.ufeNo = ufeNo;
	}

	/**
	 * @return the localidades
	 */
	public Set<Localidade> getLocalidades() {
		return localidades;
	}

	/**
	 * @param localidades the localidades to set
	 */
	public void setLocalidades(Set<Localidade> localidades) {
		this.localidades = localidades;
	}

	
}
