package br.com.pais.entities;

// Generated 12/09/2010 22:48:01 by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Formacaoacademica generated by hbm2java
 */
@Entity
@Table(name = "formacaoacademica", catalog = "wwwpais_sistema", uniqueConstraints = @UniqueConstraint(columnNames = "ForDescricao"))
public class Formacaoacademica implements java.io.Serializable {

	private Integer forCod;
	private String forDescricao;
	private Set<Discipulos> discipuloses = new HashSet<Discipulos>(0);

	public Formacaoacademica() {
	}

	public Formacaoacademica(String forDescricao) {
		this.forDescricao = forDescricao;
	}

	public Formacaoacademica(String forDescricao, Set<Discipulos> discipuloses) {
		this.forDescricao = forDescricao;
		this.discipuloses = discipuloses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ForCod", unique = true, nullable = false)
	public Integer getForCod() {
		return this.forCod;
	}

	public void setForCod(Integer forCod) {
		this.forCod = forCod;
	}

	@Column(name = "ForDescricao", unique = true, nullable = false, length = 60)
	public String getForDescricao() {
		return this.forDescricao;
	}

	public void setForDescricao(String forDescricao) {
		this.forDescricao = forDescricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "formacaoacademica")
	public Set<Discipulos> getDiscipuloses() {
		return this.discipuloses;
	}

	public void setDiscipuloses(Set<Discipulos> discipuloses) {
		this.discipuloses = discipuloses;
	}

}
