package br.com.pais.entities;

// Generated 06/01/2011 15:01:09 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FotosbasesId generated by hbm2java
 */
@Embeddable
public class FotosbasesId implements java.io.Serializable {

	private int basCod;
	private String foto;

	public FotosbasesId() {
	}

	public FotosbasesId(int basCod, String foto) {
		this.basCod = basCod;
		this.foto = foto;
	}

	@Column(name = "basCod", nullable = false)
	public int getBasCod() {
		return this.basCod;
	}

	public void setBasCod(int basCod) {
		this.basCod = basCod;
	}

	@Column(name = "foto", nullable = false, length = 100)
	public String getFoto() {
		return this.foto;
	}

	public void setFoto(String foto) {
		this.foto = foto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FotosbasesId))
			return false;
		FotosbasesId castOther = (FotosbasesId) other;

		return (this.getBasCod() == castOther.getBasCod())
				&& ((this.getFoto() == castOther.getFoto()) || (this.getFoto() != null
						&& castOther.getFoto() != null && this.getFoto()
						.equals(castOther.getFoto())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getBasCod();
		result = 37 * result
				+ (getFoto() == null ? 0 : this.getFoto().hashCode());
		return result;
	}

}
