package br.com.pais.entities;

// Generated 06/01/2011 15:01:09 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Fotosbases generated by hbm2java
 */
@Entity
@Table(name = "fotosbases", catalog = "wwwpais_sistema")
public class Fotosbases implements java.io.Serializable {

	private FotosbasesId id;
	private Bases bases;

	public Fotosbases() {
	}

	public Fotosbases(FotosbasesId id, Bases bases) {
		this.id = id;
		this.bases = bases;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "basCod", column = @Column(name = "basCod", nullable = false)),
			@AttributeOverride(name = "foto", column = @Column(name = "foto", nullable = false, length = 100)) })
	public FotosbasesId getId() {
		return this.id;
	}

	public void setId(FotosbasesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "basCod", nullable = false, insertable = false, updatable = false)
	public Bases getBases() {
		return this.bases;
	}

	public void setBases(Bases bases) {
		this.bases = bases;
	}

}
