package br.com.pais.entities;

// Generated 12/09/2010 22:48:01 by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Funcaoeclesiasticas generated by hbm2java
 */
@Entity
@Table(name = "funcaoeclesiasticas", catalog = "wwwpais_sistema", uniqueConstraints = @UniqueConstraint(columnNames = "funDescricao"))
public class Funcaoeclesiasticas implements java.io.Serializable {

	private int funCod;
	private String funDescricao;
	private Set<Funeclesiasticasdiscipulos> funeclesiasticasdiscipuloses = new HashSet<Funeclesiasticasdiscipulos>(
			0);

	public Funcaoeclesiasticas() {
	}

	public Funcaoeclesiasticas(int funCod) {
		this.funCod = funCod;
	}

	public Funcaoeclesiasticas(int funCod, String funDescricao,
			Set<Funeclesiasticasdiscipulos> funeclesiasticasdiscipuloses) {
		this.funCod = funCod;
		this.funDescricao = funDescricao;
		this.funeclesiasticasdiscipuloses = funeclesiasticasdiscipuloses;
	}

	@Id
	@Column(name = "funCod", unique = true, nullable = false)
	public int getFunCod() {
		return this.funCod;
	}

	public void setFunCod(int funCod) {
		this.funCod = funCod;
	}

	@Column(name = "funDescricao", unique = true, length = 60)
	public String getFunDescricao() {
		return this.funDescricao;
	}

	public void setFunDescricao(String funDescricao) {
		this.funDescricao = funDescricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "funcaoeclesiasticas")
	public Set<Funeclesiasticasdiscipulos> getFuneclesiasticasdiscipuloses() {
		return this.funeclesiasticasdiscipuloses;
	}

	public void setFuneclesiasticasdiscipuloses(
			Set<Funeclesiasticasdiscipulos> funeclesiasticasdiscipuloses) {
		this.funeclesiasticasdiscipuloses = funeclesiasticasdiscipuloses;
	}

}
