package br.com.pais.entities;

// Generated 12/09/2010 22:48:01 by Hibernate Tools 3.3.0.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Funeclesiasticasdiscipulos generated by hbm2java
 */
@Entity
@Table(name = "funeclesiasticasdiscipulos", catalog = "wwwpais_sistema")
public class Funeclesiasticasdiscipulos implements java.io.Serializable {

	private FuneclesiasticasdiscipulosId id;
	private Funcaoeclesiasticas funcaoeclesiasticas;
	private Discipulos discipulos;
	private Date fundisData;
	private Set<Bases> baseses = new HashSet<Bases>(0);
	private Set<Celulas> celulases = new HashSet<Celulas>(0);

	public Funeclesiasticasdiscipulos() {
	}

	public Funeclesiasticasdiscipulos(FuneclesiasticasdiscipulosId id,
			Funcaoeclesiasticas funcaoeclesiasticas, Discipulos discipulos,
			Date fundisData) {
		this.id = id;
		this.funcaoeclesiasticas = funcaoeclesiasticas;
		this.discipulos = discipulos;
		this.fundisData = fundisData;
	}

	public Funeclesiasticasdiscipulos(FuneclesiasticasdiscipulosId id,
			Funcaoeclesiasticas funcaoeclesiasticas, Discipulos discipulos,
			Date fundisData, Set<Bases> baseses, Set<Celulas> celulases) {
		this.id = id;
		this.funcaoeclesiasticas = funcaoeclesiasticas;
		this.discipulos = discipulos;
		this.fundisData = fundisData;
		this.baseses = baseses;
		this.celulases = celulases;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "funCod", column = @Column(name = "funCod", nullable = false)),
			@AttributeOverride(name = "disCod", column = @Column(name = "disCod", nullable = false)) })
	public FuneclesiasticasdiscipulosId getId() {
		return this.id;
	}

	public void setId(FuneclesiasticasdiscipulosId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "funCod", nullable = false, insertable = false, updatable = false)
	public Funcaoeclesiasticas getFuncaoeclesiasticas() {
		return this.funcaoeclesiasticas;
	}

	public void setFuncaoeclesiasticas(Funcaoeclesiasticas funcaoeclesiasticas) {
		this.funcaoeclesiasticas = funcaoeclesiasticas;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "disCod", nullable = false, insertable = false, updatable = false)
	public Discipulos getDiscipulos() {
		return this.discipulos;
	}

	public void setDiscipulos(Discipulos discipulos) {
		this.discipulos = discipulos;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fundisData", nullable = false, length = 10)
	public Date getFundisData() {
		return this.fundisData;
	}

	public void setFundisData(Date fundisData) {
		this.fundisData = fundisData;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "funeclesiasticasdiscipulos")
	public Set<Bases> getBaseses() {
		return this.baseses;
	}

	public void setBaseses(Set<Bases> baseses) {
		this.baseses = baseses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "funeclesiasticasdiscipulos")
	public Set<Celulas> getCelulases() {
		return this.celulases;
	}

	public void setCelulases(Set<Celulas> celulases) {
		this.celulases = celulases;
	}

}
