package br.com.pais.entities;

// Generated 14/05/2010 14:52:28 by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FuneclesiasticasdiscipulosId generated by hbm2java
 */
@Embeddable
public class FuneclesiasticasdiscipulosId implements java.io.Serializable {

	@Column(name = "funCod", nullable = false)
	private int funCod;
	
	@Column(name = "disCod", nullable = false)
	private int disCod;

	


	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FuneclesiasticasdiscipulosId))
			return false;
		FuneclesiasticasdiscipulosId castOther = (FuneclesiasticasdiscipulosId) other;

		return (this.getFunCod() == castOther.getFunCod())
				&& (this.getDisCod() == castOther.getDisCod());
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getFunCod();
		result = 37 * result + this.getDisCod();
		return result;
	}

	/**
	 * @return the funCod
	 */
	public int getFunCod() {
		return funCod;
	}

	/**
	 * @param funCod the funCod to set
	 */
	public void setFunCod(int funCod) {
		this.funCod = funCod;
	}

	/**
	 * @return the disCod
	 */
	public int getDisCod() {
		return disCod;
	}

	/**
	 * @param disCod the disCod to set
	 */
	public void setDisCod(int disCod) {
		this.disCod = disCod;
	}

}
