package br.com.pais.entities;

// Generated 14/05/2010 14:52:28 by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Logradouro generated by hbm2java
 */
@Entity
@Table(name = "logradouro")
public class Logradouro implements java.io.Serializable {

	@Id
	@Column(name = "LOG_NUM_SEQUENCIAL", unique = true, nullable = false)
	private int logNumSequencial;
	
 	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BAI_NU_SEQUENCIAL_INI", nullable = false)
	private Bairro bairro;
 	
 	@Column(name = "UFE_SG", nullable = false, length = 2)
 	private String ufeSg;
 	
	@Column(name = "LOC_NU_SEQUENCIAL", nullable = false) 	
	private int locNuSequencial;
	
	@Column(name = "LOG_No", nullable = false, length = 70)
	private String logNo;
	
	@Column(name = "LOG_Nome", nullable = false, length = 125)
	private String logNome;
	
	@Column(name = "LOG_Complemento", length = 100)
	private String logComplemento;
	
	@Column(name = "LOG_Tipo_Logradouro", nullable = false, length = 72)
	private String logTipoLogradouro;
	
	@Column(name = "CEP2", nullable = false, length = 8)
	private String cep2;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "logradouro")
	private Set<Celulas> celulases = new HashSet<Celulas>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "logradouro")
	private Set<Discipulos> discipuloses = new HashSet<Discipulos>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "logradouro")
	private Set<Encontros> encontroses = new HashSet<Encontros>(0);

	/**
	 * @return the logNumSequencial
	 */
	public int getLogNumSequencial() {
		return logNumSequencial;
	}

	/**
	 * @param logNumSequencial the logNumSequencial to set
	 */
	public void setLogNumSequencial(int logNumSequencial) {
		this.logNumSequencial = logNumSequencial;
	}

	/**
	 * @return the bairro
	 */
	public Bairro getBairro() {
		return bairro;
	}

	/**
	 * @param bairro the bairro to set
	 */
	public void setBairro(Bairro bairro) {
		this.bairro = bairro;
	}

	/**
	 * @return the ufeSg
	 */
	public String getUfeSg() {
		return ufeSg;
	}

	/**
	 * @param ufeSg the ufeSg to set
	 */
	public void setUfeSg(String ufeSg) {
		this.ufeSg = ufeSg;
	}

	/**
	 * @return the locNuSequencial
	 */
	public int getLocNuSequencial() {
		return locNuSequencial;
	}

	/**
	 * @param locNuSequencial the locNuSequencial to set
	 */
	public void setLocNuSequencial(int locNuSequencial) {
		this.locNuSequencial = locNuSequencial;
	}

	/**
	 * @return the logNo
	 */
	public String getLogNo() {
		return logNo;
	}

	/**
	 * @param logNo the logNo to set
	 */
	public void setLogNo(String logNo) {
		this.logNo = logNo;
	}

	/**
	 * @return the logNome
	 */
	public String getLogNome() {
		return logNome;
	}

	/**
	 * @param logNome the logNome to set
	 */
	public void setLogNome(String logNome) {
		this.logNome = logNome;
	}

	/**
	 * @return the logComplemento
	 */
	public String getLogComplemento() {
		return logComplemento;
	}

	/**
	 * @param logComplemento the logComplemento to set
	 */
	public void setLogComplemento(String logComplemento) {
		this.logComplemento = logComplemento;
	}

	/**
	 * @return the logTipoLogradouro
	 */
	public String getLogTipoLogradouro() {
		return logTipoLogradouro;
	}

	/**
	 * @param logTipoLogradouro the logTipoLogradouro to set
	 */
	public void setLogTipoLogradouro(String logTipoLogradouro) {
		this.logTipoLogradouro = logTipoLogradouro;
	}

	/**
	 * @return the cep2
	 */
	public String getCep2() {
		return cep2;
	}

	/**
	 * @param cep2 the cep2 to set
	 */
	public void setCep2(String cep2) {
		this.cep2 = cep2;
	}

	/**
	 * @return the celulases
	 */
	public Set<Celulas> getCelulases() {
		return celulases;
	}

	/**
	 * @param celulases the celulases to set
	 */
	public void setCelulases(Set<Celulas> celulases) {
		this.celulases = celulases;
	}

	/**
	 * @return the discipuloses
	 */
	public Set<Discipulos> getDiscipuloses() {
		return discipuloses;
	}

	/**
	 * @param discipuloses the discipuloses to set
	 */
	public void setDiscipuloses(Set<Discipulos> discipuloses) {
		this.discipuloses = discipuloses;
	}

	/**
	 * @return the encontroses
	 */
	public Set<Encontros> getEncontroses() {
		return encontroses;
	}

	/**
	 * @param encontroses the encontroses to set
	 */
	public void setEncontroses(Set<Encontros> encontroses) {
		this.encontroses = encontroses;
	}


}
