package br.com.pais.entities;

// Generated 25/01/2011 16:14:58 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mensagem generated by hbm2java
 */
@Entity
@Table(name = "mensagem", catalog = "wwwpais_sistema")
public class Mensagem implements java.io.Serializable {

	private Integer mensCod;
	private Discipulos discipulosByMensDisCodRecebe;
	private Discipulos discipulosByMensDisCod;
	private String mensTexto;
	private Date mensData;
	private char mensLida;
	private char mensCaixa;
	private Set<Mensagemanexos> mensagemanexoses = new HashSet<Mensagemanexos>(
			0);

	public Mensagem() {
	}

	public Mensagem(Discipulos discipulosByMensDisCodRecebe,
			Discipulos discipulosByMensDisCod, String mensTexto, Date mensData,
			char mensLida) {
		this.discipulosByMensDisCodRecebe = discipulosByMensDisCodRecebe;
		this.discipulosByMensDisCod = discipulosByMensDisCod;
		this.mensTexto = mensTexto;
		this.mensData = mensData;
		this.mensLida = mensLida;
	}

	public Mensagem(Discipulos discipulosByMensDisCodRecebe,
			Discipulos discipulosByMensDisCod, String mensTexto, Date mensData,
			char mensLida, Set<Mensagemanexos> mensagemanexoses) {
		this.discipulosByMensDisCodRecebe = discipulosByMensDisCodRecebe;
		this.discipulosByMensDisCod = discipulosByMensDisCod;
		this.mensTexto = mensTexto;
		this.mensData = mensData;
		this.mensLida = mensLida;
		this.mensagemanexoses = mensagemanexoses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "mensCod", unique = true, nullable = false)
	public Integer getMensCod() {
		return this.mensCod;
	}

	public void setMensCod(Integer mensCod) {
		this.mensCod = mensCod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mensDisCodRecebe", nullable = false)
	public Discipulos getDiscipulosByMensDisCodRecebe() {
		return this.discipulosByMensDisCodRecebe;
	}

	public void setDiscipulosByMensDisCodRecebe(
			Discipulos discipulosByMensDisCodRecebe) {
		this.discipulosByMensDisCodRecebe = discipulosByMensDisCodRecebe;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mensDisCod", nullable = false)
	public Discipulos getDiscipulosByMensDisCod() {
		return this.discipulosByMensDisCod;
	}

	public void setDiscipulosByMensDisCod(Discipulos discipulosByMensDisCod) {
		this.discipulosByMensDisCod = discipulosByMensDisCod;
	}

	@Column(name = "mensTexto", nullable = false)
	public String getMensTexto() {
		return this.mensTexto;
	}

	public void setMensTexto(String mensTexto) {
		this.mensTexto = mensTexto;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "mensData", nullable = false, length = 10)
	public Date getMensData() {
		return this.mensData;
	}

	public void setMensData(Date mensData) {
		this.mensData = mensData;
	}

	@Column(name = "mensLida", nullable = false, length = 1)
	public char getMensLida() {
		return this.mensLida;
	}

	public void setMensLida(char mensLida) {
		this.mensLida = mensLida;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mensagem")
	public Set<Mensagemanexos> getMensagemanexoses() {
		return this.mensagemanexoses;
	}

	public void setMensagemanexoses(Set<Mensagemanexos> mensagemanexoses) {
		this.mensagemanexoses = mensagemanexoses;
	}

	/**
	 * @return the mensCaixa
	 */
	@Column(name = "mensCaixa", length = 1)
	public char getMensCaixa() {
		return mensCaixa;
	}

	/**
	 * @param mensCaixa the mensCaixa to set
	 */
	public void setMensCaixa(char mensCaixa) {
		this.mensCaixa = mensCaixa;
	}

}
