package br.com.pais.entities;

// Generated 12/09/2010 22:48:01 by Hibernate Tools 3.3.0.GA

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Participa generated by hbm2java
 */
@Entity
@Table(name = "participa", catalog = "wwwpais_sistema")
public class Participa implements java.io.Serializable {

	private ParticipaId id;
	private Discipulos discipulos;
	private Encontros encontros;
	private Date parDate;

	public Participa() {
	}

	public Participa(ParticipaId id, Discipulos discipulos,
			Encontros encontros, Date parDate) {
		this.id = id;
		this.discipulos = discipulos;
		this.encontros = encontros;
		this.parDate = parDate;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "disCod", column = @Column(name = "disCod", nullable = false)),
			@AttributeOverride(name = "encCod", column = @Column(name = "EncCod", nullable = false)) })
	public ParticipaId getId() {
		return this.id;
	}

	public void setId(ParticipaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "disCod", nullable = false, insertable = false, updatable = false)
	public Discipulos getDiscipulos() {
		return this.discipulos;
	}

	public void setDiscipulos(Discipulos discipulos) {
		this.discipulos = discipulos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EncCod", nullable = false, insertable = false, updatable = false)
	public Encontros getEncontros() {
		return this.encontros;
	}

	public void setEncontros(Encontros encontros) {
		this.encontros = encontros;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "parDate", nullable = false, length = 10)
	public Date getParDate() {
		return this.parDate;
	}

	public void setParDate(Date parDate) {
		this.parDate = parDate;
	}

}
