package br.com.pais.entities;

// Generated 06/01/2011 15:01:09 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RepasseId generated by hbm2java
 */
@Embeddable
public class RepasseId implements java.io.Serializable {

	private int movCod;
	private int disCod;

	public RepasseId() {
	}

	public RepasseId(int movCod, int disCod) {
		this.movCod = movCod;
		this.disCod = disCod;
	}

	@Column(name = "movCod", nullable = false)
	public int getMovCod() {
		return this.movCod;
	}

	public void setMovCod(int movCod) {
		this.movCod = movCod;
	}

	@Column(name = "disCod", nullable = false)
	public int getDisCod() {
		return this.disCod;
	}

	public void setDisCod(int disCod) {
		this.disCod = disCod;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RepasseId))
			return false;
		RepasseId castOther = (RepasseId) other;

		return (this.getMovCod() == castOther.getMovCod())
				&& (this.getDisCod() == castOther.getDisCod());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMovCod();
		result = 37 * result + this.getDisCod();
		return result;
	}

}
