package br.com.pais.entities;

// Generated 13/09/2010 13:58:41 by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Telcelulas generated by hbm2java
 */
@Entity
@Table(name = "telcelulas", catalog = "wwwpais_sistema")
public class Telcelulas implements java.io.Serializable {

	private Integer telCelCod;
	private Celulas celulas;
	private String telCelDescricao;
	private String telCelNumero;

	public Telcelulas() {
	}

	public Telcelulas(Celulas celulas, String telCelDescricao,
			String telCelNumero) {
		this.celulas = celulas;
		this.telCelDescricao = telCelDescricao;
		this.telCelNumero = telCelNumero;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "telCelCod", unique = true, nullable = false)
	public Integer getTelCelCod() {
		return this.telCelCod;
	}

	public void setTelCelCod(Integer telCelCod) {
		this.telCelCod = telCelCod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "celCod", nullable = false)
	public Celulas getCelulas() {
		return this.celulas;
	}

	public void setCelulas(Celulas celulas) {
		this.celulas = celulas;
	}

	@Column(name = "telCelDescricao", nullable = false, length = 15)
	public String getTelCelDescricao() {
		return this.telCelDescricao;
	}

	public void setTelCelDescricao(String telCelDescricao) {
		this.telCelDescricao = telCelDescricao;
	}

	@Column(name = "telCelNumero", nullable = false, length = 15)
	public String getTelCelNumero() {
		return this.telCelNumero;
	}

	public void setTelCelNumero(String telCelNumero) {
		this.telCelNumero = telCelNumero;
	}

}
