package br.com.pais.entities;

// Generated 14/05/2010 14:52:28 by Hibernate Tools 3.3.0.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Telcelulas generated by hbm2java
 */
@Entity
@Table(name = "telcelulas", catalog = "wwwpais_pais")
public class Telcelulas implements java.io.Serializable {

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "telNumero", column = @Column(name = "telNumero", nullable = false)),
			@AttributeOverride(name = "celCod", column = @Column(name = "celCod", nullable = false)),
			@AttributeOverride(name = "funCod", column = @Column(name = "funCod", nullable = false)),
			@AttributeOverride(name = "disCod", column = @Column(name = "disCod", nullable = false)) })
	private TelcelulasId id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
			@JoinColumn(name = "celCod", referencedColumnName = "celCod", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "funCod", referencedColumnName = "funCod", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "disCod", referencedColumnName = "disCod", nullable = false, insertable = false, updatable = false) })
	private Celulas celulas;

	@Column(name = "telTipo", nullable = false, length = 30)
	private String telTipo;

	/**
	 * @return the id
	 */
	public TelcelulasId getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(TelcelulasId id) {
		this.id = id;
	}

	/**
	 * @return the celulas
	 */
	public Celulas getCelulas() {
		return celulas;
	}

	/**
	 * @param celulas the celulas to set
	 */
	public void setCelulas(Celulas celulas) {
		this.celulas = celulas;
	}

	/**
	 * @return the telTipo
	 */
	public String getTelTipo() {
		return telTipo;
	}

	/**
	 * @param telTipo the telTipo to set
	 */
	public void setTelTipo(String telTipo) {
		this.telTipo = telTipo;
	}

}
