package br.com.pais.entities;

// Generated 06/05/2011 15:49:37 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MensagemanexosId generated by hbm2java
 */
@Embeddable
public class MensagemanexosId implements java.io.Serializable {

	private int mensagemCod;
	private String mensagemarquivo;

	public MensagemanexosId() {
	}

	public MensagemanexosId(int mensagemCod) {
		this.mensagemCod = mensagemCod;
	}

	public MensagemanexosId(int mensagemCod, String mensagemarquivo) {
		this.mensagemCod = mensagemCod;
		this.mensagemarquivo = mensagemarquivo;
	}

	@Column(name = "mensagemCod", nullable = false)
	public int getMensagemCod() {
		return this.mensagemCod;
	}

	public void setMensagemCod(int mensagemCod) {
		this.mensagemCod = mensagemCod;
	}

	@Column(name = "mensagemarquivo")
	public String getMensagemarquivo() {
		return this.mensagemarquivo;
	}

	public void setMensagemarquivo(String mensagemarquivo) {
		this.mensagemarquivo = mensagemarquivo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MensagemanexosId))
			return false;
		MensagemanexosId castOther = (MensagemanexosId) other;

		return (this.getMensagemCod() == castOther.getMensagemCod())
				&& ((this.getMensagemarquivo() == castOther
						.getMensagemarquivo()) || (this.getMensagemarquivo() != null
						&& castOther.getMensagemarquivo() != null && this
						.getMensagemarquivo().equals(
								castOther.getMensagemarquivo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMensagemCod();
		result = 37
				* result
				+ (getMensagemarquivo() == null ? 0 : this.getMensagemarquivo()
						.hashCode());
		return result;
	}

}
