package br.com.pais.domain;

// Generated 27/04/2010 23:53:17 by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.springframework.stereotype.Repository;

/**
 * Bairro generated by hbm2java
 */

@Entity
@Table(name = "tbl_bairro", catalog = "pais")
public class Bairro implements java.io.Serializable {

	private int baiCod;
	private Localidade localidade;
	private String baiUfeSg;
	private int bailocCod;
	private String baiNo;
	private String baiNoAbrev;
	private Set<Logradouro> logradouros = new HashSet<Logradouro>(0);

	public Bairro() {
	}

	public Bairro(int baiCod, Localidade localidade, String baiUfeSg,
			int bailocCod, String baiNo) {
		this.baiCod = baiCod;
		this.localidade = localidade;
		this.baiUfeSg = baiUfeSg;
		this.bailocCod = bailocCod;
		this.baiNo = baiNo;
	}

	public Bairro(int baiCod, Localidade localidade, String baiUfeSg,
			int bailocCod, String baiNo, String baiNoAbrev,
			Set<Logradouro> logradouros) {
		this.baiCod = baiCod;
		this.localidade = localidade;
		this.baiUfeSg = baiUfeSg;
		this.bailocCod = bailocCod;
		this.baiNo = baiNo;
		this.baiNoAbrev = baiNoAbrev;
		this.logradouros = logradouros;
	}

	@Id
	@Column(name = "baiCod", unique = true, nullable = false)
	public int getBaiCod() {
		return this.baiCod;
	}

	public void setBaiCod(int baiCod) {
		this.baiCod = baiCod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tbl_localidade_locCod", nullable = false)
	public Localidade getTblLocalidade() {
		return this.localidade;
	}

	public void setTblLocalidade(Localidade localidade) {
		this.localidade = localidade;
	}

	@Column(name = "baiUfeSg", nullable = false, length = 2)
	public String getBaiUfeSg() {
		return this.baiUfeSg;
	}

	public void setBaiUfeSg(String baiUfeSg) {
		this.baiUfeSg = baiUfeSg;
	}

	@Column(name = "bailocCod", nullable = false)
	public int getBailocCod() {
		return this.bailocCod;
	}

	public void setBailocCod(int bailocCod) {
		this.bailocCod = bailocCod;
	}

	@Column(name = "baiNo", nullable = false, length = 72)
	public String getBaiNo() {
		return this.baiNo;
	}

	public void setBaiNo(String baiNo) {
		this.baiNo = baiNo;
	}

	@Column(name = "baiNoAbrev", length = 36)
	public String getBaiNoAbrev() {
		return this.baiNoAbrev;
	}

	public void setBaiNoAbrev(String baiNoAbrev) {
		this.baiNoAbrev = baiNoAbrev;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblBairro")
	public Set<Logradouro> getTblLogradouros() {
		return this.logradouros;
	}

	public void setTblLogradouros(Set<Logradouro> logradouros) {
		this.logradouros = logradouros;
	}

}
