package br.com.pais.domain;

// Generated 27/04/2010 23:53:17 by Hibernate Tools 3.3.0.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Encontros generated by hbm2java
 */
@Entity
@Table(name = "tbl_Encontros", catalog = "pais")
public class Encontros implements java.io.Serializable {

	private int encCod;
	private Logradouro logradouro;
	private Date encDataRealizacao;
	private String encDescricao;
	private Set<Discipulos> tblDiscipuloses = new HashSet<Discipulos>(0);

	public Encontros() {
	}

	public Encontros(int encCod, Logradouro logradouro) {
		this.encCod = encCod;
		this.logradouro = logradouro;
	}

	public Encontros(int encCod, Logradouro logradouro,
			Date encDataRealizacao, String encDescricao,
			Set<Discipulos> tblDiscipuloses) {
		this.encCod = encCod;
		this.logradouro = logradouro;
		this.encDataRealizacao = encDataRealizacao;
		this.encDescricao = encDescricao;
		this.tblDiscipuloses = tblDiscipuloses;
	}

	@Id
	@Column(name = "EncCod", unique = true, nullable = false)
	public int getEncCod() {
		return this.encCod;
	}

	public void setEncCod(int encCod) {
		this.encCod = encCod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EncLocal", nullable = false)
	public Logradouro getTblLogradouro() {
		return this.logradouro;
	}

	public void setTblLogradouro(Logradouro logradouro) {
		this.logradouro = logradouro;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EncDataRealizacao", length = 10)
	public Date getEncDataRealizacao() {
		return this.encDataRealizacao;
	}

	public void setEncDataRealizacao(Date encDataRealizacao) {
		this.encDataRealizacao = encDataRealizacao;
	}

	@Column(name = "EncDescricao")
	public String getEncDescricao() {
		return this.encDescricao;
	}

	public void setEncDescricao(String encDescricao) {
		this.encDescricao = encDescricao;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "tblEncontroses")
	public Set<Discipulos> getTblDiscipuloses() {
		return this.tblDiscipuloses;
	}

	public void setTblDiscipuloses(Set<Discipulos> tblDiscipuloses) {
		this.tblDiscipuloses = tblDiscipuloses;
	}

}
