package br.com.pais.domain;

// Generated 27/04/2010 23:53:17 by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * EstadoCivil generated by hbm2java
 */
@Entity
@Table(name = "tbl_EstadoCivil", catalog = "pais", uniqueConstraints = @UniqueConstraint(columnNames = "Estdescricao"))
public class EstadoCivil implements java.io.Serializable {

	private Integer estCod;
	private String estdescricao;
	private Set<Discipulos> tblDiscipuloses = new HashSet<Discipulos>(0);

	public EstadoCivil() {
	}

	public EstadoCivil(String estdescricao,
			Set<Discipulos> tblDiscipuloses) {
		this.estdescricao = estdescricao;
		this.tblDiscipuloses = tblDiscipuloses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "EstCod", unique = true, nullable = false)
	public Integer getEstCod() {
		return this.estCod;
	}

	public void setEstCod(Integer estCod) {
		this.estCod = estCod;
	}

	@Column(name = "Estdescricao", unique = true, length = 60)
	public String getEstdescricao() {
		return this.estdescricao;
	}

	public void setEstdescricao(String estdescricao) {
		this.estdescricao = estdescricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblEstadoCivil")
	public Set<Discipulos> getTblDiscipuloses() {
		return this.tblDiscipuloses;
	}

	public void setTblDiscipuloses(Set<Discipulos> tblDiscipuloses) {
		this.tblDiscipuloses = tblDiscipuloses;
	}

}
