package br.com.pais.domain;

// Generated 27/04/2010 23:53:17 by Hibernate Tools 3.3.0.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FunEclesiasticasDiscipulos generated by hbm2java
 */
@Entity
@Table(name = "tbl_FunEclesiasticasDiscipulos", catalog = "pais")
public class FunEclesiasticasDiscipulos implements java.io.Serializable {

	private FunEclesiasticasDiscipulosId id;
	private FuncaoEclesiasticas funcaoEclesiasticas;
	private Discipulos discipulos;
	private Date fundisData;
	private Set<Celulas> tblCelulases = new HashSet<Celulas>(0);

	public FunEclesiasticasDiscipulos() {
	}

	public FunEclesiasticasDiscipulos(FunEclesiasticasDiscipulosId id,
			FuncaoEclesiasticas funcaoEclesiasticas,
			Discipulos discipulos, Date fundisData) {
		this.id = id;
		this.funcaoEclesiasticas = funcaoEclesiasticas;
		this.discipulos = discipulos;
		this.fundisData = fundisData;
	}

	public FunEclesiasticasDiscipulos(FunEclesiasticasDiscipulosId id,
			FuncaoEclesiasticas funcaoEclesiasticas,
			Discipulos discipulos, Date fundisData,
			Set<Celulas> tblCelulases) {
		this.id = id;
		this.funcaoEclesiasticas = funcaoEclesiasticas;
		this.discipulos = discipulos;
		this.fundisData = fundisData;
		this.tblCelulases = tblCelulases;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "funCod", column = @Column(name = "funCod", nullable = false)),
			@AttributeOverride(name = "disCod", column = @Column(name = "disCod", nullable = false)) })
	public FunEclesiasticasDiscipulosId getId() {
		return this.id;
	}

	public void setId(FunEclesiasticasDiscipulosId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "funCod", nullable = false, insertable = false, updatable = false)
	public FuncaoEclesiasticas getTblFuncaoEclesiasticas() {
		return this.funcaoEclesiasticas;
	}

	public void setTblFuncaoEclesiasticas(
			FuncaoEclesiasticas funcaoEclesiasticas) {
		this.funcaoEclesiasticas = funcaoEclesiasticas;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "disCod", nullable = false, insertable = false, updatable = false)
	public Discipulos getTblDiscipulos() {
		return this.discipulos;
	}

	public void setTblDiscipulos(Discipulos discipulos) {
		this.discipulos = discipulos;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fundisData", nullable = false, length = 10)
	public Date getFundisData() {
		return this.fundisData;
	}

	public void setFundisData(Date fundisData) {
		this.fundisData = fundisData;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblFunEclesiasticasDiscipulos")
	public Set<Celulas> getTblCelulases() {
		return this.tblCelulases;
	}

	public void setTblCelulases(Set<Celulas> tblCelulases) {
		this.tblCelulases = tblCelulases;
	}

}
