package br.com.pais.domain;

// Generated 27/04/2010 23:53:17 by Hibernate Tools 3.3.0.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TelCelulas generated by hbm2java
 */
@Entity
@Table(name = "tbl_TelCelulas", catalog = "pais")
public class TelCelulas implements java.io.Serializable {

	private TblTelCelulasId id;
	private Celulas celulas;
	private String telTipo;

	public TelCelulas() {
	}

	public TelCelulas(TblTelCelulasId id, Celulas celulas,
			String telTipo) {
		this.id = id;
		this.celulas = celulas;
		this.telTipo = telTipo;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "telNumero", column = @Column(name = "telNumero", nullable = false)),
			@AttributeOverride(name = "celCod", column = @Column(name = "celCod", nullable = false)),
			@AttributeOverride(name = "funCod", column = @Column(name = "funCod", nullable = false)),
			@AttributeOverride(name = "disCod", column = @Column(name = "disCod", nullable = false)) })
	public TblTelCelulasId getId() {
		return this.id;
	}

	public void setId(TblTelCelulasId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
			@JoinColumn(name = "celCod", referencedColumnName = "celCod", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "funCod", referencedColumnName = "funCod", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "disCod", referencedColumnName = "disCod", nullable = false, insertable = false, updatable = false) })
	public Celulas getTblCelulas() {
		return this.celulas;
	}

	public void setTblCelulas(Celulas celulas) {
		this.celulas = celulas;
	}

	@Column(name = "telTipo", nullable = false, length = 30)
	public String getTelTipo() {
		return this.telTipo;
	}

	public void setTelTipo(String telTipo) {
		this.telTipo = telTipo;
	}

}
