package br.com.pais.entities;

// Generated 13/09/2010 13:58:41 by Hibernate Tools 3.3.0.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Celulas generated by hbm2java
 */
@Entity
@Table(name = "celulas", catalog = "wwwpais_sistema")
public class Celulas implements java.io.Serializable {

	private Integer celCod;
	private Bases bases;
	private Logradouro logradouro;
	private Funeclesiasticasdiscipulos funeclesiasticasdiscipulos;
	private Date celHorarioReuniao;
	private Date celDiaReuniao;
	private String celNuEndereco;
	private String celEndComplemento;
	private Set<Telcelulas> telcelulases = new HashSet<Telcelulas>(0);
	private Set<Movimento> movimentos = new HashSet<Movimento>(0);

	public Celulas() {
	}

	public Celulas(Logradouro logradouro,
			Funeclesiasticasdiscipulos funeclesiasticasdiscipulos,
			String celNuEndereco) {
		this.logradouro = logradouro;
		this.funeclesiasticasdiscipulos = funeclesiasticasdiscipulos;
		this.celNuEndereco = celNuEndereco;
	}

	public Celulas(Bases bases, Logradouro logradouro,
			Funeclesiasticasdiscipulos funeclesiasticasdiscipulos,
			Date celHorarioReuniao, Date celDiaReuniao, String celNuEndereco,
			String celEndComplemento, Set<Telcelulas> telcelulases,
			Set<Movimento> movimentos) {
		this.bases = bases;
		this.logradouro = logradouro;
		this.funeclesiasticasdiscipulos = funeclesiasticasdiscipulos;
		this.celHorarioReuniao = celHorarioReuniao;
		this.celDiaReuniao = celDiaReuniao;
		this.celNuEndereco = celNuEndereco;
		this.celEndComplemento = celEndComplemento;
		this.telcelulases = telcelulases;
		this.movimentos = movimentos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "celCod", unique = true, nullable = false)
	public Integer getCelCod() {
		return this.celCod;
	}

	public void setCelCod(Integer celCod) {
		this.celCod = celCod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "basCod")
	public Bases getBases() {
		return this.bases;
	}

	public void setBases(Bases bases) {
		this.bases = bases;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "celEndereco", nullable = false)
	public Logradouro getLogradouro() {
		return this.logradouro;
	}

	public void setLogradouro(Logradouro logradouro) {
		this.logradouro = logradouro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "funCod", referencedColumnName = "funCod", nullable = false),
			@JoinColumn(name = "disCod", referencedColumnName = "disCod", nullable = false) })
	public Funeclesiasticasdiscipulos getFuneclesiasticasdiscipulos() {
		return this.funeclesiasticasdiscipulos;
	}

	public void setFuneclesiasticasdiscipulos(
			Funeclesiasticasdiscipulos funeclesiasticasdiscipulos) {
		this.funeclesiasticasdiscipulos = funeclesiasticasdiscipulos;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "celHorarioReuniao", length = 8)
	public Date getCelHorarioReuniao() {
		return this.celHorarioReuniao;
	}

	public void setCelHorarioReuniao(Date celHorarioReuniao) {
		this.celHorarioReuniao = celHorarioReuniao;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "celDiaReuniao", length = 10)
	public Date getCelDiaReuniao() {
		return this.celDiaReuniao;
	}

	public void setCelDiaReuniao(Date celDiaReuniao) {
		this.celDiaReuniao = celDiaReuniao;
	}

	@Column(name = "celNuEndereco", nullable = false, length = 5)
	public String getCelNuEndereco() {
		return this.celNuEndereco;
	}

	public void setCelNuEndereco(String celNuEndereco) {
		this.celNuEndereco = celNuEndereco;
	}

	@Column(name = "celEndComplemento", length = 45)
	public String getCelEndComplemento() {
		return this.celEndComplemento;
	}

	public void setCelEndComplemento(String celEndComplemento) {
		this.celEndComplemento = celEndComplemento;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "celulas")
	public Set<Telcelulas> getTelcelulases() {
		return this.telcelulases;
	}

	public void setTelcelulases(Set<Telcelulas> telcelulases) {
		this.telcelulases = telcelulases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "celulas")
	public Set<Movimento> getMovimentos() {
		return this.movimentos;
	}

	public void setMovimentos(Set<Movimento> movimentos) {
		this.movimentos = movimentos;
	}

}
