package br.com.pais.entities;

// Generated 14/05/2010 14:52:28 by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CelulasId generated by hbm2java
 */
@Embeddable
public class CelulasId implements java.io.Serializable {

	@Column(name = "celCod", nullable = false)
	private int celCod;
	
	@Column(name = "funCod", nullable = false)
	private int funCod;
	
	@Column(name = "disCod", nullable = false)
	private int disCod;



	public int getCelCod() {
		return this.celCod;
	}

	public void setCelCod(int celCod) {
		this.celCod = celCod;
	}

	
	public int getFunCod() {
		return this.funCod;
	}

	public void setFunCod(int funCod) {
		this.funCod = funCod;
	}

	
	public int getDisCod() {
		return this.disCod;
	}

	public void setDisCod(int disCod) {
		this.disCod = disCod;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CelulasId))
			return false;
		CelulasId castOther = (CelulasId) other;

		return (this.getCelCod() == castOther.getCelCod())
				&& (this.getFunCod() == castOther.getFunCod())
				&& (this.getDisCod() == castOther.getDisCod());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCelCod();
		result = 37 * result + this.getFunCod();
		result = 37 * result + this.getDisCod();
		return result;
	}

}
