package br.com.pais.entities;

// Generated 14/05/2010 14:52:28 by Hibernate Tools 3.3.0.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;



/**
 * Discipulos generated by hbm2java
 */
@Entity
@Table(name = "discipulos", catalog = "wwwpais_sistema")
@NamedQueries ({
@NamedQuery(name="Discipulo.findbyCPF", query = "FROM Discipulos AS d where d.disCPF = :cpf")})
public class Discipulos implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "disCod", unique = true, nullable = false)
	private Integer disCod;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "disEstCivil", nullable = false)
	private Estadocivil estadocivil;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "disdiscipulador", nullable = false)
	private Discipulos discipulos;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "disEndereço", nullable = false)
	private Logradouro logradouro;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "disGeracao", nullable = false)
	private Geracoes geracoes;
	
	@Column(name = "disfoto", length = 60)
	private String disfoto;
	
	@Column(name = "disemail", length = 60)
	private String disemail;
	
	@Column(name = "disnome", nullable = false, length = 60)
	private String disnome;
	
	@Column(name = "dispai", length = 60)
	private String dispai;
	
	@Column(name = "disconjuge", length = 60)	
	private String disconjuge;
	
	@Column(name = "dismae", nullable = false, length = 60)	
	private String dismae;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "disdatanascimento", nullable = false, length = 10)	
	private Date disdatanascimento;
	
	@Column(name = "dism12", nullable = false, length = 1)
	private char dism12;
	
	@Column(name = "disSenha", length = 23)
	private String disSenha;
	
	@Column(name = "disCPF", length = 14)
	private String disCPF;
	
	@Column(name = "disRG", length = 11)
	private String disRG;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "disDTEmissao")
	private Date disDTEmissao;
	
	@Column(name = "disTitEleitor", length = 11)
	private String disTitEleitor;
	
	@Column(name = "disZona", length = 4)
	private String disZona;
	
	@Column(name = "disSecao", length = 4)
	private String disSecao;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "discipulos")
	private Set<Repasse> repasses = new HashSet<Repasse>(0);
	
	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "foreclesiasticasdiscipulos", catalog = "wwwpais_pais", joinColumns = { @JoinColumn(name = "disCod", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "forCod", nullable = false, updatable = false) })
	private Set<Formacaoeclesiasticas> formacaoeclesiasticases = new HashSet<Formacaoeclesiasticas>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "discipulos")
	private Set<Discipulos> discipuloses = new HashSet<Discipulos>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "discipulos")
	private Set<Participa> participas = new HashSet<Participa>(0);
	
	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "foracademicadiscipulos", catalog = "wwwpais_pais", joinColumns = { @JoinColumn(name = "disCod", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "ForCod", nullable = false, updatable = false) })	
	private Set<Formacaoacademica> formacaoacademicas = new HashSet<Formacaoacademica>(0);
		
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "discipulos")
	private Set<Funeclesiasticasdiscipulos> funeclesiasticasdiscipuloses = new HashSet<Funeclesiasticasdiscipulos>(0);

	/**
	 * @return the disCod
	 */
	public Integer getDisCod() {
		return disCod;
	}

	/**
	 * @param disCod the disCod to set
	 */
	public void setDisCod(Integer disCod) {
		this.disCod = disCod;
	}

	/**
	 * @return the estadocivil
	 */
	public Estadocivil getEstadocivil() {
		return estadocivil;
	}

	/**
	 * @param estadocivil the estadocivil to set
	 */
	public void setEstadocivil(Estadocivil estadocivil) {
		this.estadocivil = estadocivil;
	}

	/**
	 * @return the discipulos
	 */
	public Discipulos getDiscipulos() {
		return discipulos;
	}

	/**
	 * @param discipulos the discipulos to set
	 */
	public void setDiscipulos(Discipulos discipulos) {
		this.discipulos = discipulos;
	}

	/**
	 * @return the logradouro
	 */
	public Logradouro getLogradouro() {
		return logradouro;
	}

	/**
	 * @param logradouro the logradouro to set
	 */
	public void setLogradouro(Logradouro logradouro) {
		this.logradouro = logradouro;
	}

	/**
	 * @return the geracoes
	 */
	public Geracoes getGeracoes() {
		return geracoes;
	}

	/**
	 * @param geracoes the geracoes to set
	 */
	public void setGeracoes(Geracoes geracoes) {
		this.geracoes = geracoes;
	}

	/**
	 * @return the disfoto
	 */
	public String getDisfoto() {
		return disfoto;
	}

	/**
	 * @param disfoto the disfoto to set
	 */
	public void setDisfoto(String disfoto) {
		this.disfoto = disfoto;
	}

	/**
	 * @return the disemail
	 */
	public String getDisemail() {
		return disemail;
	}

	/**
	 * @param disemail the disemail to set
	 */
	public void setDisemail(String disemail) {
		this.disemail = disemail;
	}

	/**
	 * @return the disnome
	 */
	public String getDisnome() {
		return disnome;
	}

	/**
	 * @param disnome the disnome to set
	 */
	public void setDisnome(String disnome) {
		this.disnome = disnome;
	}

	/**
	 * @return the dispai
	 */
	public String getDispai() {
		return dispai;
	}

	/**
	 * @param dispai the dispai to set
	 */
	public void setDispai(String dispai) {
		this.dispai = dispai;
	}

	/**
	 * @return the disconjuge
	 */
	public String getDisconjuge() {
		return disconjuge;
	}

	/**
	 * @param disconjuge the disconjuge to set
	 */
	public void setDisconjuge(String disconjuge) {
		this.disconjuge = disconjuge;
	}

	/**
	 * @return the dismae
	 */
	public String getDismae() {
		return dismae;
	}

	/**
	 * @param dismae the dismae to set
	 */
	public void setDismae(String dismae) {
		this.dismae = dismae;
	}

	/**
	 * @return the disdatanascimento
	 */
	public Date getDisdatanascimento() {
		return disdatanascimento;
	}

	/**
	 * @param disdatanascimento the disdatanascimento to set
	 */
	public void setDisdatanascimento(Date disdatanascimento) {
		this.disdatanascimento = disdatanascimento;
	}

	/**
	 * @return the dism12
	 */
	public char getDism12() {
		return dism12;
	}

	/**
	 * @param dism12 the dism12 to set
	 */
	public void setDism12(char dism12) {
		this.dism12 = dism12;
	}

	/**
	 * @return the disSenha
	 */
	public String getDisSenha() {
		return disSenha;
	}

	/**
	 * @param disSenha the disSenha to set
	 */
	public void setDisSenha(String disSenha) {
		this.disSenha = disSenha;
	}

	/**
	 * @return the repasses
	 */
	public Set<Repasse> getRepasses() {
		return repasses;
	}

	/**
	 * @param repasses the repasses to set
	 */
	public void setRepasses(Set<Repasse> repasses) {
		this.repasses = repasses;
	}

	/**
	 * @return the formacaoeclesiasticases
	 */
	public Set<Formacaoeclesiasticas> getFormacaoeclesiasticases() {
		return formacaoeclesiasticases;
	}

	/**
	 * @param formacaoeclesiasticases the formacaoeclesiasticases to set
	 */
	public void setFormacaoeclesiasticases(
			Set<Formacaoeclesiasticas> formacaoeclesiasticases) {
		this.formacaoeclesiasticases = formacaoeclesiasticases;
	}

	/**
	 * @return the discipuloses
	 */
	public Set<Discipulos> getDiscipuloses() {
		return discipuloses;
	}

	/**
	 * @param discipuloses the discipuloses to set
	 */
	public void setDiscipuloses(Set<Discipulos> discipuloses) {
		this.discipuloses = discipuloses;
	}

	/**
	 * @return the participas
	 */
	public Set<Participa> getParticipas() {
		return participas;
	}

	/**
	 * @param participas the participas to set
	 */
	public void setParticipas(Set<Participa> participas) {
		this.participas = participas;
	}

	/**
	 * @return the formacaoacademicas
	 */
	public Set<Formacaoacademica> getFormacaoacademicas() {
		return formacaoacademicas;
	}

	/**
	 * @param formacaoacademicas the formacaoacademicas to set
	 */
	public void setFormacaoacademicas(Set<Formacaoacademica> formacaoacademicas) {
		this.formacaoacademicas = formacaoacademicas;
	}

	/**
	 * @return the funeclesiasticasdiscipuloses
	 */
	public Set<Funeclesiasticasdiscipulos> getFuneclesiasticasdiscipuloses() {
		return funeclesiasticasdiscipuloses;
	}

	/**
	 * @param funeclesiasticasdiscipuloses the funeclesiasticasdiscipuloses to set
	 */
	public void setFuneclesiasticasdiscipuloses(
			Set<Funeclesiasticasdiscipulos> funeclesiasticasdiscipuloses) {
		this.funeclesiasticasdiscipuloses = funeclesiasticasdiscipuloses;
	}

	/**
	 * @return the disCPF
	 */
	public String getDisCPF() {
		return disCPF;
	}

	/**
	 * @param disCPF the disCPF to set
	 */
	public void setDisCPF(String disCPF) {
		this.disCPF = disCPF;
	}

	/**
	 * @return the disRG
	 */
	public String getDisRG() {
		return disRG;
	}

	/**
	 * @param disRG the disRG to set
	 */
	public void setDisRG(String disRG) {
		this.disRG = disRG;
	}

	/**
	 * @return the disDTEmissao
	 */
	public Date getDisDTEmissao() {
		return disDTEmissao;
	}

	/**
	 * @param disDTEmissao the disDTEmissao to set
	 */
	public void setDisDTEmissao(Date disDTEmissao) {
		this.disDTEmissao = disDTEmissao;
	}

	/**
	 * @return the disTitEleitor
	 */
	public String getDisTitEleitor() {
		return disTitEleitor;
	}

	/**
	 * @param disTitEleitor the disTitEleitor to set
	 */
	public void setDisTitEleitor(String disTitEleitor) {
		this.disTitEleitor = disTitEleitor;
	}

	/**
	 * @return the disZona
	 */
	public String getDisZona() {
		return disZona;
	}

	/**
	 * @param disZona the disZona to set
	 */
	public void setDisZona(String disZona) {
		this.disZona = disZona;
	}

	/**
	 * @return the disSecao
	 */
	public String getDisSecao() {
		return disSecao;
	}

	/**
	 * @param disSecao the disSecao to set
	 */
	public void setDisSecao(String disSecao) {
		this.disSecao = disSecao;
	}
}
