package br.com.pais.entities;

// Generated 14/05/2010 14:52:28 by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Documentos generated by hbm2java
 */
@Entity
@Table(name = "documentos", catalog = "wwwpais_pais", uniqueConstraints = {
		@UniqueConstraint(columnNames = "docTituloEleitor"),
		@UniqueConstraint(columnNames = "docCPF"),
		@UniqueConstraint(columnNames = "docRG") })
public class Documentos implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "docCod", unique = true, nullable = false)
	private Integer docCod;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "docDisCod", nullable = false)
	private Discipulos discipulos;
	
	@Column(name = "docRG", unique = true, length = 10)
	private String docRg;
	
	@Column(name = "docRGEmissor", length = 5)
	private String docRgemissor;
	
	@Column(name = "docTituloEleitor", unique = true, length = 10)
	private String docTituloEleitor;
	
	@Column(name = "docSecao")
	private Integer docSecao;
	
	@Column(name = "docZona")
	private Integer docZona;
	
	@Column(name = "docCPF", unique = true, nullable = false, length = 11)
	private String docCpf;

	/**
	 * @return the docCod
	 */
	public Integer getDocCod() {
		return docCod;
	}

	/**
	 * @param docCod the docCod to set
	 */
	public void setDocCod(Integer docCod) {
		this.docCod = docCod;
	}

	/**
	 * @return the discipulos
	 */
	public Discipulos getDiscipulos() {
		return discipulos;
	}

	/**
	 * @param discipulos the discipulos to set
	 */
	public void setDiscipulos(Discipulos discipulos) {
		this.discipulos = discipulos;
	}

	/**
	 * @return the docRg
	 */
	public String getDocRg() {
		return docRg;
	}

	/**
	 * @param docRg the docRg to set
	 */
	public void setDocRg(String docRg) {
		this.docRg = docRg;
	}

	/**
	 * @return the docRgemissor
	 */
	public String getDocRgemissor() {
		return docRgemissor;
	}

	/**
	 * @param docRgemissor the docRgemissor to set
	 */
	public void setDocRgemissor(String docRgemissor) {
		this.docRgemissor = docRgemissor;
	}

	/**
	 * @return the docTituloEleitor
	 */
	public String getDocTituloEleitor() {
		return docTituloEleitor;
	}

	/**
	 * @param docTituloEleitor the docTituloEleitor to set
	 */
	public void setDocTituloEleitor(String docTituloEleitor) {
		this.docTituloEleitor = docTituloEleitor;
	}

	/**
	 * @return the docSecao
	 */
	public Integer getDocSecao() {
		return docSecao;
	}

	/**
	 * @param docSecao the docSecao to set
	 */
	public void setDocSecao(Integer docSecao) {
		this.docSecao = docSecao;
	}

	/**
	 * @return the docZona
	 */
	public Integer getDocZona() {
		return docZona;
	}

	/**
	 * @param docZona the docZona to set
	 */
	public void setDocZona(Integer docZona) {
		this.docZona = docZona;
	}

	/**
	 * @return the docCpf
	 */
	public String getDocCpf() {
		return docCpf;
	}

	/**
	 * @param docCpf the docCpf to set
	 */
	public void setDocCpf(String docCpf) {
		this.docCpf = docCpf;
	}
 
 
}
