package br.com.pais.entities;

// Generated 12/09/2010 22:48:01 by Hibernate Tools 3.3.0.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Encontros generated by hbm2java
 */
@Entity
@Table(name = "encontros", catalog = "wwwpais_sistema")
public class Encontros implements java.io.Serializable {

	private int encCod;
	private Logradouro logradouro;
	private Date encDataRealizacao;
	private String encDescricao;
	private Set<Participa> participas = new HashSet<Participa>(0);

	public Encontros() {
	}

	public Encontros(int encCod, Logradouro logradouro) {
		this.encCod = encCod;
		this.logradouro = logradouro;
	}

	public Encontros(int encCod, Logradouro logradouro, Date encDataRealizacao,
			String encDescricao, Set<Participa> participas) {
		this.encCod = encCod;
		this.logradouro = logradouro;
		this.encDataRealizacao = encDataRealizacao;
		this.encDescricao = encDescricao;
		this.participas = participas;
	}

	@Id
	@Column(name = "EncCod", unique = true, nullable = false)
	public int getEncCod() {
		return this.encCod;
	}

	public void setEncCod(int encCod) {
		this.encCod = encCod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EncLocal", nullable = false)
	public Logradouro getLogradouro() {
		return this.logradouro;
	}

	public void setLogradouro(Logradouro logradouro) {
		this.logradouro = logradouro;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EncDataRealizacao", length = 10)
	public Date getEncDataRealizacao() {
		return this.encDataRealizacao;
	}

	public void setEncDataRealizacao(Date encDataRealizacao) {
		this.encDataRealizacao = encDataRealizacao;
	}

	@Column(name = "EncDescricao")
	public String getEncDescricao() {
		return this.encDescricao;
	}

	public void setEncDescricao(String encDescricao) {
		this.encDescricao = encDescricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "encontros")
	public Set<Participa> getParticipas() {
		return this.participas;
	}

	public void setParticipas(Set<Participa> participas) {
		this.participas = participas;
	}

}
