package br.com.pais.entities;

// Generated 06/01/2011 15:01:09 by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Formacaoeclesiasticas generated by hbm2java
 */
@Entity
@Table(name = "formacaoeclesiasticas", catalog = "wwwpais_sistema", uniqueConstraints = @UniqueConstraint(columnNames = "forEcDescricao"))
public class Formacaoeclesiasticas implements java.io.Serializable {

	private Integer forEcCod;
	private String forEcDescricao;
	private Set<Discipulos> discipuloses = new HashSet<Discipulos>(0);

	public Formacaoeclesiasticas() {
	}

	public Formacaoeclesiasticas(String forEcDescricao) {
		this.forEcDescricao = forEcDescricao;
	}

	public Formacaoeclesiasticas(String forEcDescricao,
			Set<Discipulos> discipuloses) {
		this.forEcDescricao = forEcDescricao;
		this.discipuloses = discipuloses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "forEcCod", unique = true, nullable = false)
	public Integer getForEcCod() {
		return this.forEcCod;
	}

	public void setForEcCod(Integer forEcCod) {
		this.forEcCod = forEcCod;
	}

	@Column(name = "forEcDescricao", unique = true, nullable = false, length = 60)
	public String getForEcDescricao() {
		return this.forEcDescricao;
	}

	public void setForEcDescricao(String forEcDescricao) {
		this.forEcDescricao = forEcDescricao;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "formacaoeclesiasticases")
	public Set<Discipulos> getDiscipuloses() {
		return this.discipuloses;
	}

	public void setDiscipuloses(Set<Discipulos> discipuloses) {
		this.discipuloses = discipuloses;
	}

}
