package br.com.pais.entities;

// Generated 17/01/2011 11:25:41 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Fotosbases generated by hbm2java
 */
@Entity
@Table(name = "fotosbases", catalog = "wwwpais_sistema")
public class Fotosbases implements java.io.Serializable {

	private Integer codFoto;
	private Bases bases;
	private String foto;
	private String legenda;
	
	public Fotosbases() {
	}

	public Fotosbases(Bases bases, String foto) {
		this.bases = bases;
		this.foto = foto;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "codFoto", unique = true, nullable = false)
	public Integer getCodFoto() {
		return this.codFoto;
	}

	public void setCodFoto(Integer codFoto) {
		this.codFoto = codFoto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "basCod", nullable = false)
	public Bases getBases() {
		return this.bases;
	}

	public void setBases(Bases bases) {
		this.bases = bases;
	}

	@Column(name = "foto", nullable = false, length = 100)
	public String getFoto() {
		return this.foto;
	}

	public void setFoto(String foto) {
		this.foto = foto;
	}

	/**
	 * @return the legenda
	 */
	@Column(name = "legenda", length = 100)
	public String getLegenda() {
		return legenda;
	}

	/**
	 * @param legenda the legenda to set
	 */
	public void setLegenda(String legenda) {
		this.legenda = legenda;
	}

	
	
}
