package br.com.pais.entities;

// Generated 14/05/2010 14:52:28 by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Funcaoeclesiasticas generated by hbm2java
 */
@Entity
@Table(name = "funcaoeclesiasticas", catalog = "wwwpais_pais", uniqueConstraints = @UniqueConstraint(columnNames = "funDescricao"))
public class Funcaoeclesiasticas implements java.io.Serializable {

	@Id
	@Column(name = "funCod", unique = true, nullable = false)
	private int funCod;
	
	@Column(name = "funDescricao", unique = true, length = 60)
	private String funDescricao;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "funcaoeclesiasticas")
	private Set<Funeclesiasticasdiscipulos> funeclesiasticasdiscipuloses = new HashSet<Funeclesiasticasdiscipulos>(0);

	/**
	 * @return the funCod
	 */
	public int getFunCod() {
		return funCod;
	}

	/**
	 * @param funCod the funCod to set
	 */
	public void setFunCod(int funCod) {
		this.funCod = funCod;
	}

	/**
	 * @return the funDescricao
	 */
	public String getFunDescricao() {
		return funDescricao;
	}

	/**
	 * @param funDescricao the funDescricao to set
	 */
	public void setFunDescricao(String funDescricao) {
		this.funDescricao = funDescricao;
	}

	/**
	 * @return the funeclesiasticasdiscipuloses
	 */
	public Set<Funeclesiasticasdiscipulos> getFuneclesiasticasdiscipuloses() {
		return funeclesiasticasdiscipuloses;
	}

	/**
	 * @param funeclesiasticasdiscipuloses the funeclesiasticasdiscipuloses to set
	 */
	public void setFuneclesiasticasdiscipuloses(
			Set<Funeclesiasticasdiscipulos> funeclesiasticasdiscipuloses) {
		this.funeclesiasticasdiscipuloses = funeclesiasticasdiscipuloses;
	}


}
