package br.com.pais.entities;

// Generated 14/05/2010 14:52:28 by Hibernate Tools 3.3.0.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Funeclesiasticasdiscipulos generated by hbm2java
 */
@Entity
@Table(name = "funeclesiasticasdiscipulos", catalog = "wwwpais_pais")
public class Funeclesiasticasdiscipulos implements java.io.Serializable {

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "funCod", column = @Column(name = "funCod", nullable = false)),
			@AttributeOverride(name = "disCod", column = @Column(name = "disCod", nullable = false)) })
	private FuneclesiasticasdiscipulosId id;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "funCod", nullable = false, insertable = false, updatable = false)
	private Funcaoeclesiasticas funcaoeclesiasticas;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "disCod", nullable = false, insertable = false, updatable = false)
	private Discipulos discipulos;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "fundisData", nullable = false, length = 10)
	private Date fundisData;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "funeclesiasticasdiscipulos")
	private Set<Celulas> celulases = new HashSet<Celulas>(0);

	/**
	 * @return the id
	 */
	public FuneclesiasticasdiscipulosId getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(FuneclesiasticasdiscipulosId id) {
		this.id = id;
	}

	/**
	 * @return the funcaoeclesiasticas
	 */
	public Funcaoeclesiasticas getFuncaoeclesiasticas() {
		return funcaoeclesiasticas;
	}

	/**
	 * @param funcaoeclesiasticas the funcaoeclesiasticas to set
	 */
	public void setFuncaoeclesiasticas(Funcaoeclesiasticas funcaoeclesiasticas) {
		this.funcaoeclesiasticas = funcaoeclesiasticas;
	}

	/**
	 * @return the discipulos
	 */
	public Discipulos getDiscipulos() {
		return discipulos;
	}

	/**
	 * @param discipulos the discipulos to set
	 */
	public void setDiscipulos(Discipulos discipulos) {
		this.discipulos = discipulos;
	}

	/**
	 * @return the fundisData
	 */
	public Date getFundisData() {
		return fundisData;
	}

	/**
	 * @param fundisData the fundisData to set
	 */
	public void setFundisData(Date fundisData) {
		this.fundisData = fundisData;
	}

	/**
	 * @return the celulases
	 */
	public Set<Celulas> getCelulases() {
		return celulases;
	}

	/**
	 * @param celulases the celulases to set
	 */
	public void setCelulases(Set<Celulas> celulases) {
		this.celulases = celulases;
	}


}
