package br.com.pais.entities;

// Generated 14/05/2010 14:52:28 by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Localidade generated by hbm2java
 */
@Entity
@Table(name = "localidade", catalog = "wwwpais_pais")
public class Localidade implements java.io.Serializable {

	@Id
	@Column(name = "LOC_NU_SEQUENCIAL", unique = true, nullable = false)
	private int locNuSequencial;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tbl_estado_UFE_SG", nullable = false)
	private Estado estado;
	
	@Column(name = "LOC_NU_SUB", length = 50)
	private String locNuSub;
	
	@Column(name = "LOC_NO", length = 60)
	private String locNo;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "localidade")
	private Set<Bairro> bairros = new HashSet<Bairro>(0);

	/**
	 * @return the locNuSequencial
	 */
	public int getLocNuSequencial() {
		return locNuSequencial;
	}

	/**
	 * @param locNuSequencial the locNuSequencial to set
	 */
	public void setLocNuSequencial(int locNuSequencial) {
		this.locNuSequencial = locNuSequencial;
	}

	/**
	 * @return the estado
	 */
	public Estado getEstado() {
		return estado;
	}

	/**
	 * @param estado the estado to set
	 */
	public void setEstado(Estado estado) {
		this.estado = estado;
	}

	/**
	 * @return the locNuSub
	 */
	public String getLocNuSub() {
		return locNuSub;
	}

	/**
	 * @param locNuSub the locNuSub to set
	 */
	public void setLocNuSub(String locNuSub) {
		this.locNuSub = locNuSub;
	}

	/**
	 * @return the locNo
	 */
	public String getLocNo() {
		return locNo;
	}

	/**
	 * @param locNo the locNo to set
	 */
	public void setLocNo(String locNo) {
		this.locNo = locNo;
	}

	/**
	 * @return the bairros
	 */
	public Set<Bairro> getBairros() {
		return bairros;
	}

	/**
	 * @param bairros the bairros to set
	 */
	public void setBairros(Set<Bairro> bairros) {
		this.bairros = bairros;
	}

	
}
