package br.com.pais.entities;

// Generated 14/05/2010 14:52:28 by Hibernate Tools 3.3.0.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Movimento generated by hbm2java
 */
@Entity
@Table(name = "movimento")
public class Movimento implements java.io.Serializable {

	@Id
	@Column(name = "movCod", unique = true, nullable = false)
	private int movCod;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
			@JoinColumn(name = "celCod", referencedColumnName = "celCod", nullable = false),
			@JoinColumn(name = "funCod", referencedColumnName = "funCod", nullable = false),
			@JoinColumn(name = "disCod", referencedColumnName = "disCod", nullable = false) })
	private Celulas celulas;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "movData", length = 10)
	private Date movData;
	
	@Column(name = "movTipo", length = 60)
	private String movTipo;
	
	@Column(name = "movValor", precision = 2, scale = 0)
	private Byte movValor;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "movimento")
	private Set<Repasse> repasse = new HashSet<Repasse>(0);

	/**
	 * @return the movCod
	 */
	public int getMovCod() {
		return movCod;
	}

	/**
	 * @param movCod the movCod to set
	 */
	public void setMovCod(int movCod) {
		this.movCod = movCod;
	}

	/**
	 * @return the celulas
	 */
	public Celulas getCelulas() {
		return celulas;
	}

	/**
	 * @param celulas the celulas to set
	 */
	public void setCelulas(Celulas celulas) {
		this.celulas = celulas;
	}

	/**
	 * @return the movData
	 */
	public Date getMovData() {
		return movData;
	}

	/**
	 * @param movData the movData to set
	 */
	public void setMovData(Date movData) {
		this.movData = movData;
	}

	/**
	 * @return the movTipo
	 */
	public String getMovTipo() {
		return movTipo;
	}

	/**
	 * @param movTipo the movTipo to set
	 */
	public void setMovTipo(String movTipo) {
		this.movTipo = movTipo;
	}

	/**
	 * @return the movValor
	 */
	public Byte getMovValor() {
		return movValor;
	}

	/**
	 * @param movValor the movValor to set
	 */
	public void setMovValor(Byte movValor) {
		this.movValor = movValor;
	}

	/**
	 * @return the repasse
	 */
	public Set<Repasse> getRepasse() {
		return repasse;
	}

	/**
	 * @param repasse the repasse to set
	 */
	public void setRepasse(Set<Repasse> repasse) {
		this.repasse = repasse;
	}

}
