package br.com.pais.entities;

// Generated 12/09/2010 22:48:01 by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ParticipaId generated by hbm2java
 */
@Embeddable
public class ParticipaId implements java.io.Serializable {

	private int disCod;
	private int encCod;

	public ParticipaId() {
	}

	public ParticipaId(int disCod, int encCod) {
		this.disCod = disCod;
		this.encCod = encCod;
	}

	@Column(name = "disCod", nullable = false)
	public int getDisCod() {
		return this.disCod;
	}

	public void setDisCod(int disCod) {
		this.disCod = disCod;
	}

	@Column(name = "EncCod", nullable = false)
	public int getEncCod() {
		return this.encCod;
	}

	public void setEncCod(int encCod) {
		this.encCod = encCod;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ParticipaId))
			return false;
		ParticipaId castOther = (ParticipaId) other;

		return (this.getDisCod() == castOther.getDisCod())
				&& (this.getEncCod() == castOther.getEncCod());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getDisCod();
		result = 37 * result + this.getEncCod();
		return result;
	}

}
