package br.com.pais.entities;

// Generated 14/05/2010 14:52:28 by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RepasseId generated by hbm2java
 */
@Embeddable
public class RepasseId implements java.io.Serializable {

	@Column(name = "movCod", nullable = false)
	private int movCod;

	@Column(name = "disCod", nullable = false)
	private int disCod;

	

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RepasseId))
			return false;
		RepasseId castOther = (RepasseId) other;

		return (this.getMovCod() == castOther.getMovCod())
				&& (this.getDisCod() == castOther.getDisCod());
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMovCod();
		result = 37 * result + this.getDisCod();
		return result;
	}

	/**
	 * @return the movCod
	 */
	public int getMovCod() {
		return movCod;
	}

	/**
	 * @param movCod the movCod to set
	 */
	public void setMovCod(int movCod) {
		this.movCod = movCod;
	}

	/**
	 * @return the disCod
	 */
	public int getDisCod() {
		return disCod;
	}

	/**
	 * @param disCod the disCod to set
	 */
	public void setDisCod(int disCod) {
		this.disCod = disCod;
	}

}
