package br.com.pais.entities;

// Generated 13/09/2010 13:58:41 by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Teldiscipulos generated by hbm2java
 */
@Entity
@Table(name = "teldiscipulos", catalog = "wwwpais_sistema")
public class Teldiscipulos implements java.io.Serializable {

	private Integer telDisCod;
	private Discipulos discipulos;
	private String telDisDescricao;
	private String telDisNumero;

	public Teldiscipulos() {
	}

	public Teldiscipulos(Discipulos discipulos, String telDisDescricao,
			String telDisNumero) {
		this.discipulos = discipulos;
		this.telDisDescricao = telDisDescricao;
		this.telDisNumero = telDisNumero;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "telDisCod", unique = true, nullable = false)
	public Integer getTelDisCod() {
		return this.telDisCod;
	}

	public void setTelDisCod(Integer telDisCod) {
		this.telDisCod = telDisCod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "disCod", nullable = false)
	public Discipulos getDiscipulos() {
		return this.discipulos;
	}

	public void setDiscipulos(Discipulos discipulos) {
		this.discipulos = discipulos;
	}

	@Column(name = "telDisDescricao", nullable = false, length = 15)
	public String getTelDisDescricao() {
		return this.telDisDescricao;
	}

	public void setTelDisDescricao(String telDisDescricao) {
		this.telDisDescricao = telDisDescricao;
	}

	@Column(name = "telDisNumero", nullable = false, length = 15)
	public String getTelDisNumero() {
		return this.telDisNumero;
	}

	public void setTelDisNumero(String telDisNumero) {
		this.telDisNumero = telDisNumero;
	}

}
